compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@graphql-codegen/cli@*":
    dependencies:
      graphql: "^16.9.0"
  "@graphql-codegen/core@*":
    dependencies:
      graphql: "^16.9.0"
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      graphql: "^16.9.0"
  "@graphql-codegen/schema-ast@*":
    dependencies:
      graphql: "^16.9.0"
  "@graphql-codegen/typescript@*":
    dependencies:
      graphql: "^16.9.0"
  "@graphql-codegen/visitor-plugin-common@*":
    dependencies:
      graphql: "^16.9.0"
  "@mermaid-js/mermaid-cli@*":
    peerDependenciesMeta:
      puppeteer:
        optional: true

yarnPath: .yarn/releases/yarn-4.12.0.cjs

# re-enable a specific script by combining enableScripts and dependenciesMeta.
enableScripts: false
