%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/v4/geometry.queries"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: Access[9], Access[10], Object[11]<br />2: PgSelect[8]<br />3: Connection[12]<br />4: ConnectionItems[14]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 14<br /><br />ROOT Connectionᐸ8ᐳ[12]"):::bucket
    Bucket3("Bucket 3 (listItem)<br /><br />ROOT __Item{3}ᐸ14ᐳ[18]"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 19<br /><br />ROOT PgSelectSingle{3}ᐸgeomᐳ[19]"):::bucket
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 21<br /><br />ROOT PgClassExpression{4}ᐸ__geom__.”point”ᐳ[21]"):::bucket
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 23<br /><br />ROOT PgClassExpression{4}ᐸ__geom__.”line”ᐳ[23]"):::bucket
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 25<br /><br />ROOT PgClassExpression{4}ᐸ__geom__.”lseg”ᐳ[25]"):::bucket
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 27<br /><br />ROOT PgClassExpression{4}ᐸ__geom__.”box”ᐳ[27]"):::bucket
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 29<br /><br />ROOT PgClassExpression{4}ᐸ__geom__.”open_path”ᐳ[29]"):::bucket
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 31<br /><br />ROOT PgClassExpression{4}ᐸ__geom__.”closed_path”ᐳ[31]"):::bucket
    Bucket11("Bucket 11 (nullableBoundary)<br />Deps: 33<br /><br />ROOT PgClassExpression{4}ᐸ__geom__.”polygon”ᐳ[33]"):::bucket
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 35<br /><br />ROOT PgClassExpression{4}ᐸ__geom__.”circle”ᐳ[35]"):::bucket
    Bucket13("Bucket 13 (listItem)<br /><br />ROOT __Item{13}ᐸ22ᐳ[37]"):::bucket
    Bucket14("Bucket 14 (listItem)<br /><br />ROOT __Item{14}ᐸ24ᐳ[38]"):::bucket
    Bucket15("Bucket 15 (listItem)<br /><br />ROOT __Item{15}ᐸ26ᐳ[39]"):::bucket
    Bucket16("Bucket 16 (listItem)<br /><br />ROOT __Item{16}ᐸ28ᐳ[40]"):::bucket
    Bucket17("Bucket 17 (listItem)<br /><br />ROOT __Item{17}ᐸ30ᐳ[41]"):::bucket
    Bucket18("Bucket 18 (listItem)<br /><br />ROOT __Item{18}ᐸ32ᐳ[42]"):::bucket
    Bucket19("Bucket 19 (listItem)<br /><br />ROOT __Item{19}ᐸ34ᐳ[43]"):::bucket
    Bucket20("Bucket 20 (listItem)<br /><br />ROOT __Item{20}ᐸ36ᐳ[44]"):::bucket
    Bucket21("Bucket 21 (nullableBoundary)<br />Deps: 37<br /><br />ROOT __Item{13}ᐸ22ᐳ[37]"):::bucket
    Bucket22("Bucket 22 (nullableBoundary)<br />Deps: 38<br /><br />ROOT __Item{14}ᐸ24ᐳ[38]"):::bucket
    Bucket23("Bucket 23 (nullableBoundary)<br />Deps: 39<br /><br />ROOT __Item{15}ᐸ26ᐳ[39]"):::bucket
    Bucket24("Bucket 24 (nullableBoundary)<br />Deps: 40<br /><br />ROOT __Item{16}ᐸ28ᐳ[40]"):::bucket
    Bucket25("Bucket 25 (nullableBoundary)<br />Deps: 41<br /><br />ROOT __Item{17}ᐸ30ᐳ[41]"):::bucket
    Bucket26("Bucket 26 (nullableBoundary)<br />Deps: 42<br /><br />ROOT __Item{18}ᐸ32ᐳ[42]"):::bucket
    Bucket27("Bucket 27 (nullableBoundary)<br />Deps: 43<br /><br />ROOT __Item{19}ᐸ34ᐳ[43]"):::bucket
    Bucket28("Bucket 28 (nullableBoundary)<br />Deps: 44<br /><br />ROOT __Item{20}ᐸ36ᐳ[44]"):::bucket
    Bucket29("Bucket 29 (listItem)<br /><br />ROOT __Item{29}ᐸ51ᐳ[60]"):::bucket
    Bucket30("Bucket 30 (listItem)<br /><br />ROOT __Item{30}ᐸ57ᐳ[61]"):::bucket
    Bucket31("Bucket 31 (listItem)<br /><br />ROOT __Item{31}ᐸ58ᐳ[62]"):::bucket
    Bucket32("Bucket 32 (listItem)<br /><br />ROOT __Item{32}ᐸ69ᐳ[92]"):::bucket
    Bucket33("Bucket 33 (listItem)<br /><br />ROOT __Item{33}ᐸ75ᐳ[93]"):::bucket
    Bucket34("Bucket 34 (listItem)<br /><br />ROOT __Item{34}ᐸ76ᐳ[94]"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5 & Bucket6 & Bucket7 & Bucket8 & Bucket9 & Bucket10 & Bucket11 & Bucket12 & Bucket13 & Bucket14 & Bucket15 & Bucket16 & Bucket17 & Bucket18 & Bucket19 & Bucket20
    Bucket9 --> Bucket30
    Bucket10 --> Bucket31
    Bucket11 --> Bucket29
    Bucket13 --> Bucket21
    Bucket14 --> Bucket22
    Bucket15 --> Bucket23
    Bucket16 --> Bucket24
    Bucket17 --> Bucket25
    Bucket18 --> Bucket26
    Bucket19 --> Bucket27
    Bucket20 --> Bucket28
    Bucket25 --> Bucket33
    Bucket26 --> Bucket34
    Bucket27 --> Bucket32

    %% plan dependencies
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    PgSelect8[["PgSelect[8∈0] ➊<br />ᐸgeomᐳ"]]:::plan
    Object11 --> PgSelect8
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    Connection12[["Connection[12∈0] ➊<br />ᐸ8ᐳ"]]:::plan
    PgSelect8 --> Connection12
    ConnectionItems14[["ConnectionItems[14∈0] ➊"]]:::plan
    Connection12 --> ConnectionItems14
    __Item18[/"__Item[18∈3]<br />ᐸ14ᐳ"\]:::itemplan
    ConnectionItems14 ==> __Item18
    PgSelectSingle19{{"PgSelectSingle[19∈3]<br />ᐸgeomᐳ"}}:::plan
    __Item18 --> PgSelectSingle19
    PgClassExpression20{{"PgClassExpression[20∈4]<br />ᐸ__geom__.”id”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression20
    PgClassExpression21{{"PgClassExpression[21∈4]<br />ᐸ__geom__.”point”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression21
    PgClassExpression22{{"PgClassExpression[22∈4]<br />ᐸ__geom__.”points”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression22
    PgClassExpression23{{"PgClassExpression[23∈4]<br />ᐸ__geom__.”line”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression23
    PgClassExpression24{{"PgClassExpression[24∈4]<br />ᐸ__geom__.”lines”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression24
    PgClassExpression25{{"PgClassExpression[25∈4]<br />ᐸ__geom__.”lseg”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression25
    PgClassExpression26{{"PgClassExpression[26∈4]<br />ᐸ__geom__.”lsegs”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression26
    PgClassExpression27{{"PgClassExpression[27∈4]<br />ᐸ__geom__.”box”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression27
    PgClassExpression28{{"PgClassExpression[28∈4]<br />ᐸ__geom__.”boxes”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression28
    PgClassExpression29{{"PgClassExpression[29∈4]<br />ᐸ__geom__.”open_path”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression29
    PgClassExpression30{{"PgClassExpression[30∈4]<br />ᐸ__geom__.”open_paths”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression30
    PgClassExpression31{{"PgClassExpression[31∈4]<br />ᐸ__geom__.”closed_path”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression31
    PgClassExpression32{{"PgClassExpression[32∈4]<br />ᐸ__geom__.”closed_paths”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression32
    PgClassExpression33{{"PgClassExpression[33∈4]<br />ᐸ__geom__.”polygon”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression33
    PgClassExpression34{{"PgClassExpression[34∈4]<br />ᐸ__geom__.”polygons”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression34
    PgClassExpression35{{"PgClassExpression[35∈4]<br />ᐸ__geom__.”circle”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression35
    PgClassExpression36{{"PgClassExpression[36∈4]<br />ᐸ__geom__.”circles”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression36
    Access45{{"Access[45∈5]<br />ᐸ21.xᐳ"}}:::plan
    PgClassExpression21 --> Access45
    Access53{{"Access[53∈5]<br />ᐸ21.yᐳ"}}:::plan
    Access45 o--o Access53
    Access46{{"Access[46∈6]<br />ᐸ23.aᐳ"}}:::plan
    PgClassExpression23 --> Access46
    Access54{{"Access[54∈6]<br />ᐸ23.bᐳ"}}:::plan
    Access46 o--o Access54
    Access78{{"Access[78∈6]<br />ᐸ23.a.xᐳ"}}:::plan
    Access54 o--o Access78
    Access82{{"Access[82∈6]<br />ᐸ23.b.xᐳ"}}:::plan
    Access78 o--o Access82
    Access85{{"Access[85∈6]<br />ᐸ23.a.yᐳ"}}:::plan
    Access82 o--o Access85
    Access89{{"Access[89∈6]<br />ᐸ23.b.yᐳ"}}:::plan
    Access85 o--o Access89
    Access47{{"Access[47∈7]<br />ᐸ25.aᐳ"}}:::plan
    PgClassExpression25 --> Access47
    Access55{{"Access[55∈7]<br />ᐸ25.bᐳ"}}:::plan
    Access47 o--o Access55
    Access79{{"Access[79∈7]<br />ᐸ25.a.xᐳ"}}:::plan
    Access55 o--o Access79
    Access83{{"Access[83∈7]<br />ᐸ25.b.xᐳ"}}:::plan
    Access79 o--o Access83
    Access86{{"Access[86∈7]<br />ᐸ25.a.yᐳ"}}:::plan
    Access83 o--o Access86
    Access90{{"Access[90∈7]<br />ᐸ25.b.yᐳ"}}:::plan
    Access86 o--o Access90
    Access48{{"Access[48∈8]<br />ᐸ27.aᐳ"}}:::plan
    PgClassExpression27 --> Access48
    Access56{{"Access[56∈8]<br />ᐸ27.bᐳ"}}:::plan
    Access48 o--o Access56
    Access80{{"Access[80∈8]<br />ᐸ27.a.xᐳ"}}:::plan
    Access56 o--o Access80
    Access84{{"Access[84∈8]<br />ᐸ27.b.xᐳ"}}:::plan
    Access80 o--o Access84
    Access87{{"Access[87∈8]<br />ᐸ27.a.yᐳ"}}:::plan
    Access84 o--o Access87
    Access91{{"Access[91∈8]<br />ᐸ27.b.yᐳ"}}:::plan
    Access87 o--o Access91
    Access49{{"Access[49∈9]<br />ᐸ29.isOpenᐳ"}}:::plan
    PgClassExpression29 --> Access49
    Access57{{"Access[57∈9]<br />ᐸ29.pointsᐳ"}}:::plan
    PgClassExpression29 --> Access57
    Access50{{"Access[50∈10]<br />ᐸ31.isOpenᐳ"}}:::plan
    PgClassExpression31 --> Access50
    Access58{{"Access[58∈10]<br />ᐸ31.pointsᐳ"}}:::plan
    PgClassExpression31 --> Access58
    Access51{{"Access[51∈11]<br />ᐸ33.pointsᐳ"}}:::plan
    PgClassExpression33 --> Access51
    Access52{{"Access[52∈12]<br />ᐸ35.centerᐳ"}}:::plan
    PgClassExpression35 --> Access52
    Access59{{"Access[59∈12]<br />ᐸ35.radiusᐳ"}}:::plan
    Access52 o--o Access59
    Access81{{"Access[81∈12]<br />ᐸ35.center.xᐳ"}}:::plan
    Access59 o--o Access81
    Access88{{"Access[88∈12]<br />ᐸ35.center.yᐳ"}}:::plan
    Access81 o--o Access88
    __Item37[/"__Item[37∈13]<br />ᐸ22ᐳ"\]:::itemplan
    PgClassExpression22 ==> __Item37
    __Item38[/"__Item[38∈14]<br />ᐸ24ᐳ"\]:::itemplan
    PgClassExpression24 ==> __Item38
    __Item39[/"__Item[39∈15]<br />ᐸ26ᐳ"\]:::itemplan
    PgClassExpression26 ==> __Item39
    __Item40[/"__Item[40∈16]<br />ᐸ28ᐳ"\]:::itemplan
    PgClassExpression28 ==> __Item40
    __Item41[/"__Item[41∈17]<br />ᐸ30ᐳ"\]:::itemplan
    PgClassExpression30 ==> __Item41
    __Item42[/"__Item[42∈18]<br />ᐸ32ᐳ"\]:::itemplan
    PgClassExpression32 ==> __Item42
    __Item43[/"__Item[43∈19]<br />ᐸ34ᐳ"\]:::itemplan
    PgClassExpression34 ==> __Item43
    __Item44[/"__Item[44∈20]<br />ᐸ36ᐳ"\]:::itemplan
    PgClassExpression36 ==> __Item44
    Access63{{"Access[63∈21]<br />ᐸ37.xᐳ"}}:::plan
    __Item37 --> Access63
    Access71{{"Access[71∈21]<br />ᐸ37.yᐳ"}}:::plan
    Access63 o--o Access71
    Access64{{"Access[64∈22]<br />ᐸ38.aᐳ"}}:::plan
    __Item38 --> Access64
    Access72{{"Access[72∈22]<br />ᐸ38.bᐳ"}}:::plan
    Access64 o--o Access72
    Access98{{"Access[98∈22]<br />ᐸ38.a.xᐳ"}}:::plan
    Access72 o--o Access98
    Access102{{"Access[102∈22]<br />ᐸ38.b.xᐳ"}}:::plan
    Access98 o--o Access102
    Access108{{"Access[108∈22]<br />ᐸ38.a.yᐳ"}}:::plan
    Access102 o--o Access108
    Access112{{"Access[112∈22]<br />ᐸ38.b.yᐳ"}}:::plan
    Access108 o--o Access112
    Access65{{"Access[65∈23]<br />ᐸ39.aᐳ"}}:::plan
    __Item39 --> Access65
    Access73{{"Access[73∈23]<br />ᐸ39.bᐳ"}}:::plan
    Access65 o--o Access73
    Access99{{"Access[99∈23]<br />ᐸ39.a.xᐳ"}}:::plan
    Access73 o--o Access99
    Access103{{"Access[103∈23]<br />ᐸ39.b.xᐳ"}}:::plan
    Access99 o--o Access103
    Access109{{"Access[109∈23]<br />ᐸ39.a.yᐳ"}}:::plan
    Access103 o--o Access109
    Access113{{"Access[113∈23]<br />ᐸ39.b.yᐳ"}}:::plan
    Access109 o--o Access113
    Access66{{"Access[66∈24]<br />ᐸ40.aᐳ"}}:::plan
    __Item40 --> Access66
    Access74{{"Access[74∈24]<br />ᐸ40.bᐳ"}}:::plan
    Access66 o--o Access74
    Access100{{"Access[100∈24]<br />ᐸ40.a.xᐳ"}}:::plan
    Access74 o--o Access100
    Access104{{"Access[104∈24]<br />ᐸ40.b.xᐳ"}}:::plan
    Access100 o--o Access104
    Access110{{"Access[110∈24]<br />ᐸ40.a.yᐳ"}}:::plan
    Access104 o--o Access110
    Access114{{"Access[114∈24]<br />ᐸ40.b.yᐳ"}}:::plan
    Access110 o--o Access114
    Access67{{"Access[67∈25]<br />ᐸ41.isOpenᐳ"}}:::plan
    __Item41 --> Access67
    Access75{{"Access[75∈25]<br />ᐸ41.pointsᐳ"}}:::plan
    __Item41 --> Access75
    Access68{{"Access[68∈26]<br />ᐸ42.isOpenᐳ"}}:::plan
    __Item42 --> Access68
    Access76{{"Access[76∈26]<br />ᐸ42.pointsᐳ"}}:::plan
    __Item42 --> Access76
    Access69{{"Access[69∈27]<br />ᐸ43.pointsᐳ"}}:::plan
    __Item43 --> Access69
    Access70{{"Access[70∈28]<br />ᐸ44.centerᐳ"}}:::plan
    __Item44 --> Access70
    Access77{{"Access[77∈28]<br />ᐸ44.radiusᐳ"}}:::plan
    Access70 o--o Access77
    Access101{{"Access[101∈28]<br />ᐸ44.center.xᐳ"}}:::plan
    Access77 o--o Access101
    Access111{{"Access[111∈28]<br />ᐸ44.center.yᐳ"}}:::plan
    Access101 o--o Access111
    __Item60[/"__Item[60∈29]<br />ᐸ51ᐳ"\]:::itemplan
    Access51 ==> __Item60
    Access95{{"Access[95∈29]<br />ᐸ60.xᐳ"}}:::plan
    __Item60 --> Access95
    Access105{{"Access[105∈29]<br />ᐸ60.yᐳ"}}:::plan
    Access95 o--o Access105
    __Item61[/"__Item[61∈30]<br />ᐸ57ᐳ"\]:::itemplan
    Access57 ==> __Item61
    Access96{{"Access[96∈30]<br />ᐸ61.xᐳ"}}:::plan
    __Item61 --> Access96
    Access106{{"Access[106∈30]<br />ᐸ61.yᐳ"}}:::plan
    Access96 o--o Access106
    __Item62[/"__Item[62∈31]<br />ᐸ58ᐳ"\]:::itemplan
    Access58 ==> __Item62
    Access97{{"Access[97∈31]<br />ᐸ62.xᐳ"}}:::plan
    __Item62 --> Access97
    Access107{{"Access[107∈31]<br />ᐸ62.yᐳ"}}:::plan
    Access97 o--o Access107
    __Item92[/"__Item[92∈32]<br />ᐸ69ᐳ"\]:::itemplan
    Access69 ==> __Item92
    Access115{{"Access[115∈32]<br />ᐸ92.xᐳ"}}:::plan
    __Item92 --> Access115
    Access118{{"Access[118∈32]<br />ᐸ92.yᐳ"}}:::plan
    Access115 o--o Access118
    __Item93[/"__Item[93∈33]<br />ᐸ75ᐳ"\]:::itemplan
    Access75 ==> __Item93
    Access116{{"Access[116∈33]<br />ᐸ93.xᐳ"}}:::plan
    __Item93 --> Access116
    Access119{{"Access[119∈33]<br />ᐸ93.yᐳ"}}:::plan
    Access116 o--o Access119
    __Item94[/"__Item[94∈34]<br />ᐸ76ᐳ"\]:::itemplan
    Access76 ==> __Item94
    Access117{{"Access[117∈34]<br />ᐸ94.xᐳ"}}:::plan
    __Item94 --> Access117
    Access120{{"Access[120∈34]<br />ᐸ94.yᐳ"}}:::plan
    Access117 o--o Access120

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect8,Access9,Access10,Object11,Connection12,ConnectionItems14 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1 bucket1
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item18,PgSelectSingle19 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression20,PgClassExpression21,PgClassExpression22,PgClassExpression23,PgClassExpression24,PgClassExpression25,PgClassExpression26,PgClassExpression27,PgClassExpression28,PgClassExpression29,PgClassExpression30,PgClassExpression31,PgClassExpression32,PgClassExpression33,PgClassExpression34,PgClassExpression35,PgClassExpression36 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,Access45,Access53 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,Access46,Access54,Access78,Access82,Access85,Access89 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,Access47,Access55,Access79,Access83,Access86,Access90 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,Access48,Access56,Access80,Access84,Access87,Access91 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,Access49,Access57 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,Access50,Access58 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11,Access51 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12,Access52,Access59,Access81,Access88 bucket12
    classDef bucket13 stroke:#3cb371
    class Bucket13,__Item37 bucket13
    classDef bucket14 stroke:#a52a2a
    class Bucket14,__Item38 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15,__Item39 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16,__Item40 bucket16
    classDef bucket17 stroke:#696969
    class Bucket17,__Item41 bucket17
    classDef bucket18 stroke:#00bfff
    class Bucket18,__Item42 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19,__Item43 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20,__Item44 bucket20
    classDef bucket21 stroke:#0000ff
    class Bucket21,Access63,Access71 bucket21
    classDef bucket22 stroke:#7fff00
    class Bucket22,Access64,Access72,Access98,Access102,Access108,Access112 bucket22
    classDef bucket23 stroke:#ff1493
    class Bucket23,Access65,Access73,Access99,Access103,Access109,Access113 bucket23
    classDef bucket24 stroke:#808000
    class Bucket24,Access66,Access74,Access100,Access104,Access110,Access114 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25,Access67,Access75 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,Access68,Access76 bucket26
    classDef bucket27 stroke:#ffff00
    class Bucket27,Access69 bucket27
    classDef bucket28 stroke:#00ffff
    class Bucket28,Access70,Access77,Access101,Access111 bucket28
    classDef bucket29 stroke:#4169e1
    class Bucket29,__Item60,Access95,Access105 bucket29
    classDef bucket30 stroke:#3cb371
    class Bucket30,__Item61,Access96,Access106 bucket30
    classDef bucket31 stroke:#a52a2a
    class Bucket31,__Item62,Access97,Access107 bucket31
    classDef bucket32 stroke:#ff00ff
    class Bucket32,__Item92,Access115,Access118 bucket32
    classDef bucket33 stroke:#f5deb3
    class Bucket33,__Item93,Access116,Access119 bucket33
    classDef bucket34 stroke:#696969
    class Bucket34,__Item94,Access117,Access120 bucket34

