%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/v4/partitions"
    Bucket0("Bucket 0 (root)<br /><br />1: 217, 221, 225, 229, 233, 237, 241<br />ᐳ: 9, 10, 101, 107, 111, 117, 121, 127, 11<br />2: 8, 15, 20, 25, 30, 35, 40, 65<br />ᐳ: 93, 218, 222, 226, 230, 234, 238, 242<br />3: 12, 17, 22, 27, 32, 37, 42, 67<br />ᐳ: 66, 68, 69<br />4: 44, 47, 50, 53, 56, 59, 62<br />5: First[92], Last[95]<br />ᐳ: PgCursor[94], PgCursor[96]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 44, 93, 218, 69, 94, 96<br /><br />ROOT Connectionᐸ8ᐳ[12]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 17, 47, 101, 222, 107<br /><br />ROOT Connectionᐸ15ᐳ[17]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 22, 50, 107, 226<br /><br />ROOT Connectionᐸ20ᐳ[22]"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 27, 53, 111, 230, 117<br /><br />ROOT Connectionᐸ25ᐳ[27]"):::bucket
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 32, 56, 117, 234<br /><br />ROOT Connectionᐸ30ᐳ[32]"):::bucket
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 37, 59, 121, 238, 127<br /><br />ROOT Connectionᐸ35ᐳ[37]"):::bucket
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 42, 62, 127, 242<br /><br />ROOT Connectionᐸ40ᐳ[42]"):::bucket
    Bucket15("Bucket 15 (listItem)<br />Deps: 93, 218<br /><br />ROOT __Item{15}ᐸ71ᐳ[78]"):::bucket
    Bucket16("Bucket 16 (listItem)<br />Deps: 101, 222, 107<br /><br />ROOT __Item{16}ᐸ47ᐳ[80]"):::bucket
    Bucket17("Bucket 17 (listItem)<br />Deps: 107, 226<br /><br />ROOT __Item{17}ᐸ50ᐳ[82]"):::bucket
    Bucket18("Bucket 18 (listItem)<br />Deps: 111, 230, 117<br /><br />ROOT __Item{18}ᐸ53ᐳ[84]"):::bucket
    Bucket19("Bucket 19 (listItem)<br />Deps: 117, 234<br /><br />ROOT __Item{19}ᐸ56ᐳ[86]"):::bucket
    Bucket20("Bucket 20 (listItem)<br />Deps: 121, 238, 127<br /><br />ROOT __Item{20}ᐸ59ᐳ[88]"):::bucket
    Bucket21("Bucket 21 (listItem)<br />Deps: 127, 242<br /><br />ROOT __Item{21}ᐸ62ᐳ[90]"):::bucket
    Bucket22("Bucket 22 (nullableBoundary)<br />Deps: 78, 79, 218, 100<br /><br />ROOT Edge{15}[79]"):::bucket
    Bucket23("Bucket 23 (nullableBoundary)<br />Deps: 81, 101, 222, 107<br /><br />ROOT PgSelectSingle{16}ᐸlocation_tagsᐳ[81]<br />1: <br />ᐳ: 102, 103, 104, 223, 105, 106, 224<br />2: PgSelectRows[158]<br />ᐳ: First[157], PgSelectSingle[159]"):::bucket
    Bucket24("Bucket 24 (nullableBoundary)<br />Deps: 83, 107, 226, 82<br /><br />ROOT PgSelectSingle{17}ᐸlocationsᐳ[83]<br />1: <br />ᐳ: 108, 227, 109, 110, 228<br />2: Connection[139]<br />3: ConnectionItems[175]"):::bucket
    Bucket25("Bucket 25 (nullableBoundary)<br />Deps: 85, 111, 230, 117<br /><br />ROOT PgSelectSingle{18}ᐸphoto_tagsᐳ[85]<br />1: <br />ᐳ: 112, 113, 114, 231, 115, 116, 232<br />2: PgSelectRows[165]<br />ᐳ: First[164], PgSelectSingle[166]"):::bucket
    Bucket26("Bucket 26 (nullableBoundary)<br />Deps: 87, 117, 234, 86<br /><br />ROOT PgSelectSingle{19}ᐸphotosᐳ[87]<br />1: <br />ᐳ: 118, 235, 119, 120, 236<br />2: Connection[145]<br />3: ConnectionItems[178]"):::bucket
    Bucket27("Bucket 27 (nullableBoundary)<br />Deps: 89, 121, 238, 127<br /><br />ROOT PgSelectSingle{20}ᐸprofile_tagsᐳ[89]<br />1: <br />ᐳ: 122, 123, 124, 239, 125, 126, 240<br />2: PgSelectRows[172]<br />ᐳ: First[171], PgSelectSingle[173]"):::bucket
    Bucket28("Bucket 28 (nullableBoundary)<br />Deps: 91, 127, 242, 90<br /><br />ROOT PgSelectSingle{21}ᐸprofilesᐳ[91]<br />1: <br />ᐳ: 128, 243, 129, 130, 244<br />2: Connection[151]<br />3: ConnectionItems[181]"):::bucket
    Bucket29("Bucket 29 (nullableBoundary)<br />Deps: 131, 218<br /><br />ROOT PgSelectSingle{22}ᐸmeasurementsᐳ[131]<br />1: <br />ᐳ: 174, 193, 194, 219, 220<br />2: PgSelectRows[201]<br />ᐳ: First[200], PgSelectSingle[202]"):::bucket
    Bucket30("Bucket 30 (nullableBoundary)<br />Deps: 159, 107<br /><br />ROOT PgSelectSingle{23}ᐸlocationsᐳ[159]"):::bucket
    Bucket31("Bucket 31 (nullableBoundary)<br />Deps: 166, 117<br /><br />ROOT PgSelectSingle{25}ᐸphotosᐳ[166]"):::bucket
    Bucket32("Bucket 32 (nullableBoundary)<br />Deps: 173, 127<br /><br />ROOT PgSelectSingle{27}ᐸprofilesᐳ[173]"):::bucket
    Bucket36("Bucket 36 (nullableBoundary)<br />Deps: 202<br /><br />ROOT PgSelectSingle{29}ᐸusersᐳ[202]"):::bucket
    Bucket37("Bucket 37 (listItem)<br /><br />ROOT __Item{37}ᐸ175ᐳ[206]"):::bucket
    Bucket38("Bucket 38 (listItem)<br /><br />ROOT __Item{38}ᐸ178ᐳ[208]"):::bucket
    Bucket39("Bucket 39 (listItem)<br /><br />ROOT __Item{39}ᐸ181ᐳ[210]"):::bucket
    Bucket40("Bucket 40 (nullableBoundary)<br />Deps: 207<br /><br />ROOT PgSelectSingle{37}ᐸlocation_tagsᐳ[207]"):::bucket
    Bucket41("Bucket 41 (nullableBoundary)<br />Deps: 209<br /><br />ROOT PgSelectSingle{38}ᐸphoto_tagsᐳ[209]"):::bucket
    Bucket42("Bucket 42 (nullableBoundary)<br />Deps: 211<br /><br />ROOT PgSelectSingle{39}ᐸprofile_tagsᐳ[211]"):::bucket
    end
    Bucket0 --> Bucket1 & Bucket2 & Bucket3 & Bucket4 & Bucket5 & Bucket6 & Bucket7
    Bucket1 --> Bucket15
    Bucket2 --> Bucket16
    Bucket3 --> Bucket17
    Bucket4 --> Bucket18
    Bucket5 --> Bucket19
    Bucket6 --> Bucket20
    Bucket7 --> Bucket21
    Bucket15 --> Bucket22
    Bucket16 --> Bucket23
    Bucket17 --> Bucket24
    Bucket18 --> Bucket25
    Bucket19 --> Bucket26
    Bucket20 --> Bucket27
    Bucket21 --> Bucket28
    Bucket22 --> Bucket29
    Bucket23 --> Bucket30
    Bucket24 --> Bucket37
    Bucket25 --> Bucket31
    Bucket26 --> Bucket38
    Bucket27 --> Bucket32
    Bucket28 --> Bucket39
    Bucket29 --> Bucket36
    Bucket37 --> Bucket40
    Bucket38 --> Bucket41
    Bucket39 --> Bucket42

    %% plan dependencies
    PgSelect8[["PgSelect[8∈0] ➊<br />ᐸmeasurements+1ᐳ"]]:::plan
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    PgSelectInlineApply217["PgSelectInlineApply[217∈0] ➊"]:::plan
    Object11 & PgSelectInlineApply217 --> PgSelect8
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    PgSelect15[["PgSelect[15∈0] ➊<br />ᐸlocation_tagsᐳ"]]:::plan
    PgSelectInlineApply221["PgSelectInlineApply[221∈0] ➊"]:::plan
    Object11 & PgSelectInlineApply221 --> PgSelect15
    PgSelect20[["PgSelect[20∈0] ➊<br />ᐸlocationsᐳ"]]:::plan
    PgSelectInlineApply225["PgSelectInlineApply[225∈0] ➊"]:::plan
    Object11 & PgSelectInlineApply225 --> PgSelect20
    PgSelect25[["PgSelect[25∈0] ➊<br />ᐸphoto_tagsᐳ"]]:::plan
    PgSelectInlineApply229["PgSelectInlineApply[229∈0] ➊"]:::plan
    Object11 & PgSelectInlineApply229 --> PgSelect25
    PgSelect30[["PgSelect[30∈0] ➊<br />ᐸphotosᐳ"]]:::plan
    PgSelectInlineApply233["PgSelectInlineApply[233∈0] ➊"]:::plan
    Object11 & PgSelectInlineApply233 --> PgSelect30
    PgSelect35[["PgSelect[35∈0] ➊<br />ᐸprofile_tagsᐳ"]]:::plan
    PgSelectInlineApply237["PgSelectInlineApply[237∈0] ➊"]:::plan
    Object11 & PgSelectInlineApply237 --> PgSelect35
    PgSelect40[["PgSelect[40∈0] ➊<br />ᐸprofilesᐳ"]]:::plan
    PgSelectInlineApply241["PgSelectInlineApply[241∈0] ➊"]:::plan
    Object11 & PgSelectInlineApply241 --> PgSelect40
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    Connection12[["Connection[12∈0] ➊<br />ᐸ8ᐳ<br />Dependents: 4"]]:::plan
    PgSelect8 --> Connection12
    Connection17[["Connection[17∈0] ➊<br />ᐸ15ᐳ"]]:::plan
    PgSelect15 --> Connection17
    Connection22[["Connection[22∈0] ➊<br />ᐸ20ᐳ"]]:::plan
    PgSelect20 --> Connection22
    Connection27[["Connection[27∈0] ➊<br />ᐸ25ᐳ"]]:::plan
    PgSelect25 --> Connection27
    Connection32[["Connection[32∈0] ➊<br />ᐸ30ᐳ"]]:::plan
    PgSelect30 --> Connection32
    Connection37[["Connection[37∈0] ➊<br />ᐸ35ᐳ"]]:::plan
    PgSelect35 --> Connection37
    Connection42[["Connection[42∈0] ➊<br />ᐸ40ᐳ"]]:::plan
    PgSelect40 --> Connection42
    ConnectionItems44[["ConnectionItems[44∈0] ➊<br />Dependents: 3<br />More deps:<br />- Connection[12]"]]:::plan
    ConnectionItems47[["ConnectionItems[47∈0] ➊"]]:::plan
    Connection17 --> ConnectionItems47
    ConnectionItems50[["ConnectionItems[50∈0] ➊"]]:::plan
    Connection22 --> ConnectionItems50
    ConnectionItems53[["ConnectionItems[53∈0] ➊"]]:::plan
    Connection27 --> ConnectionItems53
    ConnectionItems56[["ConnectionItems[56∈0] ➊"]]:::plan
    Connection32 --> ConnectionItems56
    ConnectionItems59[["ConnectionItems[59∈0] ➊"]]:::plan
    Connection37 --> ConnectionItems59
    ConnectionItems62[["ConnectionItems[62∈0] ➊"]]:::plan
    Connection42 --> ConnectionItems62
    PgSelect65[["PgSelect[65∈0] ➊<br />ᐸmeasurements(aggregate)ᐳ"]]:::plan
    Object11 --> PgSelect65
    First66{{"First[66∈0] ➊"}}:::plan
    PgSelectRows67[["PgSelectRows[67∈0] ➊"]]:::plan
    PgSelectRows67 --> First66
    PgSelect65 --> PgSelectRows67
    PgSelectSingle68{{"PgSelectSingle[68∈0] ➊<br />ᐸmeasurementsᐳ"}}:::plan
    First66 --> PgSelectSingle68
    First92[["First[92∈0] ➊<br />More deps:<br />- ConnectionItems[44]"]]:::plan
    Access93{{"Access[93∈0] ➊<br />ᐸ8.cursorDetailsᐳ<br />Dependents: 3"}}:::plan
    PgSelect8 --> Access93
    Last95[["Last[95∈0] ➊<br />More deps:<br />- ConnectionItems[44]"]]:::plan
    Access218{{"Access[218∈0] ➊<br />ᐸ8.m.joinDetailsFor196ᐳ"}}:::plan
    PgSelect8 --> Access218
    Access222{{"Access[222∈0] ➊<br />ᐸ15.m.joinDetailsFor153ᐳ"}}:::plan
    PgSelect15 --> Access222
    Access226{{"Access[226∈0] ➊<br />ᐸ20.m.subqueryDetailsFor135ᐳ"}}:::plan
    PgSelect20 --> Access226
    Access230{{"Access[230∈0] ➊<br />ᐸ25.m.joinDetailsFor160ᐳ"}}:::plan
    PgSelect25 --> Access230
    Access234{{"Access[234∈0] ➊<br />ᐸ30.m.subqueryDetailsFor141ᐳ"}}:::plan
    PgSelect30 --> Access234
    Access238{{"Access[238∈0] ➊<br />ᐸ35.m.joinDetailsFor167ᐳ"}}:::plan
    PgSelect35 --> Access238
    Access242{{"Access[242∈0] ➊<br />ᐸ40.m.subqueryDetailsFor147ᐳ"}}:::plan
    PgSelect40 --> Access242
    PageInfo70{{"PageInfo[70∈1] ➊<br />More deps:<br />- Connection[12]"}}:::plan
    __CloneStream71[["__CloneStream[71∈1] ➊<br />More deps:<br />- ConnectionItems[44]"]]:::plan
    Lambda97[["Lambda[97∈1] ➊<br />More deps:<br />- Connection[12]"]]:::unbatchedplan
    Lambda98[["Lambda[98∈1] ➊<br />More deps:<br />- Connection[12]"]]:::unbatchedplan
    Edge79{{"Edge[79∈15]"}}:::plan
    __Item78[/"__Item[78∈15]<br />ᐸ71ᐳ"\]:::itemplan
    PgCursor100{{"PgCursor[100∈15]<br />More deps:<br />- Access[93]"}}:::plan
    __Item78 & PgCursor100 --> Edge79
    __Item78 --> PgCursor100
    __CloneStream71 ==> __Item78
    __Item80[/"__Item[80∈16]<br />ᐸ47ᐳ"\]:::itemplan
    ConnectionItems47 ==> __Item80
    PgSelectSingle81{{"PgSelectSingle[81∈16]<br />ᐸlocation_tagsᐳ"}}:::plan
    __Item80 --> PgSelectSingle81
    __Item82[/"__Item[82∈17]<br />ᐸ50ᐳ"\]:::itemplan
    ConnectionItems50 ==> __Item82
    PgSelectSingle83{{"PgSelectSingle[83∈17]<br />ᐸlocationsᐳ"}}:::plan
    __Item82 --> PgSelectSingle83
    __Item84[/"__Item[84∈18]<br />ᐸ53ᐳ"\]:::itemplan
    ConnectionItems53 ==> __Item84
    PgSelectSingle85{{"PgSelectSingle[85∈18]<br />ᐸphoto_tagsᐳ"}}:::plan
    __Item84 --> PgSelectSingle85
    __Item86[/"__Item[86∈19]<br />ᐸ56ᐳ"\]:::itemplan
    ConnectionItems56 ==> __Item86
    PgSelectSingle87{{"PgSelectSingle[87∈19]<br />ᐸphotosᐳ"}}:::plan
    __Item86 --> PgSelectSingle87
    __Item88[/"__Item[88∈20]<br />ᐸ59ᐳ"\]:::itemplan
    ConnectionItems59 ==> __Item88
    PgSelectSingle89{{"PgSelectSingle[89∈20]<br />ᐸprofile_tagsᐳ"}}:::plan
    __Item88 --> PgSelectSingle89
    __Item90[/"__Item[90∈21]<br />ᐸ62ᐳ"\]:::itemplan
    ConnectionItems62 ==> __Item90
    PgSelectSingle91{{"PgSelectSingle[91∈21]<br />ᐸprofilesᐳ"}}:::plan
    __Item90 --> PgSelectSingle91
    PgSelectSingle131{{"PgSelectSingle[131∈22]<br />ᐸmeasurementsᐳ"}}:::plan
    __Item78 --> PgSelectSingle131
    List105{{"List[105∈23]<br />ᐸ101,102,103,104ᐳ<br />More deps:<br />- Constantᐸ'location_tags'ᐳ[101]"}}:::plan
    PgClassExpression102{{"PgClassExpression[102∈23]<br />ᐸ__location...tity_kind”ᐳ"}}:::plan
    PgClassExpression103{{"PgClassExpression[103∈23]<br />ᐸ__location...entity_id”ᐳ"}}:::plan
    PgClassExpression104{{"PgClassExpression[104∈23]<br />ᐸ__location_tags__.”tag”ᐳ"}}:::plan
    PgClassExpression102 & PgClassExpression103 & PgClassExpression104 --> List105
    List223{{"List[223∈23]<br />ᐸ222,81ᐳ"}}:::plan
    Access222 & PgSelectSingle81 --> List223
    PgSelectSingle81 --> PgClassExpression102
    PgSelectSingle81 --> PgClassExpression103
    PgSelectSingle81 --> PgClassExpression104
    Lambda106{{"Lambda[106∈23]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List105 --> Lambda106
    First157{{"First[157∈23]"}}:::plan
    PgSelectRows158[["PgSelectRows[158∈23]"]]:::plan
    PgSelectRows158 --> First157
    Lambda224{{"Lambda[224∈23]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda224 --> PgSelectRows158
    PgSelectSingle159{{"PgSelectSingle[159∈23]<br />ᐸlocationsᐳ"}}:::plan
    First157 --> PgSelectSingle159
    List223 --> Lambda224
    List109{{"List[109∈24]<br />ᐸ107,108ᐳ<br />More deps:<br />- Constantᐸ'locations'ᐳ[107]"}}:::plan
    PgClassExpression108{{"PgClassExpression[108∈24]<br />ᐸ__locations__.”id”ᐳ"}}:::plan
    PgClassExpression108 --> List109
    List227{{"List[227∈24]<br />ᐸ226,82ᐳ"}}:::plan
    Access226 & __Item82 --> List227
    PgSelectSingle83 --> PgClassExpression108
    Lambda110{{"Lambda[110∈24]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List109 --> Lambda110
    Connection139[["Connection[139∈24]<br />ᐸ228ᐳ"]]:::plan
    Lambda228{{"Lambda[228∈24]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda228 --> Connection139
    ConnectionItems175[["ConnectionItems[175∈24]"]]:::plan
    Connection139 --> ConnectionItems175
    List227 --> Lambda228
    List115{{"List[115∈25]<br />ᐸ111,112,113,114ᐳ<br />More deps:<br />- Constantᐸ'photo_tags'ᐳ[111]"}}:::plan
    PgClassExpression112{{"PgClassExpression[112∈25]<br />ᐸ__photo_ta...tity_kind”ᐳ"}}:::plan
    PgClassExpression113{{"PgClassExpression[113∈25]<br />ᐸ__photo_ta...entity_id”ᐳ"}}:::plan
    PgClassExpression114{{"PgClassExpression[114∈25]<br />ᐸ__photo_tags__.”tag”ᐳ"}}:::plan
    PgClassExpression112 & PgClassExpression113 & PgClassExpression114 --> List115
    List231{{"List[231∈25]<br />ᐸ230,85ᐳ"}}:::plan
    Access230 & PgSelectSingle85 --> List231
    PgSelectSingle85 --> PgClassExpression112
    PgSelectSingle85 --> PgClassExpression113
    PgSelectSingle85 --> PgClassExpression114
    Lambda116{{"Lambda[116∈25]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List115 --> Lambda116
    First164{{"First[164∈25]"}}:::plan
    PgSelectRows165[["PgSelectRows[165∈25]"]]:::plan
    PgSelectRows165 --> First164
    Lambda232{{"Lambda[232∈25]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda232 --> PgSelectRows165
    PgSelectSingle166{{"PgSelectSingle[166∈25]<br />ᐸphotosᐳ"}}:::plan
    First164 --> PgSelectSingle166
    List231 --> Lambda232
    List119{{"List[119∈26]<br />ᐸ117,118ᐳ<br />More deps:<br />- Constantᐸ'photos'ᐳ[117]"}}:::plan
    PgClassExpression118{{"PgClassExpression[118∈26]<br />ᐸ__photos__.”id”ᐳ"}}:::plan
    PgClassExpression118 --> List119
    List235{{"List[235∈26]<br />ᐸ234,86ᐳ"}}:::plan
    Access234 & __Item86 --> List235
    PgSelectSingle87 --> PgClassExpression118
    Lambda120{{"Lambda[120∈26]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List119 --> Lambda120
    Connection145[["Connection[145∈26]<br />ᐸ236ᐳ"]]:::plan
    Lambda236{{"Lambda[236∈26]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda236 --> Connection145
    ConnectionItems178[["ConnectionItems[178∈26]"]]:::plan
    Connection145 --> ConnectionItems178
    List235 --> Lambda236
    List125{{"List[125∈27]<br />ᐸ121,122,123,124ᐳ<br />More deps:<br />- Constantᐸ'profile_tags'ᐳ[121]"}}:::plan
    PgClassExpression122{{"PgClassExpression[122∈27]<br />ᐸ__profile_...tity_kind”ᐳ"}}:::plan
    PgClassExpression123{{"PgClassExpression[123∈27]<br />ᐸ__profile_...entity_id”ᐳ"}}:::plan
    PgClassExpression124{{"PgClassExpression[124∈27]<br />ᐸ__profile_tags__.”tag”ᐳ"}}:::plan
    PgClassExpression122 & PgClassExpression123 & PgClassExpression124 --> List125
    List239{{"List[239∈27]<br />ᐸ238,89ᐳ"}}:::plan
    Access238 & PgSelectSingle89 --> List239
    PgSelectSingle89 --> PgClassExpression122
    PgSelectSingle89 --> PgClassExpression123
    PgSelectSingle89 --> PgClassExpression124
    Lambda126{{"Lambda[126∈27]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List125 --> Lambda126
    First171{{"First[171∈27]"}}:::plan
    PgSelectRows172[["PgSelectRows[172∈27]"]]:::plan
    PgSelectRows172 --> First171
    Lambda240{{"Lambda[240∈27]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda240 --> PgSelectRows172
    PgSelectSingle173{{"PgSelectSingle[173∈27]<br />ᐸprofilesᐳ"}}:::plan
    First171 --> PgSelectSingle173
    List239 --> Lambda240
    List129{{"List[129∈28]<br />ᐸ127,128ᐳ<br />More deps:<br />- Constantᐸ'profiles'ᐳ[127]"}}:::plan
    PgClassExpression128{{"PgClassExpression[128∈28]<br />ᐸ__profiles__.”id”ᐳ"}}:::plan
    PgClassExpression128 --> List129
    List243{{"List[243∈28]<br />ᐸ242,90ᐳ"}}:::plan
    Access242 & __Item90 --> List243
    PgSelectSingle91 --> PgClassExpression128
    Lambda130{{"Lambda[130∈28]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List129 --> Lambda130
    Connection151[["Connection[151∈28]<br />ᐸ244ᐳ"]]:::plan
    Lambda244{{"Lambda[244∈28]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda244 --> Connection151
    ConnectionItems181[["ConnectionItems[181∈28]"]]:::plan
    Connection151 --> ConnectionItems181
    List243 --> Lambda244
    List219{{"List[219∈29]<br />ᐸ218,131ᐳ"}}:::plan
    Access218 & PgSelectSingle131 --> List219
    PgClassExpression174{{"PgClassExpression[174∈29]<br />ᐸ__measurem...timestamp”ᐳ"}}:::plan
    PgSelectSingle131 --> PgClassExpression174
    PgClassExpression193{{"PgClassExpression[193∈29]<br />ᐸ__measurements__.”key”ᐳ"}}:::plan
    PgClassExpression174 o--o PgClassExpression193
    PgClassExpression194{{"PgClassExpression[194∈29]<br />ᐸ__measurem...__.”value”ᐳ"}}:::plan
    PgClassExpression193 o--o PgClassExpression194
    First200{{"First[200∈29]"}}:::plan
    PgSelectRows201[["PgSelectRows[201∈29]"]]:::plan
    PgSelectRows201 --> First200
    Lambda220{{"Lambda[220∈29]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda220 --> PgSelectRows201
    PgSelectSingle202{{"PgSelectSingle[202∈29]<br />ᐸusersᐳ"}}:::plan
    First200 --> PgSelectSingle202
    List219 --> Lambda220
    List185{{"List[185∈30]<br />ᐸ107,184ᐳ<br />More deps:<br />- Constantᐸ'locations'ᐳ[107]"}}:::plan
    PgClassExpression184{{"PgClassExpression[184∈30]<br />ᐸ__locations__.”id”ᐳ"}}:::plan
    PgClassExpression184 --> List185
    PgSelectSingle159 --> PgClassExpression184
    Lambda186{{"Lambda[186∈30]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List185 --> Lambda186
    List188{{"List[188∈31]<br />ᐸ117,187ᐳ<br />More deps:<br />- Constantᐸ'photos'ᐳ[117]"}}:::plan
    PgClassExpression187{{"PgClassExpression[187∈31]<br />ᐸ__photos__.”id”ᐳ"}}:::plan
    PgClassExpression187 --> List188
    PgSelectSingle166 --> PgClassExpression187
    Lambda189{{"Lambda[189∈31]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List188 --> Lambda189
    List191{{"List[191∈32]<br />ᐸ127,190ᐳ<br />More deps:<br />- Constantᐸ'profiles'ᐳ[127]"}}:::plan
    PgClassExpression190{{"PgClassExpression[190∈32]<br />ᐸ__profiles__.”id”ᐳ"}}:::plan
    PgClassExpression190 --> List191
    PgSelectSingle173 --> PgClassExpression190
    Lambda192{{"Lambda[192∈32]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List191 --> Lambda192
    PgClassExpression212{{"PgClassExpression[212∈36]<br />ᐸ__users__.”id”ᐳ"}}:::plan
    PgSelectSingle202 --> PgClassExpression212
    PgClassExpression213{{"PgClassExpression[213∈36]<br />ᐸ__users__.”name”ᐳ"}}:::plan
    PgClassExpression212 o--o PgClassExpression213
    __Item206[/"__Item[206∈37]<br />ᐸ175ᐳ"\]:::itemplan
    ConnectionItems175 ==> __Item206
    PgSelectSingle207{{"PgSelectSingle[207∈37]<br />ᐸlocation_tagsᐳ"}}:::plan
    __Item206 --> PgSelectSingle207
    __Item208[/"__Item[208∈38]<br />ᐸ178ᐳ"\]:::itemplan
    ConnectionItems178 ==> __Item208
    PgSelectSingle209{{"PgSelectSingle[209∈38]<br />ᐸphoto_tagsᐳ"}}:::plan
    __Item208 --> PgSelectSingle209
    __Item210[/"__Item[210∈39]<br />ᐸ181ᐳ"\]:::itemplan
    ConnectionItems181 ==> __Item210
    PgSelectSingle211{{"PgSelectSingle[211∈39]<br />ᐸprofile_tagsᐳ"}}:::plan
    __Item210 --> PgSelectSingle211
    PgClassExpression214{{"PgClassExpression[214∈40]<br />ᐸ__location_tags__.”tag”ᐳ"}}:::plan
    PgSelectSingle207 --> PgClassExpression214
    PgClassExpression215{{"PgClassExpression[215∈41]<br />ᐸ__photo_tags__.”tag”ᐳ"}}:::plan
    PgSelectSingle209 --> PgClassExpression215
    PgClassExpression216{{"PgClassExpression[216∈42]<br />ᐸ__profile_tags__.”tag”ᐳ"}}:::plan
    PgSelectSingle211 --> PgClassExpression216

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect8,Access9,Access10,Object11,Connection12,PgSelect15,Connection17,PgSelect20,Connection22,PgSelect25,Connection27,PgSelect30,Connection32,PgSelect35,Connection37,PgSelect40,Connection42,ConnectionItems44,ConnectionItems47,ConnectionItems50,ConnectionItems53,ConnectionItems56,ConnectionItems59,ConnectionItems62,PgSelect65,First66,PgSelectRows67,PgSelectSingle68,First92,Access93,Last95,PgSelectInlineApply217,Access218,PgSelectInlineApply221,Access222,PgSelectInlineApply225,Access226,PgSelectInlineApply229,Access230,PgSelectInlineApply233,Access234,PgSelectInlineApply237,Access238,PgSelectInlineApply241,Access242 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PageInfo70,__CloneStream71,Lambda97,Lambda98 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7 bucket7
    classDef bucket15 stroke:#ff00ff
    class Bucket15,__Item78,Edge79,PgCursor100 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16,__Item80,PgSelectSingle81 bucket16
    classDef bucket17 stroke:#696969
    class Bucket17,__Item82,PgSelectSingle83 bucket17
    classDef bucket18 stroke:#00bfff
    class Bucket18,__Item84,PgSelectSingle85 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19,__Item86,PgSelectSingle87 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20,__Item88,PgSelectSingle89 bucket20
    classDef bucket21 stroke:#0000ff
    class Bucket21,__Item90,PgSelectSingle91 bucket21
    classDef bucket22 stroke:#7fff00
    class Bucket22,PgSelectSingle131 bucket22
    classDef bucket23 stroke:#ff1493
    class Bucket23,PgClassExpression102,PgClassExpression103,PgClassExpression104,List105,Lambda106,First157,PgSelectRows158,PgSelectSingle159,List223,Lambda224 bucket23
    classDef bucket24 stroke:#808000
    class Bucket24,PgClassExpression108,List109,Lambda110,Connection139,ConnectionItems175,List227,Lambda228 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25,PgClassExpression112,PgClassExpression113,PgClassExpression114,List115,Lambda116,First164,PgSelectRows165,PgSelectSingle166,List231,Lambda232 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,PgClassExpression118,List119,Lambda120,Connection145,ConnectionItems178,List235,Lambda236 bucket26
    classDef bucket27 stroke:#ffff00
    class Bucket27,PgClassExpression122,PgClassExpression123,PgClassExpression124,List125,Lambda126,First171,PgSelectRows172,PgSelectSingle173,List239,Lambda240 bucket27
    classDef bucket28 stroke:#00ffff
    class Bucket28,PgClassExpression128,List129,Lambda130,Connection151,ConnectionItems181,List243,Lambda244 bucket28
    classDef bucket29 stroke:#4169e1
    class Bucket29,PgClassExpression174,PgClassExpression193,PgClassExpression194,First200,PgSelectRows201,PgSelectSingle202,List219,Lambda220 bucket29
    classDef bucket30 stroke:#3cb371
    class Bucket30,PgClassExpression184,List185,Lambda186 bucket30
    classDef bucket31 stroke:#a52a2a
    class Bucket31,PgClassExpression187,List188,Lambda189 bucket31
    classDef bucket32 stroke:#ff00ff
    class Bucket32,PgClassExpression190,List191,Lambda192 bucket32
    classDef bucket36 stroke:#7f007f
    class Bucket36,PgClassExpression212,PgClassExpression213 bucket36
    classDef bucket37 stroke:#ffa500
    class Bucket37,__Item206,PgSelectSingle207 bucket37
    classDef bucket38 stroke:#0000ff
    class Bucket38,__Item208,PgSelectSingle209 bucket38
    classDef bucket39 stroke:#7fff00
    class Bucket39,__Item210,PgSelectSingle211 bucket39
    classDef bucket40 stroke:#ff1493
    class Bucket40,PgClassExpression214 bucket40
    classDef bucket41 stroke:#808000
    class Bucket41,PgClassExpression215 bucket41
    classDef bucket42 stroke:#dda0dd
    class Bucket42,PgClassExpression216 bucket42

