%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/v4/relation-head-tail"
    Bucket0("Bucket 0 (root)<br /><br />1: 117, 121, 125<br />ᐳ: 6, 9, 10, 129, 130, 11, 50, 56<br />2: 15, 109, 113<br />ᐳ: Access[126]<br />3: PgSelect[8], Connection[17]<br />ᐳ: 110, 114, 118, 122<br />4: Connection[12], ConnectionItems[22]<br />5: ConnectionItems[19]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 19, 129, 110, 114, 118, 122<br /><br />ROOT Connectionᐸ8ᐳ[12]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 17, 22, 126<br /><br />ROOT Connectionᐸ15ᐳ[17]"):::bucket
    Bucket5("Bucket 5 (listItem)<br />Deps: 129, 110, 114, 118, 122<br /><br />ROOT __Item{5}ᐸ19ᐳ[27]"):::bucket
    Bucket6("Bucket 6 (listItem)<br />Deps: 126<br /><br />ROOT __Item{6}ᐸ22ᐳ[29]"):::bucket
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 28, 129, 110, 27, 114, 118, 122<br /><br />ROOT PgSelectSingle{5}ᐸpersonᐳ[28]<br />1: <br />ᐳ: 31, 33, 111, 115, 119, 123, 112, 116, 120, 124<br />2: 42, 55, 61, 66<br />3: 68, 74, 77, 80"):::bucket
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 30, 126, 29<br /><br />ROOT PgSelectSingle{6}ᐸcompound_keyᐳ[30]<br />1: <br />ᐳ: 32, 34, 127, 128<br />2: Connection[48]<br />3: ConnectionItems[71]"):::bucket
    Bucket14("Bucket 14 (listItem)<br /><br />ROOT __Item{14}ᐸ68ᐳ[88]"):::bucket
    Bucket15("Bucket 15 (listItem)<br /><br />ROOT __Item{15}ᐸ71ᐳ[90]"):::bucket
    Bucket16("Bucket 16 (listItem)<br /><br />ROOT __Item{16}ᐸ74ᐳ[92]"):::bucket
    Bucket17("Bucket 17 (listItem)<br /><br />ROOT __Item{17}ᐸ77ᐳ[94]"):::bucket
    Bucket18("Bucket 18 (listItem)<br /><br />ROOT __Item{18}ᐸ80ᐳ[96]"):::bucket
    Bucket19("Bucket 19 (nullableBoundary)<br />Deps: 89<br /><br />ROOT PgSelectSingle{14}ᐸpostᐳ[89]"):::bucket
    Bucket20("Bucket 20 (nullableBoundary)<br />Deps: 91<br /><br />ROOT PgSelectSingle{15}ᐸforeign_keyᐳ[91]"):::bucket
    Bucket21("Bucket 21 (nullableBoundary)<br />Deps: 93<br /><br />ROOT PgSelectSingle{16}ᐸpostᐳ[93]"):::bucket
    Bucket22("Bucket 22 (nullableBoundary)<br />Deps: 95<br /><br />ROOT PgSelectSingle{17}ᐸcompound_keyᐳ[95]"):::bucket
    Bucket23("Bucket 23 (nullableBoundary)<br />Deps: 97<br /><br />ROOT PgSelectSingle{18}ᐸcompound_keyᐳ[97]"):::bucket
    end
    Bucket0 --> Bucket1 & Bucket2
    Bucket1 --> Bucket5
    Bucket2 --> Bucket6
    Bucket5 --> Bucket7
    Bucket6 --> Bucket8
    Bucket7 --> Bucket14 & Bucket16 & Bucket17 & Bucket18
    Bucket8 --> Bucket15
    Bucket14 --> Bucket19
    Bucket15 --> Bucket20
    Bucket16 --> Bucket21
    Bucket17 --> Bucket22
    Bucket18 --> Bucket23

    %% plan dependencies
    PgSelect8[["PgSelect[8∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    PgSelectInlineApply109["PgSelectInlineApply[109∈0] ➊<br />More deps:<br />- Constantᐸ2ᐳ[129]"]:::plan
    PgSelectInlineApply113["PgSelectInlineApply[113∈0] ➊"]:::plan
    PgSelectInlineApply117["PgSelectInlineApply[117∈0] ➊"]:::plan
    PgSelectInlineApply121["PgSelectInlineApply[121∈0] ➊"]:::plan
    Object11 & PgSelectInlineApply109 & PgSelectInlineApply113 & PgSelectInlineApply117 & PgSelectInlineApply121 --> PgSelect8
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    PgSelect15[["PgSelect[15∈0] ➊<br />ᐸcompound_keyᐳ"]]:::plan
    PgSelectInlineApply125["PgSelectInlineApply[125∈0] ➊"]:::plan
    Object11 & PgSelectInlineApply125 --> PgSelect15
    __InputObject50{{"__InputObject[50∈0] ➊<br />More deps:<br />- Constantᐸundefinedᐳ[6]<br />- Constantᐸ'Large bet on myself in round one.'ᐳ[130]"}}:::plan
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    Connection12[["Connection[12∈0] ➊<br />ᐸ8ᐳ"]]:::plan
    PgSelect8 --> Connection12
    Connection17[["Connection[17∈0] ➊<br />ᐸ15ᐳ"]]:::plan
    PgSelect15 --> Connection17
    ConnectionItems19[["ConnectionItems[19∈0] ➊"]]:::plan
    Connection12 --> ConnectionItems19
    ConnectionItems22[["ConnectionItems[22∈0] ➊"]]:::plan
    Connection17 --> ConnectionItems22
    ApplyInput56{{"ApplyInput[56∈0] ➊"}}:::plan
    __InputObject50 --> ApplyInput56
    Access110{{"Access[110∈0] ➊<br />ᐸ8.m.subqueryDetailsFor38ᐳ"}}:::plan
    PgSelect8 --> Access110
    ApplyInput56 --> PgSelectInlineApply113
    Access114{{"Access[114∈0] ➊<br />ᐸ8.m.subqueryDetailsFor53ᐳ"}}:::plan
    PgSelect8 --> Access114
    Access118{{"Access[118∈0] ➊<br />ᐸ8.m.subqueryDetailsFor59ᐳ"}}:::plan
    PgSelect8 --> Access118
    Access122{{"Access[122∈0] ➊<br />ᐸ8.m.subqueryDetailsFor64ᐳ"}}:::plan
    PgSelect8 --> Access122
    Access126{{"Access[126∈0] ➊<br />ᐸ15.m.subqueryDetailsFor44ᐳ"}}:::plan
    PgSelect15 --> Access126
    __Item27[/"__Item[27∈5]<br />ᐸ19ᐳ"\]:::itemplan
    ConnectionItems19 ==> __Item27
    PgSelectSingle28{{"PgSelectSingle[28∈5]<br />ᐸpersonᐳ"}}:::plan
    __Item27 --> PgSelectSingle28
    __Item29[/"__Item[29∈6]<br />ᐸ22ᐳ"\]:::itemplan
    ConnectionItems22 ==> __Item29
    PgSelectSingle30{{"PgSelectSingle[30∈6]<br />ᐸcompound_keyᐳ"}}:::plan
    __Item29 --> PgSelectSingle30
    Connection42[["Connection[42∈7]<br />ᐸ112ᐳ<br />More deps:<br />- Constantᐸ2ᐳ[129]"]]:::plan
    Lambda112{{"Lambda[112∈7]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda112 --> Connection42
    List111{{"List[111∈7]<br />ᐸ110,27ᐳ"}}:::plan
    Access110 & __Item27 --> List111
    List115{{"List[115∈7]<br />ᐸ114,27ᐳ"}}:::plan
    Access114 & __Item27 --> List115
    List119{{"List[119∈7]<br />ᐸ118,27ᐳ"}}:::plan
    Access118 & __Item27 --> List119
    List123{{"List[123∈7]<br />ᐸ122,27ᐳ"}}:::plan
    Access122 & __Item27 --> List123
    PgClassExpression31{{"PgClassExpression[31∈7]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    PgSelectSingle28 --> PgClassExpression31
    PgClassExpression33{{"PgClassExpression[33∈7]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgClassExpression31 o--o PgClassExpression33
    Connection55[["Connection[55∈7]<br />ᐸ116ᐳ"]]:::plan
    Lambda116{{"Lambda[116∈7]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda116 --> Connection55
    Connection61[["Connection[61∈7]<br />ᐸ120ᐳ"]]:::plan
    Lambda120{{"Lambda[120∈7]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda120 --> Connection61
    Connection66[["Connection[66∈7]<br />ᐸ124ᐳ"]]:::plan
    Lambda124{{"Lambda[124∈7]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda124 --> Connection66
    ConnectionItems68[["ConnectionItems[68∈7]"]]:::plan
    Connection42 --> ConnectionItems68
    ConnectionItems74[["ConnectionItems[74∈7]"]]:::plan
    Connection55 --> ConnectionItems74
    ConnectionItems77[["ConnectionItems[77∈7]"]]:::plan
    Connection61 --> ConnectionItems77
    ConnectionItems80[["ConnectionItems[80∈7]"]]:::plan
    Connection66 --> ConnectionItems80
    List111 --> Lambda112
    List115 --> Lambda116
    List119 --> Lambda120
    List123 --> Lambda124
    List127{{"List[127∈8]<br />ᐸ126,29ᐳ"}}:::plan
    Access126 & __Item29 --> List127
    PgClassExpression32{{"PgClassExpression[32∈8]<br />ᐸ__compound...rson_id_1”ᐳ"}}:::plan
    PgSelectSingle30 --> PgClassExpression32
    PgClassExpression34{{"PgClassExpression[34∈8]<br />ᐸ__compound...rson_id_2”ᐳ"}}:::plan
    PgClassExpression32 o--o PgClassExpression34
    Connection48[["Connection[48∈8]<br />ᐸ128ᐳ"]]:::plan
    Lambda128{{"Lambda[128∈8]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda128 --> Connection48
    ConnectionItems71[["ConnectionItems[71∈8]"]]:::plan
    Connection48 --> ConnectionItems71
    List127 --> Lambda128
    __Item88[/"__Item[88∈14]<br />ᐸ68ᐳ"\]:::itemplan
    ConnectionItems68 ==> __Item88
    PgSelectSingle89{{"PgSelectSingle[89∈14]<br />ᐸpostᐳ"}}:::plan
    __Item88 --> PgSelectSingle89
    __Item90[/"__Item[90∈15]<br />ᐸ71ᐳ"\]:::itemplan
    ConnectionItems71 ==> __Item90
    PgSelectSingle91{{"PgSelectSingle[91∈15]<br />ᐸforeign_keyᐳ"}}:::plan
    __Item90 --> PgSelectSingle91
    __Item92[/"__Item[92∈16]<br />ᐸ74ᐳ"\]:::itemplan
    ConnectionItems74 ==> __Item92
    PgSelectSingle93{{"PgSelectSingle[93∈16]<br />ᐸpostᐳ"}}:::plan
    __Item92 --> PgSelectSingle93
    __Item94[/"__Item[94∈17]<br />ᐸ77ᐳ"\]:::itemplan
    ConnectionItems77 ==> __Item94
    PgSelectSingle95{{"PgSelectSingle[95∈17]<br />ᐸcompound_keyᐳ"}}:::plan
    __Item94 --> PgSelectSingle95
    __Item96[/"__Item[96∈18]<br />ᐸ80ᐳ"\]:::itemplan
    ConnectionItems80 ==> __Item96
    PgSelectSingle97{{"PgSelectSingle[97∈18]<br />ᐸcompound_keyᐳ"}}:::plan
    __Item96 --> PgSelectSingle97
    PgClassExpression98{{"PgClassExpression[98∈19]<br />ᐸ__post__.”headline”ᐳ"}}:::plan
    PgSelectSingle89 --> PgClassExpression98
    PgClassExpression103{{"PgClassExpression[103∈19]<br />ᐸ__post__.”author_id”ᐳ"}}:::plan
    PgClassExpression98 o--o PgClassExpression103
    PgClassExpression99{{"PgClassExpression[99∈20]<br />ᐸ__foreign_...person_id”ᐳ"}}:::plan
    PgSelectSingle91 --> PgClassExpression99
    PgClassExpression104{{"PgClassExpression[104∈20]<br />ᐸ__foreign_...und_key_1”ᐳ"}}:::plan
    PgClassExpression99 o--o PgClassExpression104
    PgClassExpression108{{"PgClassExpression[108∈20]<br />ᐸ__foreign_...und_key_2”ᐳ"}}:::plan
    PgClassExpression104 o--o PgClassExpression108
    PgClassExpression100{{"PgClassExpression[100∈21]<br />ᐸ__post__.”headline”ᐳ"}}:::plan
    PgSelectSingle93 --> PgClassExpression100
    PgClassExpression105{{"PgClassExpression[105∈21]<br />ᐸ__post__.”author_id”ᐳ"}}:::plan
    PgClassExpression100 o--o PgClassExpression105
    PgClassExpression101{{"PgClassExpression[101∈22]<br />ᐸ__compound...rson_id_1”ᐳ"}}:::plan
    PgSelectSingle95 --> PgClassExpression101
    PgClassExpression106{{"PgClassExpression[106∈22]<br />ᐸ__compound...rson_id_2”ᐳ"}}:::plan
    PgClassExpression101 o--o PgClassExpression106
    PgClassExpression102{{"PgClassExpression[102∈23]<br />ᐸ__compound...rson_id_1”ᐳ"}}:::plan
    PgSelectSingle97 --> PgClassExpression102
    PgClassExpression107{{"PgClassExpression[107∈23]<br />ᐸ__compound...rson_id_2”ᐳ"}}:::plan
    PgClassExpression102 o--o PgClassExpression107

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect8,Access9,Access10,Object11,Connection12,PgSelect15,Connection17,ConnectionItems19,ConnectionItems22,__InputObject50,ApplyInput56,PgSelectInlineApply109,Access110,PgSelectInlineApply113,Access114,PgSelectInlineApply117,Access118,PgSelectInlineApply121,Access122,PgSelectInlineApply125,Access126 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2 bucket2
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item27,PgSelectSingle28 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,__Item29,PgSelectSingle30 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression31,PgClassExpression33,Connection42,Connection55,Connection61,Connection66,ConnectionItems68,ConnectionItems74,ConnectionItems77,ConnectionItems80,List111,Lambda112,List115,Lambda116,List119,Lambda120,List123,Lambda124 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression32,PgClassExpression34,Connection48,ConnectionItems71,List127,Lambda128 bucket8
    classDef bucket14 stroke:#a52a2a
    class Bucket14,__Item88,PgSelectSingle89 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15,__Item90,PgSelectSingle91 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16,__Item92,PgSelectSingle93 bucket16
    classDef bucket17 stroke:#696969
    class Bucket17,__Item94,PgSelectSingle95 bucket17
    classDef bucket18 stroke:#00bfff
    class Bucket18,__Item96,PgSelectSingle97 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19,PgClassExpression98,PgClassExpression103 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20,PgClassExpression99,PgClassExpression104,PgClassExpression108 bucket20
    classDef bucket21 stroke:#0000ff
    class Bucket21,PgClassExpression100,PgClassExpression105 bucket21
    classDef bucket22 stroke:#7fff00
    class Bucket22,PgClassExpression101,PgClassExpression106 bucket22
    classDef bucket23 stroke:#ff1493
    class Bucket23,PgClassExpression102,PgClassExpression107 bucket23

