%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/v4/smart_comment_relations.houses"
    Bucket0("Bucket 0 (root)<br /><br />1: 282, 290, 298, 314, 326, 334<br />ᐳ: 9, 10, 41, 83, 87, 91, 350, 351, 352, 11, 22, 23, 25<br />2: 16, 27, 286, 294, 302, 318, 330, 338<br />3: 19, 30, 306, 322, 342<br />ᐳ: 18, 20, 29, 31<br />4: 310, 346<br />5: PgSelect[8]<br />ᐳ: 287, 311, 323, 347<br />6: Connection[12]<br />7: ConnectionItems[32]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 32, 41, 287, 311, 323, 347, 83, 87, 91<br /><br />ROOT Connectionᐸ8ᐳ[12]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 20, 41<br /><br />ROOT PgSelectSingleᐸhousesᐳ[20]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 31, 41<br /><br />ROOT PgSelectSingleᐸhousesᐳ[31]"):::bucket
    Bucket5("Bucket 5 (listItem)<br />Deps: 41, 287, 311, 323, 347, 83, 87, 91<br /><br />ROOT __Item{5}ᐸ32ᐳ[51]"):::bucket
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 52, 41, 287, 51, 311, 323, 347, 83, 87, 91<br /><br />ROOT PgSelectSingle{5}ᐸhousesᐳ[52]<br />1: <br />ᐳ: 53, 54, 57, 58, 59, 60, 288, 312, 324, 348, 55, 56, 289, 313, 325, 349<br />2: 66, 71, 76, 81<br />ᐳ: 65, 67, 70, 72, 75, 77, 80, 82"):::bucket
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 67, 83, 289, 65, 87<br /><br />ROOT PgSelectSingle{6}ᐸstreetsᐳ[67]<br />1: <br />ᐳ: 84, 97, 283, 85, 86, 284, 285<br />2: Connection[106]<br />3: ConnectionItems[143]"):::bucket
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 72, 87, 349, 70, 83, 91<br /><br />ROOT PgSelectSingle{6}ᐸbuildingsᐳ[72]<br />1: <br />ᐳ: 88, 98, 108, 117, 331, 343, 89, 90, 332, 333, 344, 345<br />2: PgSelectRows[135], PgSelectRows[141]<br />ᐳ: 134, 136, 140, 142"):::bucket
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 77, 91, 325, 75, 83, 87<br /><br />ROOT PgSelectSingle{6}ᐸpropertiesᐳ[77]<br />1: <br />ᐳ: 92, 99, 109, 319, 93, 94, 320, 321<br />2: PgSelectRows[123]<br />ᐳ: First[122], PgSelectSingle[124]"):::bucket
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 82, 313, 80, 83, 91, 87<br /><br />ROOT PgSelectSingle{6}ᐸstreet_propertyᐳ[82]<br />1: <br />ᐳ: 95, 96, 100, 295, 307, 296, 297, 308, 309<br />2: PgSelectRows[115], PgSelectRows[128]<br />ᐳ: 114, 116, 127, 129"):::bucket
    Bucket11("Bucket 11 (nullableBoundary)<br />Deps: 116, 83, 297, 114, 87<br /><br />ROOT PgSelectSingle{10}ᐸstreetsᐳ[116]<br />1: <br />ᐳ: 146, 161, 291, 147, 148, 292, 293<br />2: Connection[173]<br />3: ConnectionItems[206]"):::bucket
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 124, 83, 321, 122, 87<br /><br />ROOT PgSelectSingle{9}ᐸstreetsᐳ[124]<br />1: <br />ᐳ: 149, 162, 315, 150, 151, 316, 317<br />2: Connection[179]<br />3: ConnectionItems[209]"):::bucket
    Bucket13("Bucket 13 (nullableBoundary)<br />Deps: 129, 91, 309, 127, 83, 87<br /><br />ROOT PgSelectSingle{10}ᐸpropertiesᐳ[129]<br />1: <br />ᐳ: 152, 163, 181, 303, 153, 154, 304, 305<br />2: PgSelectRows[194]<br />ᐳ: First[193], PgSelectSingle[195]"):::bucket
    Bucket14("Bucket 14 (nullableBoundary)<br />Deps: 136, 83, 333, 134, 87<br /><br />ROOT PgSelectSingle{8}ᐸstreetsᐳ[136]<br />1: <br />ᐳ: 155, 164, 327, 156, 157, 328, 329<br />2: Connection[186]<br />3: ConnectionItems[212]"):::bucket
    Bucket15("Bucket 15 (nullableBoundary)<br />Deps: 142, 91, 345, 140, 83, 87<br /><br />ROOT PgSelectSingle{8}ᐸpropertiesᐳ[142]<br />1: <br />ᐳ: 158, 165, 188, 339, 159, 160, 340, 341<br />2: PgSelectRows[201]<br />ᐳ: First[200], PgSelectSingle[202]"):::bucket
    Bucket17("Bucket 17 (nullableBoundary)<br />Deps: 195, 83, 305, 193, 87<br /><br />ROOT PgSelectSingle{13}ᐸstreetsᐳ[195]<br />1: <br />ᐳ: 215, 221, 299, 216, 217, 300, 301<br />2: Connection[229]<br />3: ConnectionItems[250]"):::bucket
    Bucket18("Bucket 18 (nullableBoundary)<br />Deps: 202, 83, 341, 200, 87<br /><br />ROOT PgSelectSingle{15}ᐸstreetsᐳ[202]<br />1: <br />ᐳ: 218, 222, 335, 219, 220, 336, 337<br />2: Connection[235]<br />3: ConnectionItems[253]"):::bucket
    Bucket19("Bucket 19 (listItem)<br />Deps: 87<br /><br />ROOT __Item{19}ᐸ143ᐳ[204]"):::bucket
    Bucket20("Bucket 20 (nullableBoundary)<br />Deps: 205, 87<br /><br />ROOT PgSelectSingle{19}ᐸbuildingsᐳ[205]"):::bucket
    Bucket24("Bucket 24 (listItem)<br />Deps: 87<br /><br />ROOT __Item{24}ᐸ206ᐳ[240]"):::bucket
    Bucket25("Bucket 25 (listItem)<br />Deps: 87<br /><br />ROOT __Item{25}ᐸ209ᐳ[242]"):::bucket
    Bucket26("Bucket 26 (listItem)<br />Deps: 87<br /><br />ROOT __Item{26}ᐸ212ᐳ[244]"):::bucket
    Bucket27("Bucket 27 (nullableBoundary)<br />Deps: 241, 87<br /><br />ROOT PgSelectSingle{24}ᐸbuildingsᐳ[241]"):::bucket
    Bucket28("Bucket 28 (nullableBoundary)<br />Deps: 243, 87<br /><br />ROOT PgSelectSingle{25}ᐸbuildingsᐳ[243]"):::bucket
    Bucket29("Bucket 29 (nullableBoundary)<br />Deps: 245, 87<br /><br />ROOT PgSelectSingle{26}ᐸbuildingsᐳ[245]"):::bucket
    Bucket32("Bucket 32 (listItem)<br />Deps: 87<br /><br />ROOT __Item{32}ᐸ250ᐳ[258]"):::bucket
    Bucket33("Bucket 33 (listItem)<br />Deps: 87<br /><br />ROOT __Item{33}ᐸ253ᐳ[260]"):::bucket
    Bucket34("Bucket 34 (nullableBoundary)<br />Deps: 259, 87<br /><br />ROOT PgSelectSingle{32}ᐸbuildingsᐳ[259]"):::bucket
    Bucket35("Bucket 35 (nullableBoundary)<br />Deps: 261, 87<br /><br />ROOT PgSelectSingle{33}ᐸbuildingsᐳ[261]"):::bucket
    end
    Bucket0 --> Bucket1 & Bucket2 & Bucket3
    Bucket1 --> Bucket5
    Bucket5 --> Bucket6
    Bucket6 --> Bucket7 & Bucket8 & Bucket9 & Bucket10
    Bucket7 --> Bucket19
    Bucket8 --> Bucket14 & Bucket15
    Bucket9 --> Bucket12
    Bucket10 --> Bucket11 & Bucket13
    Bucket11 --> Bucket24
    Bucket12 --> Bucket25
    Bucket13 --> Bucket17
    Bucket14 --> Bucket26
    Bucket15 --> Bucket18
    Bucket17 --> Bucket32
    Bucket18 --> Bucket33
    Bucket19 --> Bucket20
    Bucket24 --> Bucket27
    Bucket25 --> Bucket28
    Bucket26 --> Bucket29
    Bucket32 --> Bucket34
    Bucket33 --> Bucket35

    %% plan dependencies
    PgSelect8[["PgSelect[8∈0] ➊<br />ᐸhousesᐳ"]]:::plan
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    PgSelectInlineApply286["PgSelectInlineApply[286∈0] ➊"]:::plan
    PgSelectInlineApply310["PgSelectInlineApply[310∈0] ➊"]:::plan
    PgSelectInlineApply322["PgSelectInlineApply[322∈0] ➊"]:::plan
    PgSelectInlineApply346["PgSelectInlineApply[346∈0] ➊"]:::plan
    Object11 & PgSelectInlineApply286 & PgSelectInlineApply310 & PgSelectInlineApply322 & PgSelectInlineApply346 --> PgSelect8
    PgSelect16[["PgSelect[16∈0] ➊<br />ᐸhousesᐳ<br />More deps:<br />- Constantᐸ2ᐳ[350]<br />- Constantᐸ3ᐳ[351]"]]:::plan
    Object11 --> PgSelect16
    PgSelect27[["PgSelect[27∈0] ➊<br />ᐸhousesᐳ"]]:::plan
    Access23{{"Access[23∈0] ➊<br />ᐸ22.1ᐳ"}}:::plan
    Access25{{"Access[25∈0] ➊<br />ᐸ22.2ᐳ"}}:::plan
    Access23 -->|rejectNull| PgSelect27
    Access25 -->|rejectNull| PgSelect27
    Object11 --> PgSelect27
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    PgSelectInlineApply294["PgSelectInlineApply[294∈0] ➊"]:::plan
    PgSelectInlineApply306["PgSelectInlineApply[306∈0] ➊"]:::plan
    PgSelectInlineApply294 & PgSelectInlineApply306 --> PgSelectInlineApply310
    PgSelectInlineApply330["PgSelectInlineApply[330∈0] ➊"]:::plan
    PgSelectInlineApply342["PgSelectInlineApply[342∈0] ➊"]:::plan
    PgSelectInlineApply330 & PgSelectInlineApply342 --> PgSelectInlineApply346
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    Connection12[["Connection[12∈0] ➊<br />ᐸ8ᐳ"]]:::plan
    PgSelect8 --> Connection12
    First18{{"First[18∈0] ➊"}}:::plan
    PgSelectRows19[["PgSelectRows[19∈0] ➊"]]:::plan
    PgSelectRows19 --> First18
    PgSelect16 --> PgSelectRows19
    PgSelectSingle20{{"PgSelectSingle[20∈0] ➊<br />ᐸhousesᐳ"}}:::plan
    First18 --> PgSelectSingle20
    Lambda22{{"Lambda[22∈0] ➊<br />ᐸspecifier_House_base64JSONᐳ<br />More deps:<br />- Constantᐸ'WyJob3VzZXMiLDIsM10='ᐳ[352]"}}:::plan
    Lambda22 --> Access23
    Lambda22 --> Access25
    First29{{"First[29∈0] ➊"}}:::plan
    PgSelectRows30[["PgSelectRows[30∈0] ➊"]]:::plan
    PgSelectRows30 --> First29
    PgSelect27 --> PgSelectRows30
    PgSelectSingle31{{"PgSelectSingle[31∈0] ➊<br />ᐸhousesᐳ"}}:::plan
    First29 --> PgSelectSingle31
    ConnectionItems32[["ConnectionItems[32∈0] ➊"]]:::plan
    Connection12 --> ConnectionItems32
    PgSelectInlineApply282["PgSelectInlineApply[282∈0] ➊"]:::plan
    PgSelectInlineApply282 --> PgSelectInlineApply286
    Access287{{"Access[287∈0] ➊<br />ᐸ8.m.subqueryDetailsFor61ᐳ"}}:::plan
    PgSelect8 --> Access287
    PgSelectInlineApply290["PgSelectInlineApply[290∈0] ➊"]:::plan
    PgSelectInlineApply290 --> PgSelectInlineApply294
    PgSelectInlineApply302["PgSelectInlineApply[302∈0] ➊"]:::plan
    PgSelectInlineApply298["PgSelectInlineApply[298∈0] ➊"]:::plan
    PgSelectInlineApply298 --> PgSelectInlineApply302
    PgSelectInlineApply302 --> PgSelectInlineApply306
    Access311{{"Access[311∈0] ➊<br />ᐸ8.m.subqueryDetailsFor78ᐳ"}}:::plan
    PgSelect8 --> Access311
    PgSelectInlineApply318["PgSelectInlineApply[318∈0] ➊"]:::plan
    PgSelectInlineApply314["PgSelectInlineApply[314∈0] ➊"]:::plan
    PgSelectInlineApply314 --> PgSelectInlineApply318
    PgSelectInlineApply318 --> PgSelectInlineApply322
    Access323{{"Access[323∈0] ➊<br />ᐸ8.m.subqueryDetailsFor73ᐳ"}}:::plan
    PgSelect8 --> Access323
    PgSelectInlineApply326["PgSelectInlineApply[326∈0] ➊"]:::plan
    PgSelectInlineApply326 --> PgSelectInlineApply330
    PgSelectInlineApply338["PgSelectInlineApply[338∈0] ➊"]:::plan
    PgSelectInlineApply334["PgSelectInlineApply[334∈0] ➊"]:::plan
    PgSelectInlineApply334 --> PgSelectInlineApply338
    PgSelectInlineApply338 --> PgSelectInlineApply342
    Access347{{"Access[347∈0] ➊<br />ᐸ8.m.subqueryDetailsFor68ᐳ"}}:::plan
    PgSelect8 --> Access347
    List44{{"List[44∈2] ➊<br />ᐸ41,42,43ᐳ<br />More deps:<br />- Constantᐸ'houses'ᐳ[41]"}}:::plan
    PgClassExpression42{{"PgClassExpression[42∈2] ➊<br />ᐸ__houses__.”street_id”ᐳ"}}:::plan
    PgClassExpression43{{"PgClassExpression[43∈2] ➊<br />ᐸ__houses__...operty_id”ᐳ"}}:::plan
    PgClassExpression42 & PgClassExpression43 --> List44
    PgClassExpression35{{"PgClassExpression[35∈2] ➊<br />ᐸ__houses__...ding_name”ᐳ"}}:::plan
    PgSelectSingle20 --> PgClassExpression35
    PgClassExpression37{{"PgClassExpression[37∈2] ➊<br />ᐸ__houses__...or_number”ᐳ"}}:::plan
    PgClassExpression35 o--o PgClassExpression37
    PgClassExpression39{{"PgClassExpression[39∈2] ➊<br />ᐸ__houses__...reet_name”ᐳ"}}:::plan
    PgClassExpression37 o--o PgClassExpression39
    PgSelectSingle20 --> PgClassExpression42
    PgSelectSingle20 --> PgClassExpression43
    Lambda45{{"Lambda[45∈2] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List44 --> Lambda45
    List48{{"List[48∈3] ➊<br />ᐸ41,46,47ᐳ<br />More deps:<br />- Constantᐸ'houses'ᐳ[41]"}}:::plan
    PgClassExpression46{{"PgClassExpression[46∈3] ➊<br />ᐸ__houses__.”street_id”ᐳ"}}:::plan
    PgClassExpression47{{"PgClassExpression[47∈3] ➊<br />ᐸ__houses__...operty_id”ᐳ"}}:::plan
    PgClassExpression46 & PgClassExpression47 --> List48
    PgClassExpression36{{"PgClassExpression[36∈3] ➊<br />ᐸ__houses__...ding_name”ᐳ"}}:::plan
    PgSelectSingle31 --> PgClassExpression36
    PgClassExpression38{{"PgClassExpression[38∈3] ➊<br />ᐸ__houses__...or_number”ᐳ"}}:::plan
    PgClassExpression36 o--o PgClassExpression38
    PgClassExpression40{{"PgClassExpression[40∈3] ➊<br />ᐸ__houses__...reet_name”ᐳ"}}:::plan
    PgClassExpression38 o--o PgClassExpression40
    PgSelectSingle31 --> PgClassExpression46
    PgSelectSingle31 --> PgClassExpression47
    Lambda49{{"Lambda[49∈3] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List48 --> Lambda49
    __Item51[/"__Item[51∈5]<br />ᐸ32ᐳ"\]:::itemplan
    ConnectionItems32 ==> __Item51
    PgSelectSingle52{{"PgSelectSingle[52∈5]<br />ᐸhousesᐳ"}}:::plan
    __Item51 --> PgSelectSingle52
    List55{{"List[55∈6]<br />ᐸ41,53,54ᐳ<br />More deps:<br />- Constantᐸ'houses'ᐳ[41]"}}:::plan
    PgClassExpression53{{"PgClassExpression[53∈6]<br />ᐸ__houses__.”street_id”ᐳ"}}:::plan
    PgClassExpression54{{"PgClassExpression[54∈6]<br />ᐸ__houses__...operty_id”ᐳ"}}:::plan
    PgClassExpression53 & PgClassExpression54 --> List55
    List288{{"List[288∈6]<br />ᐸ287,51ᐳ"}}:::plan
    Access287 & __Item51 --> List288
    List312{{"List[312∈6]<br />ᐸ311,51ᐳ"}}:::plan
    Access311 & __Item51 --> List312
    List324{{"List[324∈6]<br />ᐸ323,51ᐳ"}}:::plan
    Access323 & __Item51 --> List324
    List348{{"List[348∈6]<br />ᐸ347,51ᐳ"}}:::plan
    Access347 & __Item51 --> List348
    PgSelectSingle52 --> PgClassExpression53
    PgSelectSingle52 --> PgClassExpression54
    Lambda56{{"Lambda[56∈6]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List55 --> Lambda56
    PgClassExpression57{{"PgClassExpression[57∈6]<br />ᐸ__houses__...ding_name”ᐳ"}}:::plan
    PgSelectSingle52 --> PgClassExpression57
    PgClassExpression58{{"PgClassExpression[58∈6]<br />ᐸ__houses__...or_number”ᐳ"}}:::plan
    PgClassExpression57 o--o PgClassExpression58
    PgClassExpression59{{"PgClassExpression[59∈6]<br />ᐸ__houses__...reet_name”ᐳ"}}:::plan
    PgClassExpression58 o--o PgClassExpression59
    PgClassExpression60{{"PgClassExpression[60∈6]<br />ᐸ__houses__...ilding_id”ᐳ"}}:::plan
    PgClassExpression59 o--o PgClassExpression60
    First65{{"First[65∈6]"}}:::plan
    PgSelectRows66[["PgSelectRows[66∈6]"]]:::plan
    PgSelectRows66 --> First65
    Lambda289{{"Lambda[289∈6]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda289 --> PgSelectRows66
    PgSelectSingle67{{"PgSelectSingle[67∈6]<br />ᐸstreetsᐳ"}}:::plan
    First65 --> PgSelectSingle67
    First70{{"First[70∈6]"}}:::plan
    PgSelectRows71[["PgSelectRows[71∈6]"]]:::plan
    PgSelectRows71 --> First70
    Lambda349{{"Lambda[349∈6]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda349 --> PgSelectRows71
    PgSelectSingle72{{"PgSelectSingle[72∈6]<br />ᐸbuildingsᐳ"}}:::plan
    First70 --> PgSelectSingle72
    First75{{"First[75∈6]"}}:::plan
    PgSelectRows76[["PgSelectRows[76∈6]"]]:::plan
    PgSelectRows76 --> First75
    Lambda325{{"Lambda[325∈6]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda325 --> PgSelectRows76
    PgSelectSingle77{{"PgSelectSingle[77∈6]<br />ᐸpropertiesᐳ"}}:::plan
    First75 --> PgSelectSingle77
    First80{{"First[80∈6]"}}:::plan
    PgSelectRows81[["PgSelectRows[81∈6]"]]:::plan
    PgSelectRows81 --> First80
    Lambda313{{"Lambda[313∈6]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda313 --> PgSelectRows81
    PgSelectSingle82{{"PgSelectSingle[82∈6]<br />ᐸstreet_propertyᐳ"}}:::plan
    First80 --> PgSelectSingle82
    List288 --> Lambda289
    List312 --> Lambda313
    List324 --> Lambda325
    List348 --> Lambda349
    List85{{"List[85∈7]<br />ᐸ83,84ᐳ<br />More deps:<br />- Constantᐸ'streets'ᐳ[83]"}}:::plan
    PgClassExpression84{{"PgClassExpression[84∈7]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgClassExpression84 --> List85
    List284{{"List[284∈7]<br />ᐸ283,65ᐳ"}}:::plan
    Access283{{"Access[283∈7]<br />ᐸ289.m.subqueryDetailsFor102ᐳ"}}:::plan
    Access283 & First65 --> List284
    PgSelectSingle67 --> PgClassExpression84
    Lambda86{{"Lambda[86∈7]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List85 --> Lambda86
    PgClassExpression97{{"PgClassExpression[97∈7]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgSelectSingle67 --> PgClassExpression97
    Connection106[["Connection[106∈7]<br />ᐸ285ᐳ"]]:::plan
    Lambda285{{"Lambda[285∈7]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda285 --> Connection106
    ConnectionItems143[["ConnectionItems[143∈7]"]]:::plan
    Connection106 --> ConnectionItems143
    Lambda289 --> Access283
    List284 --> Lambda285
    List89{{"List[89∈8]<br />ᐸ87,88ᐳ<br />More deps:<br />- Constantᐸ'buildings'ᐳ[87]"}}:::plan
    PgClassExpression88{{"PgClassExpression[88∈8]<br />ᐸ__buildings__.”id”ᐳ"}}:::plan
    PgClassExpression88 --> List89
    List332{{"List[332∈8]<br />ᐸ331,70ᐳ"}}:::plan
    Access331{{"Access[331∈8]<br />ᐸ349.m.subqueryDetailsFor130ᐳ"}}:::plan
    Access331 & First70 --> List332
    List344{{"List[344∈8]<br />ᐸ343,70ᐳ"}}:::plan
    Access343{{"Access[343∈8]<br />ᐸ349.m.subqueryDetailsFor138ᐳ"}}:::plan
    Access343 & First70 --> List344
    PgSelectSingle72 --> PgClassExpression88
    Lambda90{{"Lambda[90∈8]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List89 --> Lambda90
    PgClassExpression98{{"PgClassExpression[98∈8]<br />ᐸ__buildings__.”name”ᐳ"}}:::plan
    PgSelectSingle72 --> PgClassExpression98
    PgClassExpression108{{"PgClassExpression[108∈8]<br />ᐸ__buildings__.”floors”ᐳ"}}:::plan
    PgClassExpression98 o--o PgClassExpression108
    PgClassExpression117{{"PgClassExpression[117∈8]<br />ᐸ__building...s_primary”ᐳ"}}:::plan
    PgClassExpression108 o--o PgClassExpression117
    First134{{"First[134∈8]"}}:::plan
    PgSelectRows135[["PgSelectRows[135∈8]"]]:::plan
    PgSelectRows135 --> First134
    Lambda333{{"Lambda[333∈8]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda333 --> PgSelectRows135
    PgSelectSingle136{{"PgSelectSingle[136∈8]<br />ᐸstreetsᐳ"}}:::plan
    First134 --> PgSelectSingle136
    First140{{"First[140∈8]"}}:::plan
    PgSelectRows141[["PgSelectRows[141∈8]"]]:::plan
    PgSelectRows141 --> First140
    Lambda345{{"Lambda[345∈8]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda345 --> PgSelectRows141
    PgSelectSingle142{{"PgSelectSingle[142∈8]<br />ᐸpropertiesᐳ"}}:::plan
    First140 --> PgSelectSingle142
    Lambda349 --> Access331
    List332 --> Lambda333
    Lambda349 --> Access343
    List344 --> Lambda345
    List93{{"List[93∈9]<br />ᐸ91,92ᐳ<br />More deps:<br />- Constantᐸ'properties'ᐳ[91]"}}:::plan
    PgClassExpression92{{"PgClassExpression[92∈9]<br />ᐸ__properties__.”id”ᐳ"}}:::plan
    PgClassExpression92 --> List93
    List320{{"List[320∈9]<br />ᐸ319,75ᐳ"}}:::plan
    Access319{{"Access[319∈9]<br />ᐸ325.m.subqueryDetailsFor118ᐳ"}}:::plan
    Access319 & First75 --> List320
    PgSelectSingle77 --> PgClassExpression92
    Lambda94{{"Lambda[94∈9]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List93 --> Lambda94
    PgClassExpression99{{"PgClassExpression[99∈9]<br />ᐸ__properti...street_id”ᐳ"}}:::plan
    PgSelectSingle77 --> PgClassExpression99
    PgClassExpression109{{"PgClassExpression[109∈9]<br />ᐸ__properti...or_number”ᐳ"}}:::plan
    PgClassExpression99 o--o PgClassExpression109
    First122{{"First[122∈9]"}}:::plan
    PgSelectRows123[["PgSelectRows[123∈9]"]]:::plan
    PgSelectRows123 --> First122
    Lambda321{{"Lambda[321∈9]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda321 --> PgSelectRows123
    PgSelectSingle124{{"PgSelectSingle[124∈9]<br />ᐸstreetsᐳ"}}:::plan
    First122 --> PgSelectSingle124
    Lambda325 --> Access319
    List320 --> Lambda321
    List296{{"List[296∈10]<br />ᐸ295,80ᐳ"}}:::plan
    Access295{{"Access[295∈10]<br />ᐸ313.m.subqueryDetailsFor110ᐳ"}}:::plan
    Access295 & First80 --> List296
    List308{{"List[308∈10]<br />ᐸ307,80ᐳ"}}:::plan
    Access307{{"Access[307∈10]<br />ᐸ313.m.subqueryDetailsFor125ᐳ"}}:::plan
    Access307 & First80 --> List308
    PgClassExpression95{{"PgClassExpression[95∈10]<br />ᐸ__street_p..._.”str_id”ᐳ"}}:::plan
    PgSelectSingle82 --> PgClassExpression95
    PgClassExpression96{{"PgClassExpression[96∈10]<br />ᐸ__street_p....”prop_id”ᐳ"}}:::plan
    PgClassExpression95 o--o PgClassExpression96
    PgClassExpression100{{"PgClassExpression[100∈10]<br />ᐸ__street_p...ent_owner”ᐳ"}}:::plan
    PgClassExpression96 o--o PgClassExpression100
    First114{{"First[114∈10]"}}:::plan
    PgSelectRows115[["PgSelectRows[115∈10]"]]:::plan
    PgSelectRows115 --> First114
    Lambda297{{"Lambda[297∈10]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda297 --> PgSelectRows115
    PgSelectSingle116{{"PgSelectSingle[116∈10]<br />ᐸstreetsᐳ"}}:::plan
    First114 --> PgSelectSingle116
    First127{{"First[127∈10]"}}:::plan
    PgSelectRows128[["PgSelectRows[128∈10]"]]:::plan
    PgSelectRows128 --> First127
    Lambda309{{"Lambda[309∈10]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda309 --> PgSelectRows128
    PgSelectSingle129{{"PgSelectSingle[129∈10]<br />ᐸpropertiesᐳ"}}:::plan
    First127 --> PgSelectSingle129
    Lambda313 --> Access295
    List296 --> Lambda297
    Lambda313 --> Access307
    List308 --> Lambda309
    List147{{"List[147∈11]<br />ᐸ83,146ᐳ<br />More deps:<br />- Constantᐸ'streets'ᐳ[83]"}}:::plan
    PgClassExpression146{{"PgClassExpression[146∈11]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgClassExpression146 --> List147
    List292{{"List[292∈11]<br />ᐸ291,114ᐳ"}}:::plan
    Access291{{"Access[291∈11]<br />ᐸ297.m.subqueryDetailsFor169ᐳ"}}:::plan
    Access291 & First114 --> List292
    PgSelectSingle116 --> PgClassExpression146
    Lambda148{{"Lambda[148∈11]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List147 --> Lambda148
    PgClassExpression161{{"PgClassExpression[161∈11]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgSelectSingle116 --> PgClassExpression161
    Connection173[["Connection[173∈11]<br />ᐸ293ᐳ"]]:::plan
    Lambda293{{"Lambda[293∈11]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda293 --> Connection173
    ConnectionItems206[["ConnectionItems[206∈11]"]]:::plan
    Connection173 --> ConnectionItems206
    Lambda297 --> Access291
    List292 --> Lambda293
    List150{{"List[150∈12]<br />ᐸ83,149ᐳ<br />More deps:<br />- Constantᐸ'streets'ᐳ[83]"}}:::plan
    PgClassExpression149{{"PgClassExpression[149∈12]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgClassExpression149 --> List150
    List316{{"List[316∈12]<br />ᐸ315,122ᐳ"}}:::plan
    Access315{{"Access[315∈12]<br />ᐸ321.m.subqueryDetailsFor175ᐳ"}}:::plan
    Access315 & First122 --> List316
    PgSelectSingle124 --> PgClassExpression149
    Lambda151{{"Lambda[151∈12]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List150 --> Lambda151
    PgClassExpression162{{"PgClassExpression[162∈12]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgSelectSingle124 --> PgClassExpression162
    Connection179[["Connection[179∈12]<br />ᐸ317ᐳ"]]:::plan
    Lambda317{{"Lambda[317∈12]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda317 --> Connection179
    ConnectionItems209[["ConnectionItems[209∈12]"]]:::plan
    Connection179 --> ConnectionItems209
    Lambda321 --> Access315
    List316 --> Lambda317
    List153{{"List[153∈13]<br />ᐸ91,152ᐳ<br />More deps:<br />- Constantᐸ'properties'ᐳ[91]"}}:::plan
    PgClassExpression152{{"PgClassExpression[152∈13]<br />ᐸ__properties__.”id”ᐳ"}}:::plan
    PgClassExpression152 --> List153
    List304{{"List[304∈13]<br />ᐸ303,127ᐳ"}}:::plan
    Access303{{"Access[303∈13]<br />ᐸ309.m.subqueryDetailsFor189ᐳ"}}:::plan
    Access303 & First127 --> List304
    PgSelectSingle129 --> PgClassExpression152
    Lambda154{{"Lambda[154∈13]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List153 --> Lambda154
    PgClassExpression163{{"PgClassExpression[163∈13]<br />ᐸ__properti...street_id”ᐳ"}}:::plan
    PgSelectSingle129 --> PgClassExpression163
    PgClassExpression181{{"PgClassExpression[181∈13]<br />ᐸ__properti...or_number”ᐳ"}}:::plan
    PgClassExpression163 o--o PgClassExpression181
    First193{{"First[193∈13]"}}:::plan
    PgSelectRows194[["PgSelectRows[194∈13]"]]:::plan
    PgSelectRows194 --> First193
    Lambda305{{"Lambda[305∈13]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda305 --> PgSelectRows194
    PgSelectSingle195{{"PgSelectSingle[195∈13]<br />ᐸstreetsᐳ"}}:::plan
    First193 --> PgSelectSingle195
    Lambda309 --> Access303
    List304 --> Lambda305
    List156{{"List[156∈14]<br />ᐸ83,155ᐳ<br />More deps:<br />- Constantᐸ'streets'ᐳ[83]"}}:::plan
    PgClassExpression155{{"PgClassExpression[155∈14]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgClassExpression155 --> List156
    List328{{"List[328∈14]<br />ᐸ327,134ᐳ"}}:::plan
    Access327{{"Access[327∈14]<br />ᐸ333.m.subqueryDetailsFor182ᐳ"}}:::plan
    Access327 & First134 --> List328
    PgSelectSingle136 --> PgClassExpression155
    Lambda157{{"Lambda[157∈14]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List156 --> Lambda157
    PgClassExpression164{{"PgClassExpression[164∈14]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgSelectSingle136 --> PgClassExpression164
    Connection186[["Connection[186∈14]<br />ᐸ329ᐳ"]]:::plan
    Lambda329{{"Lambda[329∈14]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda329 --> Connection186
    ConnectionItems212[["ConnectionItems[212∈14]"]]:::plan
    Connection186 --> ConnectionItems212
    Lambda333 --> Access327
    List328 --> Lambda329
    List159{{"List[159∈15]<br />ᐸ91,158ᐳ<br />More deps:<br />- Constantᐸ'properties'ᐳ[91]"}}:::plan
    PgClassExpression158{{"PgClassExpression[158∈15]<br />ᐸ__properties__.”id”ᐳ"}}:::plan
    PgClassExpression158 --> List159
    List340{{"List[340∈15]<br />ᐸ339,140ᐳ"}}:::plan
    Access339{{"Access[339∈15]<br />ᐸ345.m.subqueryDetailsFor196ᐳ"}}:::plan
    Access339 & First140 --> List340
    PgSelectSingle142 --> PgClassExpression158
    Lambda160{{"Lambda[160∈15]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List159 --> Lambda160
    PgClassExpression165{{"PgClassExpression[165∈15]<br />ᐸ__properti...street_id”ᐳ"}}:::plan
    PgSelectSingle142 --> PgClassExpression165
    PgClassExpression188{{"PgClassExpression[188∈15]<br />ᐸ__properti...or_number”ᐳ"}}:::plan
    PgClassExpression165 o--o PgClassExpression188
    First200{{"First[200∈15]"}}:::plan
    PgSelectRows201[["PgSelectRows[201∈15]"]]:::plan
    PgSelectRows201 --> First200
    Lambda341{{"Lambda[341∈15]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda341 --> PgSelectRows201
    PgSelectSingle202{{"PgSelectSingle[202∈15]<br />ᐸstreetsᐳ"}}:::plan
    First200 --> PgSelectSingle202
    Lambda345 --> Access339
    List340 --> Lambda341
    List216{{"List[216∈17]<br />ᐸ83,215ᐳ<br />More deps:<br />- Constantᐸ'streets'ᐳ[83]"}}:::plan
    PgClassExpression215{{"PgClassExpression[215∈17]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgClassExpression215 --> List216
    List300{{"List[300∈17]<br />ᐸ299,193ᐳ"}}:::plan
    Access299{{"Access[299∈17]<br />ᐸ305.m.subqueryDetailsFor225ᐳ"}}:::plan
    Access299 & First193 --> List300
    PgSelectSingle195 --> PgClassExpression215
    Lambda217{{"Lambda[217∈17]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List216 --> Lambda217
    PgClassExpression221{{"PgClassExpression[221∈17]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgSelectSingle195 --> PgClassExpression221
    Connection229[["Connection[229∈17]<br />ᐸ301ᐳ"]]:::plan
    Lambda301{{"Lambda[301∈17]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda301 --> Connection229
    ConnectionItems250[["ConnectionItems[250∈17]"]]:::plan
    Connection229 --> ConnectionItems250
    Lambda305 --> Access299
    List300 --> Lambda301
    List219{{"List[219∈18]<br />ᐸ83,218ᐳ<br />More deps:<br />- Constantᐸ'streets'ᐳ[83]"}}:::plan
    PgClassExpression218{{"PgClassExpression[218∈18]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgClassExpression218 --> List219
    List336{{"List[336∈18]<br />ᐸ335,200ᐳ"}}:::plan
    Access335{{"Access[335∈18]<br />ᐸ341.m.subqueryDetailsFor231ᐳ"}}:::plan
    Access335 & First200 --> List336
    PgSelectSingle202 --> PgClassExpression218
    Lambda220{{"Lambda[220∈18]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List219 --> Lambda220
    PgClassExpression222{{"PgClassExpression[222∈18]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgSelectSingle202 --> PgClassExpression222
    Connection235[["Connection[235∈18]<br />ᐸ337ᐳ"]]:::plan
    Lambda337{{"Lambda[337∈18]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda337 --> Connection235
    ConnectionItems253[["ConnectionItems[253∈18]"]]:::plan
    Connection235 --> ConnectionItems253
    Lambda341 --> Access335
    List336 --> Lambda337
    __Item204[/"__Item[204∈19]<br />ᐸ143ᐳ"\]:::itemplan
    ConnectionItems143 ==> __Item204
    PgSelectSingle205{{"PgSelectSingle[205∈19]<br />ᐸbuildingsᐳ"}}:::plan
    __Item204 --> PgSelectSingle205
    List247{{"List[247∈20]<br />ᐸ87,246ᐳ<br />More deps:<br />- Constantᐸ'buildings'ᐳ[87]"}}:::plan
    PgClassExpression246{{"PgClassExpression[246∈20]<br />ᐸ__buildings__.”id”ᐳ"}}:::plan
    PgClassExpression246 --> List247
    PgSelectSingle205 --> PgClassExpression246
    Lambda248{{"Lambda[248∈20]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List247 --> Lambda248
    PgClassExpression249{{"PgClassExpression[249∈20]<br />ᐸ__buildings__.”name”ᐳ"}}:::plan
    PgSelectSingle205 --> PgClassExpression249
    __Item240[/"__Item[240∈24]<br />ᐸ206ᐳ"\]:::itemplan
    ConnectionItems206 ==> __Item240
    PgSelectSingle241{{"PgSelectSingle[241∈24]<br />ᐸbuildingsᐳ"}}:::plan
    __Item240 --> PgSelectSingle241
    __Item242[/"__Item[242∈25]<br />ᐸ209ᐳ"\]:::itemplan
    ConnectionItems209 ==> __Item242
    PgSelectSingle243{{"PgSelectSingle[243∈25]<br />ᐸbuildingsᐳ"}}:::plan
    __Item242 --> PgSelectSingle243
    __Item244[/"__Item[244∈26]<br />ᐸ212ᐳ"\]:::itemplan
    ConnectionItems212 ==> __Item244
    PgSelectSingle245{{"PgSelectSingle[245∈26]<br />ᐸbuildingsᐳ"}}:::plan
    __Item244 --> PgSelectSingle245
    List263{{"List[263∈27]<br />ᐸ87,262ᐳ<br />More deps:<br />- Constantᐸ'buildings'ᐳ[87]"}}:::plan
    PgClassExpression262{{"PgClassExpression[262∈27]<br />ᐸ__buildings__.”id”ᐳ"}}:::plan
    PgClassExpression262 --> List263
    PgSelectSingle241 --> PgClassExpression262
    Lambda264{{"Lambda[264∈27]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List263 --> Lambda264
    PgClassExpression271{{"PgClassExpression[271∈27]<br />ᐸ__buildings__.”name”ᐳ"}}:::plan
    PgSelectSingle241 --> PgClassExpression271
    List266{{"List[266∈28]<br />ᐸ87,265ᐳ<br />More deps:<br />- Constantᐸ'buildings'ᐳ[87]"}}:::plan
    PgClassExpression265{{"PgClassExpression[265∈28]<br />ᐸ__buildings__.”id”ᐳ"}}:::plan
    PgClassExpression265 --> List266
    PgSelectSingle243 --> PgClassExpression265
    Lambda267{{"Lambda[267∈28]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List266 --> Lambda267
    PgClassExpression272{{"PgClassExpression[272∈28]<br />ᐸ__buildings__.”name”ᐳ"}}:::plan
    PgSelectSingle243 --> PgClassExpression272
    List269{{"List[269∈29]<br />ᐸ87,268ᐳ<br />More deps:<br />- Constantᐸ'buildings'ᐳ[87]"}}:::plan
    PgClassExpression268{{"PgClassExpression[268∈29]<br />ᐸ__buildings__.”id”ᐳ"}}:::plan
    PgClassExpression268 --> List269
    PgSelectSingle245 --> PgClassExpression268
    Lambda270{{"Lambda[270∈29]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List269 --> Lambda270
    PgClassExpression273{{"PgClassExpression[273∈29]<br />ᐸ__buildings__.”name”ᐳ"}}:::plan
    PgSelectSingle245 --> PgClassExpression273
    __Item258[/"__Item[258∈32]<br />ᐸ250ᐳ"\]:::itemplan
    ConnectionItems250 ==> __Item258
    PgSelectSingle259{{"PgSelectSingle[259∈32]<br />ᐸbuildingsᐳ"}}:::plan
    __Item258 --> PgSelectSingle259
    __Item260[/"__Item[260∈33]<br />ᐸ253ᐳ"\]:::itemplan
    ConnectionItems253 ==> __Item260
    PgSelectSingle261{{"PgSelectSingle[261∈33]<br />ᐸbuildingsᐳ"}}:::plan
    __Item260 --> PgSelectSingle261
    List275{{"List[275∈34]<br />ᐸ87,274ᐳ<br />More deps:<br />- Constantᐸ'buildings'ᐳ[87]"}}:::plan
    PgClassExpression274{{"PgClassExpression[274∈34]<br />ᐸ__buildings__.”id”ᐳ"}}:::plan
    PgClassExpression274 --> List275
    PgSelectSingle259 --> PgClassExpression274
    Lambda276{{"Lambda[276∈34]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List275 --> Lambda276
    PgClassExpression280{{"PgClassExpression[280∈34]<br />ᐸ__buildings__.”name”ᐳ"}}:::plan
    PgSelectSingle259 --> PgClassExpression280
    List278{{"List[278∈35]<br />ᐸ87,277ᐳ<br />More deps:<br />- Constantᐸ'buildings'ᐳ[87]"}}:::plan
    PgClassExpression277{{"PgClassExpression[277∈35]<br />ᐸ__buildings__.”id”ᐳ"}}:::plan
    PgClassExpression277 --> List278
    PgSelectSingle261 --> PgClassExpression277
    Lambda279{{"Lambda[279∈35]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List278 --> Lambda279
    PgClassExpression281{{"PgClassExpression[281∈35]<br />ᐸ__buildings__.”name”ᐳ"}}:::plan
    PgSelectSingle261 --> PgClassExpression281

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect8,Access9,Access10,Object11,Connection12,PgSelect16,First18,PgSelectRows19,PgSelectSingle20,Lambda22,Access23,Access25,PgSelect27,First29,PgSelectRows30,PgSelectSingle31,ConnectionItems32,PgSelectInlineApply282,PgSelectInlineApply286,Access287,PgSelectInlineApply290,PgSelectInlineApply294,PgSelectInlineApply298,PgSelectInlineApply302,PgSelectInlineApply306,PgSelectInlineApply310,Access311,PgSelectInlineApply314,PgSelectInlineApply318,PgSelectInlineApply322,Access323,PgSelectInlineApply326,PgSelectInlineApply330,PgSelectInlineApply334,PgSelectInlineApply338,PgSelectInlineApply342,PgSelectInlineApply346,Access347 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression35,PgClassExpression37,PgClassExpression39,PgClassExpression42,PgClassExpression43,List44,Lambda45 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression36,PgClassExpression38,PgClassExpression40,PgClassExpression46,PgClassExpression47,List48,Lambda49 bucket3
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item51,PgSelectSingle52 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression53,PgClassExpression54,List55,Lambda56,PgClassExpression57,PgClassExpression58,PgClassExpression59,PgClassExpression60,First65,PgSelectRows66,PgSelectSingle67,First70,PgSelectRows71,PgSelectSingle72,First75,PgSelectRows76,PgSelectSingle77,First80,PgSelectRows81,PgSelectSingle82,List288,Lambda289,List312,Lambda313,List324,Lambda325,List348,Lambda349 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression84,List85,Lambda86,PgClassExpression97,Connection106,ConnectionItems143,Access283,List284,Lambda285 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression88,List89,Lambda90,PgClassExpression98,PgClassExpression108,PgClassExpression117,First134,PgSelectRows135,PgSelectSingle136,First140,PgSelectRows141,PgSelectSingle142,Access331,List332,Lambda333,Access343,List344,Lambda345 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgClassExpression92,List93,Lambda94,PgClassExpression99,PgClassExpression109,First122,PgSelectRows123,PgSelectSingle124,Access319,List320,Lambda321 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgClassExpression95,PgClassExpression96,PgClassExpression100,First114,PgSelectRows115,PgSelectSingle116,First127,PgSelectRows128,PgSelectSingle129,Access295,List296,Lambda297,Access307,List308,Lambda309 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11,PgClassExpression146,List147,Lambda148,PgClassExpression161,Connection173,ConnectionItems206,Access291,List292,Lambda293 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgClassExpression149,List150,Lambda151,PgClassExpression162,Connection179,ConnectionItems209,Access315,List316,Lambda317 bucket12
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgClassExpression152,List153,Lambda154,PgClassExpression163,PgClassExpression181,First193,PgSelectRows194,PgSelectSingle195,Access303,List304,Lambda305 bucket13
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgClassExpression155,List156,Lambda157,PgClassExpression164,Connection186,ConnectionItems212,Access327,List328,Lambda329 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgClassExpression158,List159,Lambda160,PgClassExpression165,PgClassExpression188,First200,PgSelectRows201,PgSelectSingle202,Access339,List340,Lambda341 bucket15
    classDef bucket17 stroke:#696969
    class Bucket17,PgClassExpression215,List216,Lambda217,PgClassExpression221,Connection229,ConnectionItems250,Access299,List300,Lambda301 bucket17
    classDef bucket18 stroke:#00bfff
    class Bucket18,PgClassExpression218,List219,Lambda220,PgClassExpression222,Connection235,ConnectionItems253,Access335,List336,Lambda337 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19,__Item204,PgSelectSingle205 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20,PgClassExpression246,List247,Lambda248,PgClassExpression249 bucket20
    classDef bucket24 stroke:#808000
    class Bucket24,__Item240,PgSelectSingle241 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25,__Item242,PgSelectSingle243 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,__Item244,PgSelectSingle245 bucket26
    classDef bucket27 stroke:#ffff00
    class Bucket27,PgClassExpression262,List263,Lambda264,PgClassExpression271 bucket27
    classDef bucket28 stroke:#00ffff
    class Bucket28,PgClassExpression265,List266,Lambda267,PgClassExpression272 bucket28
    classDef bucket29 stroke:#4169e1
    class Bucket29,PgClassExpression268,List269,Lambda270,PgClassExpression273 bucket29
    classDef bucket32 stroke:#ff00ff
    class Bucket32,__Item258,PgSelectSingle259 bucket32
    classDef bucket33 stroke:#f5deb3
    class Bucket33,__Item260,PgSelectSingle261 bucket33
    classDef bucket34 stroke:#696969
    class Bucket34,PgClassExpression274,List275,Lambda276,PgClassExpression280 bucket34
    classDef bucket35 stroke:#00bfff
    class Bucket35,PgClassExpression277,List278,Lambda279,PgClassExpression281 bucket35

