%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/v4/smart_comment_relations.deep-to-one"
    Bucket0("Bucket 0 (root)<br /><br />1: 218, 222, 226, 230, 242, 250, 254, 270, 282, 290, 294<br />ᐳ: 10, 11, 21, 306, 12<br />2: 234, 246, 258, 274, 286, 298<br />3: 238, 262, 302<br />4: PgSelectInlineApply[266]<br />5: PgSelectInlineApply[278]<br />6: PgSelect[9]<br />ᐳ: 219, 279, 287, 303<br />7: Connection[13]<br />8: ConnectionItems[15]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 15, 13, 21, 219, 279, 287, 303<br /><br />ROOT Connectionᐸ9ᐳ[13]"):::bucket
    Bucket3("Bucket 3 (listItem)<br />Deps: 21, 219, 279, 287, 303<br /><br />ROOT __Item{3}ᐸ18ᐳ[19]"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 20, 21, 219, 279, 19, 287, 303<br /><br />ROOT PgSelectSingle{3}ᐸhousesᐳ[20]<br />1: <br />ᐳ: 22, 23, 220, 280, 288, 304, 24, 25, 221, 281, 289, 305<br />2: 32, 37, 42, 47<br />ᐳ: 31, 33, 36, 38, 41, 43, 46, 48"):::bucket
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 33, 305, 31<br /><br />ROOT PgSelectSingle{4}ᐸbuildingsᐳ[33]<br />1: <br />ᐳ: 49, 53, 291, 299, 292, 293, 300, 301<br />2: PgSelectRows[69], PgSelectRows[89]<br />ᐳ: 68, 70, 88, 90"):::bucket
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 38, 289<br /><br />ROOT PgSelectSingle{4}ᐸpropertiesᐳ[38]<br />1: <br />ᐳ: 50, 54, 283, 284, 285<br />2: PgSelectRows[77]<br />ᐳ: First[76], PgSelectSingle[78]"):::bucket
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 43<br /><br />ROOT PgSelectSingle{4}ᐸstreetsᐳ[43]"):::bucket
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 48, 281, 46, 21<br /><br />ROOT PgSelectSingle{4}ᐸstreet_propertyᐳ[48]<br />1: <br />ᐳ: 52, 223, 267, 275, 224, 225, 268, 269, 276, 277<br />2: 62, 83, 94<br />ᐳ: 61, 63, 82, 84, 93, 95"):::bucket
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 63<br /><br />ROOT PgSelectSingle{8}ᐸstreetsᐳ[63]"):::bucket
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 70<br /><br />ROOT PgSelectSingle{5}ᐸstreetsᐳ[70]"):::bucket
    Bucket11("Bucket 11 (nullableBoundary)<br />Deps: 78<br /><br />ROOT PgSelectSingle{6}ᐸstreetsᐳ[78]"):::bucket
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 84, 277<br /><br />ROOT PgSelectSingle{8}ᐸpropertiesᐳ[84]<br />1: <br />ᐳ: 99, 108, 271, 272, 273<br />2: PgSelectRows[124]<br />ᐳ: First[123], PgSelectSingle[125]"):::bucket
    Bucket13("Bucket 13 (nullableBoundary)<br />Deps: 90, 301<br /><br />ROOT PgSelectSingle{5}ᐸpropertiesᐳ[90]<br />1: <br />ᐳ: 100, 109, 295, 296, 297<br />2: PgSelectRows[132]<br />ᐳ: First[131], PgSelectSingle[133]"):::bucket
    Bucket14("Bucket 14 (nullableBoundary)<br />Deps: 95, 21, 269, 93<br /><br />ROOT PgSelectSingle{8}ᐸhousesᐳ[95]<br />1: <br />ᐳ: 101, 102, 239, 247, 263, 103, 104, 240, 241, 248, 249, 264, 265<br />2: 116, 137, 142<br />ᐳ: 115, 117, 136, 138, 141, 143"):::bucket
    Bucket15("Bucket 15 (nullableBoundary)<br />Deps: 117, 265, 115<br /><br />ROOT PgSelectSingle{14}ᐸbuildingsᐳ[117]<br />1: <br />ᐳ: 144, 149, 251, 259, 252, 253, 260, 261<br />2: PgSelectRows[166], PgSelectRows[186]<br />ᐳ: 165, 167, 185, 187"):::bucket
    Bucket16("Bucket 16 (nullableBoundary)<br />Deps: 125<br /><br />ROOT PgSelectSingle{12}ᐸstreetsᐳ[125]"):::bucket
    Bucket17("Bucket 17 (nullableBoundary)<br />Deps: 133<br /><br />ROOT PgSelectSingle{13}ᐸstreetsᐳ[133]"):::bucket
    Bucket18("Bucket 18 (nullableBoundary)<br />Deps: 138, 249<br /><br />ROOT PgSelectSingle{14}ᐸpropertiesᐳ[138]<br />1: <br />ᐳ: 147, 152, 243, 244, 245<br />2: PgSelectRows[174]<br />ᐳ: First[173], PgSelectSingle[175]"):::bucket
    Bucket19("Bucket 19 (nullableBoundary)<br />Deps: 143, 241, 141<br /><br />ROOT PgSelectSingle{14}ᐸstreet_propertyᐳ[143]<br />1: <br />ᐳ: 148, 227, 235, 228, 229, 236, 237<br />2: PgSelectRows[159], PgSelectRows[180]<br />ᐳ: 158, 160, 179, 181"):::bucket
    Bucket20("Bucket 20 (nullableBoundary)<br />Deps: 160<br /><br />ROOT PgSelectSingle{19}ᐸstreetsᐳ[160]"):::bucket
    Bucket21("Bucket 21 (nullableBoundary)<br />Deps: 167<br /><br />ROOT PgSelectSingle{15}ᐸstreetsᐳ[167]"):::bucket
    Bucket22("Bucket 22 (nullableBoundary)<br />Deps: 175<br /><br />ROOT PgSelectSingle{18}ᐸstreetsᐳ[175]"):::bucket
    Bucket23("Bucket 23 (nullableBoundary)<br />Deps: 181, 237<br /><br />ROOT PgSelectSingle{19}ᐸpropertiesᐳ[181]<br />1: <br />ᐳ: 191, 196, 231, 232, 233<br />2: PgSelectRows[204]<br />ᐳ: First[203], PgSelectSingle[205]"):::bucket
    Bucket24("Bucket 24 (nullableBoundary)<br />Deps: 187, 261<br /><br />ROOT PgSelectSingle{15}ᐸpropertiesᐳ[187]<br />1: <br />ᐳ: 192, 197, 255, 256, 257<br />2: PgSelectRows[212]<br />ᐳ: First[211], PgSelectSingle[213]"):::bucket
    Bucket25("Bucket 25 (nullableBoundary)<br />Deps: 205<br /><br />ROOT PgSelectSingle{23}ᐸstreetsᐳ[205]"):::bucket
    Bucket26("Bucket 26 (nullableBoundary)<br />Deps: 213<br /><br />ROOT PgSelectSingle{24}ᐸstreetsᐳ[213]"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5 & Bucket6 & Bucket7 & Bucket8
    Bucket5 --> Bucket10 & Bucket13
    Bucket6 --> Bucket11
    Bucket8 --> Bucket9 & Bucket12 & Bucket14
    Bucket12 --> Bucket16
    Bucket13 --> Bucket17
    Bucket14 --> Bucket15 & Bucket18 & Bucket19
    Bucket15 --> Bucket21 & Bucket24
    Bucket18 --> Bucket22
    Bucket19 --> Bucket20 & Bucket23
    Bucket23 --> Bucket25
    Bucket24 --> Bucket26

    %% plan dependencies
    PgSelect9[["PgSelect[9∈0] ➊<br />ᐸhousesᐳ<br />More deps:<br />- Constantᐸ1ᐳ[306]"]]:::plan
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    PgSelectInlineApply218["PgSelectInlineApply[218∈0] ➊"]:::plan
    PgSelectInlineApply278["PgSelectInlineApply[278∈0] ➊"]:::plan
    PgSelectInlineApply286["PgSelectInlineApply[286∈0] ➊"]:::plan
    PgSelectInlineApply302["PgSelectInlineApply[302∈0] ➊"]:::plan
    Object12 & PgSelectInlineApply218 & PgSelectInlineApply278 & PgSelectInlineApply286 & PgSelectInlineApply302 --> PgSelect9
    PgSelectInlineApply266["PgSelectInlineApply[266∈0] ➊"]:::plan
    PgSelectInlineApply238["PgSelectInlineApply[238∈0] ➊"]:::plan
    PgSelectInlineApply246["PgSelectInlineApply[246∈0] ➊"]:::plan
    PgSelectInlineApply262["PgSelectInlineApply[262∈0] ➊"]:::plan
    PgSelectInlineApply238 & PgSelectInlineApply246 & PgSelectInlineApply262 --> PgSelectInlineApply266
    PgSelectInlineApply222["PgSelectInlineApply[222∈0] ➊"]:::plan
    PgSelectInlineApply274["PgSelectInlineApply[274∈0] ➊"]:::plan
    PgSelectInlineApply222 & PgSelectInlineApply266 & PgSelectInlineApply274 --> PgSelectInlineApply278
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    Connection13[["Connection[13∈0] ➊<br />ᐸ9ᐳ<br />More deps:<br />- Constantᐸ1ᐳ[306]"]]:::plan
    PgSelect9 --> Connection13
    PgSelectInlineApply226["PgSelectInlineApply[226∈0] ➊"]:::plan
    PgSelectInlineApply234["PgSelectInlineApply[234∈0] ➊"]:::plan
    PgSelectInlineApply226 & PgSelectInlineApply234 --> PgSelectInlineApply238
    PgSelectInlineApply250["PgSelectInlineApply[250∈0] ➊"]:::plan
    PgSelectInlineApply258["PgSelectInlineApply[258∈0] ➊"]:::plan
    PgSelectInlineApply250 & PgSelectInlineApply258 --> PgSelectInlineApply262
    PgSelectInlineApply290["PgSelectInlineApply[290∈0] ➊"]:::plan
    PgSelectInlineApply298["PgSelectInlineApply[298∈0] ➊"]:::plan
    PgSelectInlineApply290 & PgSelectInlineApply298 --> PgSelectInlineApply302
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    ConnectionItems15[["ConnectionItems[15∈0] ➊"]]:::plan
    Connection13 --> ConnectionItems15
    Access219{{"Access[219∈0] ➊<br />ᐸ9.m.joinDetailsFor39ᐳ"}}:::plan
    PgSelect9 --> Access219
    PgSelectInlineApply230["PgSelectInlineApply[230∈0] ➊"]:::plan
    PgSelectInlineApply230 --> PgSelectInlineApply234
    PgSelectInlineApply242["PgSelectInlineApply[242∈0] ➊"]:::plan
    PgSelectInlineApply242 --> PgSelectInlineApply246
    PgSelectInlineApply254["PgSelectInlineApply[254∈0] ➊"]:::plan
    PgSelectInlineApply254 --> PgSelectInlineApply258
    PgSelectInlineApply270["PgSelectInlineApply[270∈0] ➊"]:::plan
    PgSelectInlineApply270 --> PgSelectInlineApply274
    Access279{{"Access[279∈0] ➊<br />ᐸ9.m.subqueryDetailsFor44ᐳ"}}:::plan
    PgSelect9 --> Access279
    PgSelectInlineApply282["PgSelectInlineApply[282∈0] ➊"]:::plan
    PgSelectInlineApply282 --> PgSelectInlineApply286
    Access287{{"Access[287∈0] ➊<br />ᐸ9.m.subqueryDetailsFor34ᐳ"}}:::plan
    PgSelect9 --> Access287
    PgSelectInlineApply294["PgSelectInlineApply[294∈0] ➊"]:::plan
    PgSelectInlineApply294 --> PgSelectInlineApply298
    Access303{{"Access[303∈0] ➊<br />ᐸ9.m.subqueryDetailsFor27ᐳ"}}:::plan
    PgSelect9 --> Access303
    __CloneStream18[["__CloneStream[18∈1] ➊"]]:::plan
    ConnectionItems15 --> __CloneStream18
    __Item19[/"__Item[19∈3]<br />ᐸ18ᐳ"\]:::itemplan
    __CloneStream18 ==> __Item19
    PgSelectSingle20{{"PgSelectSingle[20∈3]<br />ᐸhousesᐳ"}}:::plan
    __Item19 --> PgSelectSingle20
    List24{{"List[24∈4]<br />ᐸ21,22,23ᐳ<br />More deps:<br />- Constantᐸ'houses'ᐳ[21]"}}:::plan
    PgClassExpression22{{"PgClassExpression[22∈4]<br />ᐸ__houses__.”street_id”ᐳ"}}:::plan
    PgClassExpression23{{"PgClassExpression[23∈4]<br />ᐸ__houses__...operty_id”ᐳ"}}:::plan
    PgClassExpression22 & PgClassExpression23 --> List24
    List220{{"List[220∈4]<br />ᐸ219,20ᐳ"}}:::plan
    Access219 & PgSelectSingle20 --> List220
    List280{{"List[280∈4]<br />ᐸ279,19ᐳ"}}:::plan
    Access279 & __Item19 --> List280
    List288{{"List[288∈4]<br />ᐸ287,19ᐳ"}}:::plan
    Access287 & __Item19 --> List288
    List304{{"List[304∈4]<br />ᐸ303,19ᐳ"}}:::plan
    Access303 & __Item19 --> List304
    PgSelectSingle20 --> PgClassExpression22
    PgSelectSingle20 --> PgClassExpression23
    Lambda25{{"Lambda[25∈4]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List24 --> Lambda25
    First31{{"First[31∈4]"}}:::plan
    PgSelectRows32[["PgSelectRows[32∈4]"]]:::plan
    PgSelectRows32 --> First31
    Lambda305{{"Lambda[305∈4]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda305 --> PgSelectRows32
    PgSelectSingle33{{"PgSelectSingle[33∈4]<br />ᐸbuildingsᐳ"}}:::plan
    First31 --> PgSelectSingle33
    First36{{"First[36∈4]"}}:::plan
    PgSelectRows37[["PgSelectRows[37∈4]"]]:::plan
    PgSelectRows37 --> First36
    Lambda289{{"Lambda[289∈4]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda289 --> PgSelectRows37
    PgSelectSingle38{{"PgSelectSingle[38∈4]<br />ᐸpropertiesᐳ"}}:::plan
    First36 --> PgSelectSingle38
    First41{{"First[41∈4]"}}:::plan
    PgSelectRows42[["PgSelectRows[42∈4]"]]:::plan
    PgSelectRows42 --> First41
    Lambda221{{"Lambda[221∈4]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda221 --> PgSelectRows42
    PgSelectSingle43{{"PgSelectSingle[43∈4]<br />ᐸstreetsᐳ"}}:::plan
    First41 --> PgSelectSingle43
    First46{{"First[46∈4]"}}:::plan
    PgSelectRows47[["PgSelectRows[47∈4]"]]:::plan
    PgSelectRows47 --> First46
    Lambda281{{"Lambda[281∈4]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda281 --> PgSelectRows47
    PgSelectSingle48{{"PgSelectSingle[48∈4]<br />ᐸstreet_propertyᐳ"}}:::plan
    First46 --> PgSelectSingle48
    List220 --> Lambda221
    List280 --> Lambda281
    List288 --> Lambda289
    List304 --> Lambda305
    List292{{"List[292∈5]<br />ᐸ291,33ᐳ"}}:::plan
    Access291{{"Access[291∈5]<br />ᐸ305.m.joinDetailsFor64ᐳ"}}:::plan
    Access291 & PgSelectSingle33 --> List292
    List300{{"List[300∈5]<br />ᐸ299,31ᐳ"}}:::plan
    Access299{{"Access[299∈5]<br />ᐸ305.m.subqueryDetailsFor86ᐳ"}}:::plan
    Access299 & First31 --> List300
    PgClassExpression49{{"PgClassExpression[49∈5]<br />ᐸ__buildings__.”id”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression49
    PgClassExpression53{{"PgClassExpression[53∈5]<br />ᐸ__buildings__.”name”ᐳ"}}:::plan
    PgClassExpression49 o--o PgClassExpression53
    First68{{"First[68∈5]"}}:::plan
    PgSelectRows69[["PgSelectRows[69∈5]"]]:::plan
    PgSelectRows69 --> First68
    Lambda293{{"Lambda[293∈5]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda293 --> PgSelectRows69
    PgSelectSingle70{{"PgSelectSingle[70∈5]<br />ᐸstreetsᐳ"}}:::plan
    First68 --> PgSelectSingle70
    First88{{"First[88∈5]"}}:::plan
    PgSelectRows89[["PgSelectRows[89∈5]"]]:::plan
    PgSelectRows89 --> First88
    Lambda301{{"Lambda[301∈5]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda301 --> PgSelectRows89
    PgSelectSingle90{{"PgSelectSingle[90∈5]<br />ᐸpropertiesᐳ"}}:::plan
    First88 --> PgSelectSingle90
    Lambda305 --> Access291
    List292 --> Lambda293
    Lambda305 --> Access299
    List300 --> Lambda301
    List284{{"List[284∈6]<br />ᐸ283,38ᐳ"}}:::plan
    Access283{{"Access[283∈6]<br />ᐸ289.m.joinDetailsFor72ᐳ"}}:::plan
    Access283 & PgSelectSingle38 --> List284
    PgClassExpression50{{"PgClassExpression[50∈6]<br />ᐸ__properties__.”id”ᐳ"}}:::plan
    PgSelectSingle38 --> PgClassExpression50
    PgClassExpression54{{"PgClassExpression[54∈6]<br />ᐸ__properti...or_number”ᐳ"}}:::plan
    PgClassExpression50 o--o PgClassExpression54
    First76{{"First[76∈6]"}}:::plan
    PgSelectRows77[["PgSelectRows[77∈6]"]]:::plan
    PgSelectRows77 --> First76
    Lambda285{{"Lambda[285∈6]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda285 --> PgSelectRows77
    PgSelectSingle78{{"PgSelectSingle[78∈6]<br />ᐸstreetsᐳ"}}:::plan
    First76 --> PgSelectSingle78
    Lambda289 --> Access283
    List284 --> Lambda285
    PgClassExpression51{{"PgClassExpression[51∈7]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression51
    PgClassExpression55{{"PgClassExpression[55∈7]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgClassExpression51 o--o PgClassExpression55
    List224{{"List[224∈8]<br />ᐸ223,48ᐳ"}}:::plan
    Access223{{"Access[223∈8]<br />ᐸ281.m.joinDetailsFor57ᐳ"}}:::plan
    Access223 & PgSelectSingle48 --> List224
    List268{{"List[268∈8]<br />ᐸ267,46ᐳ"}}:::plan
    Access267{{"Access[267∈8]<br />ᐸ281.m.subqueryDetailsFor91ᐳ"}}:::plan
    Access267 & First46 --> List268
    List276{{"List[276∈8]<br />ᐸ275,46ᐳ"}}:::plan
    Access275{{"Access[275∈8]<br />ᐸ281.m.subqueryDetailsFor80ᐳ"}}:::plan
    Access275 & First46 --> List276
    PgClassExpression52{{"PgClassExpression[52∈8]<br />ᐸ__street_p...ent_owner”ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression52
    First61{{"First[61∈8]"}}:::plan
    PgSelectRows62[["PgSelectRows[62∈8]"]]:::plan
    PgSelectRows62 --> First61
    Lambda225{{"Lambda[225∈8]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda225 --> PgSelectRows62
    PgSelectSingle63{{"PgSelectSingle[63∈8]<br />ᐸstreetsᐳ"}}:::plan
    First61 --> PgSelectSingle63
    First82{{"First[82∈8]"}}:::plan
    PgSelectRows83[["PgSelectRows[83∈8]"]]:::plan
    PgSelectRows83 --> First82
    Lambda277{{"Lambda[277∈8]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda277 --> PgSelectRows83
    PgSelectSingle84{{"PgSelectSingle[84∈8]<br />ᐸpropertiesᐳ"}}:::plan
    First82 --> PgSelectSingle84
    First93{{"First[93∈8]"}}:::plan
    PgSelectRows94[["PgSelectRows[94∈8]"]]:::plan
    PgSelectRows94 --> First93
    Lambda269{{"Lambda[269∈8]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda269 --> PgSelectRows94
    PgSelectSingle95{{"PgSelectSingle[95∈8]<br />ᐸhousesᐳ"}}:::plan
    First93 --> PgSelectSingle95
    Lambda281 --> Access223
    List224 --> Lambda225
    Lambda281 --> Access267
    List268 --> Lambda269
    Lambda281 --> Access275
    List276 --> Lambda277
    PgClassExpression96{{"PgClassExpression[96∈9]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgSelectSingle63 --> PgClassExpression96
    PgClassExpression105{{"PgClassExpression[105∈9]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgClassExpression96 o--o PgClassExpression105
    PgClassExpression97{{"PgClassExpression[97∈10]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgSelectSingle70 --> PgClassExpression97
    PgClassExpression106{{"PgClassExpression[106∈10]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgClassExpression97 o--o PgClassExpression106
    PgClassExpression98{{"PgClassExpression[98∈11]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgSelectSingle78 --> PgClassExpression98
    PgClassExpression107{{"PgClassExpression[107∈11]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgClassExpression98 o--o PgClassExpression107
    List272{{"List[272∈12]<br />ᐸ271,84ᐳ"}}:::plan
    Access271{{"Access[271∈12]<br />ᐸ277.m.joinDetailsFor119ᐳ"}}:::plan
    Access271 & PgSelectSingle84 --> List272
    PgClassExpression99{{"PgClassExpression[99∈12]<br />ᐸ__properties__.”id”ᐳ"}}:::plan
    PgSelectSingle84 --> PgClassExpression99
    PgClassExpression108{{"PgClassExpression[108∈12]<br />ᐸ__properti...or_number”ᐳ"}}:::plan
    PgClassExpression99 o--o PgClassExpression108
    First123{{"First[123∈12]"}}:::plan
    PgSelectRows124[["PgSelectRows[124∈12]"]]:::plan
    PgSelectRows124 --> First123
    Lambda273{{"Lambda[273∈12]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda273 --> PgSelectRows124
    PgSelectSingle125{{"PgSelectSingle[125∈12]<br />ᐸstreetsᐳ"}}:::plan
    First123 --> PgSelectSingle125
    Lambda277 --> Access271
    List272 --> Lambda273
    List296{{"List[296∈13]<br />ᐸ295,90ᐳ"}}:::plan
    Access295{{"Access[295∈13]<br />ᐸ301.m.joinDetailsFor127ᐳ"}}:::plan
    Access295 & PgSelectSingle90 --> List296
    PgClassExpression100{{"PgClassExpression[100∈13]<br />ᐸ__properties__.”id”ᐳ"}}:::plan
    PgSelectSingle90 --> PgClassExpression100
    PgClassExpression109{{"PgClassExpression[109∈13]<br />ᐸ__properti...or_number”ᐳ"}}:::plan
    PgClassExpression100 o--o PgClassExpression109
    First131{{"First[131∈13]"}}:::plan
    PgSelectRows132[["PgSelectRows[132∈13]"]]:::plan
    PgSelectRows132 --> First131
    Lambda297{{"Lambda[297∈13]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda297 --> PgSelectRows132
    PgSelectSingle133{{"PgSelectSingle[133∈13]<br />ᐸstreetsᐳ"}}:::plan
    First131 --> PgSelectSingle133
    Lambda301 --> Access295
    List296 --> Lambda297
    List103{{"List[103∈14]<br />ᐸ21,101,102ᐳ<br />More deps:<br />- Constantᐸ'houses'ᐳ[21]"}}:::plan
    PgClassExpression101{{"PgClassExpression[101∈14]<br />ᐸ__houses__.”street_id”ᐳ"}}:::plan
    PgClassExpression102{{"PgClassExpression[102∈14]<br />ᐸ__houses__...operty_id”ᐳ"}}:::plan
    PgClassExpression101 & PgClassExpression102 --> List103
    List240{{"List[240∈14]<br />ᐸ239,93ᐳ"}}:::plan
    Access239{{"Access[239∈14]<br />ᐸ269.m.subqueryDetailsFor139ᐳ"}}:::plan
    Access239 & First93 --> List240
    List248{{"List[248∈14]<br />ᐸ247,93ᐳ"}}:::plan
    Access247{{"Access[247∈14]<br />ᐸ269.m.subqueryDetailsFor134ᐳ"}}:::plan
    Access247 & First93 --> List248
    List264{{"List[264∈14]<br />ᐸ263,93ᐳ"}}:::plan
    Access263{{"Access[263∈14]<br />ᐸ269.m.subqueryDetailsFor111ᐳ"}}:::plan
    Access263 & First93 --> List264
    PgSelectSingle95 --> PgClassExpression101
    PgSelectSingle95 --> PgClassExpression102
    Lambda104{{"Lambda[104∈14]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List103 --> Lambda104
    First115{{"First[115∈14]"}}:::plan
    PgSelectRows116[["PgSelectRows[116∈14]"]]:::plan
    PgSelectRows116 --> First115
    Lambda265{{"Lambda[265∈14]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda265 --> PgSelectRows116
    PgSelectSingle117{{"PgSelectSingle[117∈14]<br />ᐸbuildingsᐳ"}}:::plan
    First115 --> PgSelectSingle117
    First136{{"First[136∈14]"}}:::plan
    PgSelectRows137[["PgSelectRows[137∈14]"]]:::plan
    PgSelectRows137 --> First136
    Lambda249{{"Lambda[249∈14]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda249 --> PgSelectRows137
    PgSelectSingle138{{"PgSelectSingle[138∈14]<br />ᐸpropertiesᐳ"}}:::plan
    First136 --> PgSelectSingle138
    First141{{"First[141∈14]"}}:::plan
    PgSelectRows142[["PgSelectRows[142∈14]"]]:::plan
    PgSelectRows142 --> First141
    Lambda241{{"Lambda[241∈14]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda241 --> PgSelectRows142
    PgSelectSingle143{{"PgSelectSingle[143∈14]<br />ᐸstreet_propertyᐳ"}}:::plan
    First141 --> PgSelectSingle143
    Lambda269 --> Access239
    List240 --> Lambda241
    Lambda269 --> Access247
    List248 --> Lambda249
    Lambda269 --> Access263
    List264 --> Lambda265
    List252{{"List[252∈15]<br />ᐸ251,117ᐳ"}}:::plan
    Access251{{"Access[251∈15]<br />ᐸ265.m.joinDetailsFor161ᐳ"}}:::plan
    Access251 & PgSelectSingle117 --> List252
    List260{{"List[260∈15]<br />ᐸ259,115ᐳ"}}:::plan
    Access259{{"Access[259∈15]<br />ᐸ265.m.subqueryDetailsFor183ᐳ"}}:::plan
    Access259 & First115 --> List260
    PgClassExpression144{{"PgClassExpression[144∈15]<br />ᐸ__buildings__.”id”ᐳ"}}:::plan
    PgSelectSingle117 --> PgClassExpression144
    PgClassExpression149{{"PgClassExpression[149∈15]<br />ᐸ__buildings__.”name”ᐳ"}}:::plan
    PgClassExpression144 o--o PgClassExpression149
    First165{{"First[165∈15]"}}:::plan
    PgSelectRows166[["PgSelectRows[166∈15]"]]:::plan
    PgSelectRows166 --> First165
    Lambda253{{"Lambda[253∈15]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda253 --> PgSelectRows166
    PgSelectSingle167{{"PgSelectSingle[167∈15]<br />ᐸstreetsᐳ"}}:::plan
    First165 --> PgSelectSingle167
    First185{{"First[185∈15]"}}:::plan
    PgSelectRows186[["PgSelectRows[186∈15]"]]:::plan
    PgSelectRows186 --> First185
    Lambda261{{"Lambda[261∈15]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda261 --> PgSelectRows186
    PgSelectSingle187{{"PgSelectSingle[187∈15]<br />ᐸpropertiesᐳ"}}:::plan
    First185 --> PgSelectSingle187
    Lambda265 --> Access251
    List252 --> Lambda253
    Lambda265 --> Access259
    List260 --> Lambda261
    PgClassExpression145{{"PgClassExpression[145∈16]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgSelectSingle125 --> PgClassExpression145
    PgClassExpression150{{"PgClassExpression[150∈16]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgClassExpression145 o--o PgClassExpression150
    PgClassExpression146{{"PgClassExpression[146∈17]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgSelectSingle133 --> PgClassExpression146
    PgClassExpression151{{"PgClassExpression[151∈17]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgClassExpression146 o--o PgClassExpression151
    List244{{"List[244∈18]<br />ᐸ243,138ᐳ"}}:::plan
    Access243{{"Access[243∈18]<br />ᐸ249.m.joinDetailsFor169ᐳ"}}:::plan
    Access243 & PgSelectSingle138 --> List244
    PgClassExpression147{{"PgClassExpression[147∈18]<br />ᐸ__properties__.”id”ᐳ"}}:::plan
    PgSelectSingle138 --> PgClassExpression147
    PgClassExpression152{{"PgClassExpression[152∈18]<br />ᐸ__properti...or_number”ᐳ"}}:::plan
    PgClassExpression147 o--o PgClassExpression152
    First173{{"First[173∈18]"}}:::plan
    PgSelectRows174[["PgSelectRows[174∈18]"]]:::plan
    PgSelectRows174 --> First173
    Lambda245{{"Lambda[245∈18]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda245 --> PgSelectRows174
    PgSelectSingle175{{"PgSelectSingle[175∈18]<br />ᐸstreetsᐳ"}}:::plan
    First173 --> PgSelectSingle175
    Lambda249 --> Access243
    List244 --> Lambda245
    List228{{"List[228∈19]<br />ᐸ227,143ᐳ"}}:::plan
    Access227{{"Access[227∈19]<br />ᐸ241.m.joinDetailsFor154ᐳ"}}:::plan
    Access227 & PgSelectSingle143 --> List228
    List236{{"List[236∈19]<br />ᐸ235,141ᐳ"}}:::plan
    Access235{{"Access[235∈19]<br />ᐸ241.m.subqueryDetailsFor177ᐳ"}}:::plan
    Access235 & First141 --> List236
    PgClassExpression148{{"PgClassExpression[148∈19]<br />ᐸ__street_p...ent_owner”ᐳ"}}:::plan
    PgSelectSingle143 --> PgClassExpression148
    First158{{"First[158∈19]"}}:::plan
    PgSelectRows159[["PgSelectRows[159∈19]"]]:::plan
    PgSelectRows159 --> First158
    Lambda229{{"Lambda[229∈19]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda229 --> PgSelectRows159
    PgSelectSingle160{{"PgSelectSingle[160∈19]<br />ᐸstreetsᐳ"}}:::plan
    First158 --> PgSelectSingle160
    First179{{"First[179∈19]"}}:::plan
    PgSelectRows180[["PgSelectRows[180∈19]"]]:::plan
    PgSelectRows180 --> First179
    Lambda237{{"Lambda[237∈19]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda237 --> PgSelectRows180
    PgSelectSingle181{{"PgSelectSingle[181∈19]<br />ᐸpropertiesᐳ"}}:::plan
    First179 --> PgSelectSingle181
    Lambda241 --> Access227
    List228 --> Lambda229
    Lambda241 --> Access235
    List236 --> Lambda237
    PgClassExpression188{{"PgClassExpression[188∈20]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgSelectSingle160 --> PgClassExpression188
    PgClassExpression193{{"PgClassExpression[193∈20]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgClassExpression188 o--o PgClassExpression193
    PgClassExpression189{{"PgClassExpression[189∈21]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgSelectSingle167 --> PgClassExpression189
    PgClassExpression194{{"PgClassExpression[194∈21]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgClassExpression189 o--o PgClassExpression194
    PgClassExpression190{{"PgClassExpression[190∈22]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgSelectSingle175 --> PgClassExpression190
    PgClassExpression195{{"PgClassExpression[195∈22]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgClassExpression190 o--o PgClassExpression195
    List232{{"List[232∈23]<br />ᐸ231,181ᐳ"}}:::plan
    Access231{{"Access[231∈23]<br />ᐸ237.m.joinDetailsFor199ᐳ"}}:::plan
    Access231 & PgSelectSingle181 --> List232
    PgClassExpression191{{"PgClassExpression[191∈23]<br />ᐸ__properties__.”id”ᐳ"}}:::plan
    PgSelectSingle181 --> PgClassExpression191
    PgClassExpression196{{"PgClassExpression[196∈23]<br />ᐸ__properti...or_number”ᐳ"}}:::plan
    PgClassExpression191 o--o PgClassExpression196
    First203{{"First[203∈23]"}}:::plan
    PgSelectRows204[["PgSelectRows[204∈23]"]]:::plan
    PgSelectRows204 --> First203
    Lambda233{{"Lambda[233∈23]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda233 --> PgSelectRows204
    PgSelectSingle205{{"PgSelectSingle[205∈23]<br />ᐸstreetsᐳ"}}:::plan
    First203 --> PgSelectSingle205
    Lambda237 --> Access231
    List232 --> Lambda233
    List256{{"List[256∈24]<br />ᐸ255,187ᐳ"}}:::plan
    Access255{{"Access[255∈24]<br />ᐸ261.m.joinDetailsFor207ᐳ"}}:::plan
    Access255 & PgSelectSingle187 --> List256
    PgClassExpression192{{"PgClassExpression[192∈24]<br />ᐸ__properties__.”id”ᐳ"}}:::plan
    PgSelectSingle187 --> PgClassExpression192
    PgClassExpression197{{"PgClassExpression[197∈24]<br />ᐸ__properti...or_number”ᐳ"}}:::plan
    PgClassExpression192 o--o PgClassExpression197
    First211{{"First[211∈24]"}}:::plan
    PgSelectRows212[["PgSelectRows[212∈24]"]]:::plan
    PgSelectRows212 --> First211
    Lambda257{{"Lambda[257∈24]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda257 --> PgSelectRows212
    PgSelectSingle213{{"PgSelectSingle[213∈24]<br />ᐸstreetsᐳ"}}:::plan
    First211 --> PgSelectSingle213
    Lambda261 --> Access255
    List256 --> Lambda257
    PgClassExpression214{{"PgClassExpression[214∈25]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgSelectSingle205 --> PgClassExpression214
    PgClassExpression216{{"PgClassExpression[216∈25]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgClassExpression214 o--o PgClassExpression216
    PgClassExpression215{{"PgClassExpression[215∈26]<br />ᐸ__streets__.”id”ᐳ"}}:::plan
    PgSelectSingle213 --> PgClassExpression215
    PgClassExpression217{{"PgClassExpression[217∈26]<br />ᐸ__streets__.”name”ᐳ"}}:::plan
    PgClassExpression215 o--o PgClassExpression217

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect9,Access10,Access11,Object12,Connection13,ConnectionItems15,PgSelectInlineApply218,Access219,PgSelectInlineApply222,PgSelectInlineApply226,PgSelectInlineApply230,PgSelectInlineApply234,PgSelectInlineApply238,PgSelectInlineApply242,PgSelectInlineApply246,PgSelectInlineApply250,PgSelectInlineApply254,PgSelectInlineApply258,PgSelectInlineApply262,PgSelectInlineApply266,PgSelectInlineApply270,PgSelectInlineApply274,PgSelectInlineApply278,Access279,PgSelectInlineApply282,PgSelectInlineApply286,Access287,PgSelectInlineApply290,PgSelectInlineApply294,PgSelectInlineApply298,PgSelectInlineApply302,Access303 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,__CloneStream18 bucket1
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item19,PgSelectSingle20 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression22,PgClassExpression23,List24,Lambda25,First31,PgSelectRows32,PgSelectSingle33,First36,PgSelectRows37,PgSelectSingle38,First41,PgSelectRows42,PgSelectSingle43,First46,PgSelectRows47,PgSelectSingle48,List220,Lambda221,List280,Lambda281,List288,Lambda289,List304,Lambda305 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression49,PgClassExpression53,First68,PgSelectRows69,PgSelectSingle70,First88,PgSelectRows89,PgSelectSingle90,Access291,List292,Lambda293,Access299,List300,Lambda301 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression50,PgClassExpression54,First76,PgSelectRows77,PgSelectSingle78,Access283,List284,Lambda285 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression51,PgClassExpression55 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression52,First61,PgSelectRows62,PgSelectSingle63,First82,PgSelectRows83,PgSelectSingle84,First93,PgSelectRows94,PgSelectSingle95,Access223,List224,Lambda225,Access267,List268,Lambda269,Access275,List276,Lambda277 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgClassExpression96,PgClassExpression105 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgClassExpression97,PgClassExpression106 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11,PgClassExpression98,PgClassExpression107 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgClassExpression99,PgClassExpression108,First123,PgSelectRows124,PgSelectSingle125,Access271,List272,Lambda273 bucket12
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgClassExpression100,PgClassExpression109,First131,PgSelectRows132,PgSelectSingle133,Access295,List296,Lambda297 bucket13
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgClassExpression101,PgClassExpression102,List103,Lambda104,First115,PgSelectRows116,PgSelectSingle117,First136,PgSelectRows137,PgSelectSingle138,First141,PgSelectRows142,PgSelectSingle143,Access239,List240,Lambda241,Access247,List248,Lambda249,Access263,List264,Lambda265 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgClassExpression144,PgClassExpression149,First165,PgSelectRows166,PgSelectSingle167,First185,PgSelectRows186,PgSelectSingle187,Access251,List252,Lambda253,Access259,List260,Lambda261 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16,PgClassExpression145,PgClassExpression150 bucket16
    classDef bucket17 stroke:#696969
    class Bucket17,PgClassExpression146,PgClassExpression151 bucket17
    classDef bucket18 stroke:#00bfff
    class Bucket18,PgClassExpression147,PgClassExpression152,First173,PgSelectRows174,PgSelectSingle175,Access243,List244,Lambda245 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19,PgClassExpression148,First158,PgSelectRows159,PgSelectSingle160,First179,PgSelectRows180,PgSelectSingle181,Access227,List228,Lambda229,Access235,List236,Lambda237 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20,PgClassExpression188,PgClassExpression193 bucket20
    classDef bucket21 stroke:#0000ff
    class Bucket21,PgClassExpression189,PgClassExpression194 bucket21
    classDef bucket22 stroke:#7fff00
    class Bucket22,PgClassExpression190,PgClassExpression195 bucket22
    classDef bucket23 stroke:#ff1493
    class Bucket23,PgClassExpression191,PgClassExpression196,First203,PgSelectRows204,PgSelectSingle205,Access231,List232,Lambda233 bucket23
    classDef bucket24 stroke:#808000
    class Bucket24,PgClassExpression192,PgClassExpression197,First211,PgSelectRows212,PgSelectSingle213,Access255,List256,Lambda257 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25,PgClassExpression214,PgClassExpression216 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,PgClassExpression215,PgClassExpression217 bucket26

