%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/interfaces-relational/nested-more-fragments"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 6, 8, 9, 10<br />2: PgSelect[7]<br />3: PgSelectRows[11]"):::bucket
    Bucket1("Bucket 1 (listItem)<br />Deps: 10, 6<br /><br />ROOT __Item{1}ᐸ11ᐳ[13]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 14, 10, 6<br /><br />ROOT PgSelectSingle{1}ᐸpeopleᐳ[14]<br />1: <br />ᐳ: 15, 16<br />2: PgSelect[17]<br />3: PgSelectRows[21]"):::bucket
    Bucket3("Bucket 3 (listItem)<br />Deps: 10<br /><br />ROOT __Item{3}ᐸ21ᐳ[23]<br />1: <br />ᐳ: 24, 25, 28, 29, 120, 125, 155, 160, 165, 170, 175<br />2: PgSelect[126]<br />3: PgSelectRows[129]<br />ᐳ: First[128], PgSelectSingle[130]"):::bucket
    Bucket4("Bucket 4 (polymorphic)<br />__typename: Lambda[29]<br />Deps: 29, 10, 25, 130, 24, 28, 120, 155, 160, 165, 170, 175"):::bucket
    Bucket5("Bucket 5 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 25, 130, 24, 28, 120, 155, 160, 165, 170, 175<br />ᐳRelationalTopic<br /><br />1: PgSelect[31]<br />2: PgSelectRows[36]<br />ᐳ: 35, 37, 180"):::bucket
    Bucket6("Bucket 6 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 25, 130, 24, 28, 120, 155, 160, 165, 170, 175<br />ᐳRelationalPost<br /><br />1: PgSelect[39]<br />2: PgSelectRows[44]<br />ᐳ: 43, 45, 181, 185, 188"):::bucket
    Bucket7("Bucket 7 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 25, 130, 24, 28, 120, 155, 160, 165, 170, 175<br />ᐳRelationalDivider<br /><br />1: PgSelect[47]<br />2: PgSelectRows[52]<br />ᐳ: 51, 53, 182, 186"):::bucket
    Bucket8("Bucket 8 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 25, 130, 24, 28, 120, 155, 160, 165, 170, 175<br />ᐳRelationalChecklist<br /><br />1: PgSelect[55]<br />2: PgSelectRows[60]<br />ᐳ: 59, 61, 183"):::bucket
    Bucket9("Bucket 9 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 25, 130, 24, 28, 120, 155, 160, 165, 170, 175<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[63]<br />2: PgSelectRows[68]<br />ᐳ: 67, 69, 184, 187"):::bucket
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 130<br /><br />ROOT PgSelectSingle{3}ᐸpeopleᐳ[130]"):::bucket
    Bucket11("Bucket 11 (nullableBoundary)<br />Deps: 130<br /><br />ROOT PgSelectSingle{3}ᐸpeopleᐳ[130]"):::bucket
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 130<br /><br />ROOT PgSelectSingle{3}ᐸpeopleᐳ[130]"):::bucket
    Bucket13("Bucket 13 (nullableBoundary)<br />Deps: 130<br /><br />ROOT PgSelectSingle{3}ᐸpeopleᐳ[130]"):::bucket
    Bucket14("Bucket 14 (nullableBoundary)<br />Deps: 130<br /><br />ROOT PgSelectSingle{3}ᐸpeopleᐳ[130]"):::bucket
    Bucket15("Bucket 15 (combined)<br />Deps: 24, 10<br /><br />1: <br />ᐳ: PgClassExpression[70]<br />2: PgSelect[71]<br />3: PgSelectRows[76]<br />ᐳ: 75, 77, 189, 192, 193, 249, 254, 294, 299, 304, 309, 314<br />4: PgSelect[255]<br />5: PgSelectRows[260]<br />ᐳ: First[259], PgSelectSingle[261]"):::bucket
    Bucket16("Bucket 16 (polymorphic)<br />__typename: Lambda[193]<br />Deps: 193, 10, 189, 261, 192, 249, 294, 299, 304, 309, 314"):::bucket
    Bucket17("Bucket 17 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 189, 261, 192, 249, 294, 299, 304, 309, 314<br />(5) ...ᐳRelationalTopic<br /><br />1: PgSelect[195]<br />2: PgSelectRows[200]<br />ᐳ: 199, 201, 319"):::bucket
    Bucket18("Bucket 18 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 189, 261, 192, 249, 294, 299, 304, 309, 314<br />(5) ...ᐳRelationalPost<br /><br />1: PgSelect[203]<br />2: PgSelectRows[208]<br />ᐳ: 207, 209, 320, 324, 327"):::bucket
    Bucket19("Bucket 19 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 189, 261, 192, 249, 294, 299, 304, 309, 314<br />(5) ...ᐳRelationalDivider<br /><br />1: PgSelect[211]<br />2: PgSelectRows[216]<br />ᐳ: 215, 217, 321, 325"):::bucket
    Bucket20("Bucket 20 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 189, 261, 192, 249, 294, 299, 304, 309, 314<br />(5) ...ᐳRelationalChecklist<br /><br />1: PgSelect[219]<br />2: PgSelectRows[224]<br />ᐳ: 223, 225, 322"):::bucket
    Bucket21("Bucket 21 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 189, 261, 192, 249, 294, 299, 304, 309, 314<br />(5) ...ᐳRelationalChecklistItem<br /><br />1: PgSelect[227]<br />2: PgSelectRows[232]<br />ᐳ: 231, 233, 323, 326"):::bucket
    Bucket22("Bucket 22 (nullableBoundary)<br />Deps: 261<br /><br />ROOT PgSelectSingle{15}ᐸpeopleᐳ[261]"):::bucket
    Bucket23("Bucket 23 (nullableBoundary)<br />Deps: 261<br /><br />ROOT PgSelectSingle{15}ᐸpeopleᐳ[261]"):::bucket
    Bucket24("Bucket 24 (nullableBoundary)<br />Deps: 261<br /><br />ROOT PgSelectSingle{15}ᐸpeopleᐳ[261]"):::bucket
    Bucket25("Bucket 25 (nullableBoundary)<br />Deps: 261<br /><br />ROOT PgSelectSingle{15}ᐸpeopleᐳ[261]"):::bucket
    Bucket26("Bucket 26 (nullableBoundary)<br />Deps: 261<br /><br />ROOT PgSelectSingle{15}ᐸpeopleᐳ[261]"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5 & Bucket6 & Bucket7 & Bucket8 & Bucket9
    Bucket5 --> Bucket10 & Bucket15
    Bucket6 --> Bucket11 & Bucket15
    Bucket7 --> Bucket12 & Bucket15
    Bucket8 --> Bucket13 & Bucket15
    Bucket9 --> Bucket14 & Bucket15
    Bucket15 --> Bucket16
    Bucket16 --> Bucket17 & Bucket18 & Bucket19 & Bucket20 & Bucket21
    Bucket17 --> Bucket22
    Bucket18 --> Bucket23
    Bucket19 --> Bucket24
    Bucket20 --> Bucket25
    Bucket21 --> Bucket26

    %% plan dependencies
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸpeopleᐳ<br />More deps:<br />- Object[10]<br />- Constantᐸundefinedᐳ[6]"]]:::plan
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ<br />Dependents: 15"}}:::plan
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    PgSelectRows11[["PgSelectRows[11∈0] ➊"]]:::plan
    PgSelect7 --> PgSelectRows11
    __Item13[/"__Item[13∈1]<br />ᐸ11ᐳ"\]:::itemplan
    PgSelectRows11 ==> __Item13
    PgSelectSingle14{{"PgSelectSingle[14∈1]<br />ᐸpeopleᐳ"}}:::plan
    __Item13 --> PgSelectSingle14
    PgSelect17[["PgSelect[17∈2]<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]<br />- Constantᐸundefinedᐳ[6]<br />- Constantᐸundefinedᐳ[6]"]]:::plan
    PgClassExpression16{{"PgClassExpression[16∈2]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression16 --> PgSelect17
    PgClassExpression15{{"PgClassExpression[15∈2]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle14 --> PgClassExpression15
    PgSelectSingle14 --> PgClassExpression16
    PgSelectRows21[["PgSelectRows[21∈2]"]]:::plan
    PgSelect17 --> PgSelectRows21
    PgSelect126[["PgSelect[126∈3]<br />ᐸpeopleᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression125{{"PgClassExpression[125∈3]<br />ᐸ__relation...author_id”ᐳ"}}:::plan
    PgClassExpression125 --> PgSelect126
    __Item23[/"__Item[23∈3]<br />ᐸ21ᐳ"\]:::itemplan
    PgSelectRows21 ==> __Item23
    PgSelectSingle24{{"PgSelectSingle[24∈3]<br />ᐸrelational_itemsᐳ"}}:::plan
    __Item23 --> PgSelectSingle24
    PgClassExpression25{{"PgClassExpression[25∈3]<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle24 --> PgClassExpression25
    PgClassExpression28{{"PgClassExpression[28∈3]<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle24 --> PgClassExpression28
    Lambda29{{"Lambda[29∈3]<br />ᐸrelationalItemTypeNameFromTypeᐳ"}}:::plan
    PgClassExpression28 --> Lambda29
    PgClassExpression120{{"PgClassExpression[120∈3]<br />ᐸ__relation...__.”type2”ᐳ"}}:::plan
    PgSelectSingle24 --> PgClassExpression120
    PgSelectSingle24 --> PgClassExpression125
    First128{{"First[128∈3]"}}:::plan
    PgSelectRows129[["PgSelectRows[129∈3]"]]:::plan
    PgSelectRows129 --> First128
    PgSelect126 --> PgSelectRows129
    PgSelectSingle130{{"PgSelectSingle[130∈3]<br />ᐸpeopleᐳ"}}:::plan
    First128 --> PgSelectSingle130
    PgClassExpression155{{"PgClassExpression[155∈3]<br />ᐸ__relation...”position”ᐳ"}}:::plan
    PgClassExpression120 o--o PgClassExpression155
    PgClassExpression160{{"PgClassExpression[160∈3]<br />ᐸ__relation...reated_at”ᐳ"}}:::plan
    PgClassExpression155 o--o PgClassExpression160
    PgClassExpression165{{"PgClassExpression[165∈3]<br />ᐸ__relation...pdated_at”ᐳ"}}:::plan
    PgClassExpression160 o--o PgClassExpression165
    PgClassExpression170{{"PgClassExpression[170∈3]<br />ᐸ__relation..._archived”ᐳ"}}:::plan
    PgClassExpression165 o--o PgClassExpression170
    PgClassExpression175{{"PgClassExpression[175∈3]<br />ᐸ__relation...chived_at”ᐳ"}}:::plan
    PgClassExpression170 o--o PgClassExpression175
    PgSelect31[["PgSelect[31∈5]<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression25 --> PgSelect31
    First35{{"First[35∈5]^"}}:::plan
    PgSelectRows36[["PgSelectRows[36∈5]^"]]:::plan
    PgSelectRows36 --> First35
    PgSelect31 --> PgSelectRows36
    PgSelectSingle37{{"PgSelectSingle[37∈5]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First35 --> PgSelectSingle37
    PgClassExpression180{{"PgClassExpression[180∈5]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle37 --> PgClassExpression180
    PgSelect39[["PgSelect[39∈6]<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression25 --> PgSelect39
    First43{{"First[43∈6]^"}}:::plan
    PgSelectRows44[["PgSelectRows[44∈6]^"]]:::plan
    PgSelectRows44 --> First43
    PgSelect39 --> PgSelectRows44
    PgSelectSingle45{{"PgSelectSingle[45∈6]^<br />ᐸrelational_postsᐳ"}}:::plan
    First43 --> PgSelectSingle45
    PgClassExpression181{{"PgClassExpression[181∈6]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression181
    PgClassExpression185{{"PgClassExpression[185∈6]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression181 o--o PgClassExpression185
    PgClassExpression188{{"PgClassExpression[188∈6]^<br />ᐸ__relation...s__.”note”ᐳ"}}:::plan
    PgClassExpression185 o--o PgClassExpression188
    PgSelect47[["PgSelect[47∈7]<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression25 --> PgSelect47
    First51{{"First[51∈7]^"}}:::plan
    PgSelectRows52[["PgSelectRows[52∈7]^"]]:::plan
    PgSelectRows52 --> First51
    PgSelect47 --> PgSelectRows52
    PgSelectSingle53{{"PgSelectSingle[53∈7]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First51 --> PgSelectSingle53
    PgClassExpression182{{"PgClassExpression[182∈7]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle53 --> PgClassExpression182
    PgClassExpression186{{"PgClassExpression[186∈7]^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgClassExpression182 o--o PgClassExpression186
    PgSelect55[["PgSelect[55∈8]<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression25 --> PgSelect55
    First59{{"First[59∈8]^"}}:::plan
    PgSelectRows60[["PgSelectRows[60∈8]^"]]:::plan
    PgSelectRows60 --> First59
    PgSelect55 --> PgSelectRows60
    PgSelectSingle61{{"PgSelectSingle[61∈8]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First59 --> PgSelectSingle61
    PgClassExpression183{{"PgClassExpression[183∈8]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle61 --> PgClassExpression183
    PgSelect63[["PgSelect[63∈9]<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression25 --> PgSelect63
    First67{{"First[67∈9]^"}}:::plan
    PgSelectRows68[["PgSelectRows[68∈9]^"]]:::plan
    PgSelectRows68 --> First67
    PgSelect63 --> PgSelectRows68
    PgSelectSingle69{{"PgSelectSingle[69∈9]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First67 --> PgSelectSingle69
    PgClassExpression184{{"PgClassExpression[184∈9]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle69 --> PgClassExpression184
    PgClassExpression187{{"PgClassExpression[187∈9]^<br />ᐸ__relation...s__.”note”ᐳ"}}:::plan
    PgClassExpression184 o--o PgClassExpression187
    PgClassExpression234{{"PgClassExpression[234∈10]<br />ᐸ__people__.”username”ᐳ<br />ᐳRelationalTopic"}}:::plan
    PgSelectSingle130 --> PgClassExpression234
    PgClassExpression235{{"PgClassExpression[235∈11]<br />ᐸ__people__.”username”ᐳ<br />ᐳRelationalPost"}}:::plan
    PgClassExpression234 o--o PgClassExpression235
    PgClassExpression236{{"PgClassExpression[236∈12]<br />ᐸ__people__.”username”ᐳ<br />ᐳRelationalDivider"}}:::plan
    PgClassExpression235 o--o PgClassExpression236
    PgClassExpression237{{"PgClassExpression[237∈13]<br />ᐸ__people__.”username”ᐳ<br />ᐳRelationalChecklist"}}:::plan
    PgClassExpression236 o--o PgClassExpression237
    PgClassExpression238{{"PgClassExpression[238∈14]<br />ᐸ__people__.”username”ᐳ<br />ᐳRelationalChecklistItem"}}:::plan
    PgClassExpression237 o--o PgClassExpression238
    PgSelect71[["PgSelect[71∈15]<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression70{{"PgClassExpression[70∈15]<br />ᐸ__relation...parent_id”ᐳ"}}:::plan
    PgClassExpression70 --> PgSelect71
    PgSelect255[["PgSelect[255∈15]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression254{{"PgClassExpression[254∈15]<br />ᐸ__relation...author_id”ᐳ<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}}:::plan
    PgClassExpression254 --> PgSelect255
    PgSelectSingle24 --> PgClassExpression70
    First75{{"First[75∈15]"}}:::plan
    PgSelectRows76[["PgSelectRows[76∈15]"]]:::plan
    PgSelectRows76 --> First75
    PgSelect71 --> PgSelectRows76
    PgSelectSingle77{{"PgSelectSingle[77∈15]<br />ᐸrelational_itemsᐳ"}}:::plan
    First75 --> PgSelectSingle77
    PgClassExpression189{{"PgClassExpression[189∈15]<br />ᐸ__relation...ems__.”id”ᐳ<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}}:::plan
    PgSelectSingle77 --> PgClassExpression189
    PgClassExpression192{{"PgClassExpression[192∈15]<br />ᐸ__relation...s__.”type”ᐳ<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}}:::plan
    PgSelectSingle77 --> PgClassExpression192
    Lambda193{{"Lambda[193∈15]^<br />ᐸrelationalItemTypeNameFromTypeᐳ"}}:::plan
    PgClassExpression192 --> Lambda193
    PgClassExpression249{{"PgClassExpression[249∈15]<br />ᐸ__relation...__.”type2”ᐳ<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}}:::plan
    PgSelectSingle77 --> PgClassExpression249
    PgSelectSingle77 --> PgClassExpression254
    First259{{"First[259∈15]^"}}:::plan
    PgSelectRows260[["PgSelectRows[260∈15]^"]]:::plan
    PgSelectRows260 --> First259
    PgSelect255 --> PgSelectRows260
    PgSelectSingle261{{"PgSelectSingle[261∈15]^<br />ᐸpeopleᐳ"}}:::plan
    First259 --> PgSelectSingle261
    PgClassExpression294{{"PgClassExpression[294∈15]<br />ᐸ__relation...”position”ᐳ<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}}:::plan
    PgClassExpression249 o--o PgClassExpression294
    PgClassExpression299{{"PgClassExpression[299∈15]<br />ᐸ__relation...reated_at”ᐳ<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}}:::plan
    PgClassExpression294 o--o PgClassExpression299
    PgClassExpression304{{"PgClassExpression[304∈15]<br />ᐸ__relation...pdated_at”ᐳ<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}}:::plan
    PgClassExpression299 o--o PgClassExpression304
    PgClassExpression309{{"PgClassExpression[309∈15]<br />ᐸ__relation..._archived”ᐳ<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}}:::plan
    PgClassExpression304 o--o PgClassExpression309
    PgClassExpression314{{"PgClassExpression[314∈15]<br />ᐸ__relation...chived_at”ᐳ<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}}:::plan
    PgClassExpression309 o--o PgClassExpression314
    PgSelect195[["PgSelect[195∈17]<br />ᐸrelational_topicsᐳ<br />(5) ...ᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression189 --> PgSelect195
    First199{{"First[199∈17]^"}}:::plan
    PgSelectRows200[["PgSelectRows[200∈17]^"]]:::plan
    PgSelectRows200 --> First199
    PgSelect195 --> PgSelectRows200
    PgSelectSingle201{{"PgSelectSingle[201∈17]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First199 --> PgSelectSingle201
    PgClassExpression319{{"PgClassExpression[319∈17]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle201 --> PgClassExpression319
    PgSelect203[["PgSelect[203∈18]<br />ᐸrelational_postsᐳ<br />(5) ...ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression189 --> PgSelect203
    First207{{"First[207∈18]^"}}:::plan
    PgSelectRows208[["PgSelectRows[208∈18]^"]]:::plan
    PgSelectRows208 --> First207
    PgSelect203 --> PgSelectRows208
    PgSelectSingle209{{"PgSelectSingle[209∈18]^<br />ᐸrelational_postsᐳ"}}:::plan
    First207 --> PgSelectSingle209
    PgClassExpression320{{"PgClassExpression[320∈18]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle209 --> PgClassExpression320
    PgClassExpression324{{"PgClassExpression[324∈18]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression320 o--o PgClassExpression324
    PgClassExpression327{{"PgClassExpression[327∈18]^<br />ᐸ__relation...s__.”note”ᐳ"}}:::plan
    PgClassExpression324 o--o PgClassExpression327
    PgSelect211[["PgSelect[211∈19]<br />ᐸrelational_dividersᐳ<br />(5) ...ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression189 --> PgSelect211
    First215{{"First[215∈19]^"}}:::plan
    PgSelectRows216[["PgSelectRows[216∈19]^"]]:::plan
    PgSelectRows216 --> First215
    PgSelect211 --> PgSelectRows216
    PgSelectSingle217{{"PgSelectSingle[217∈19]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First215 --> PgSelectSingle217
    PgClassExpression321{{"PgClassExpression[321∈19]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle217 --> PgClassExpression321
    PgClassExpression325{{"PgClassExpression[325∈19]^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgClassExpression321 o--o PgClassExpression325
    PgSelect219[["PgSelect[219∈20]<br />ᐸrelational_checklistsᐳ<br />(5) ...ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression189 --> PgSelect219
    First223{{"First[223∈20]^"}}:::plan
    PgSelectRows224[["PgSelectRows[224∈20]^"]]:::plan
    PgSelectRows224 --> First223
    PgSelect219 --> PgSelectRows224
    PgSelectSingle225{{"PgSelectSingle[225∈20]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First223 --> PgSelectSingle225
    PgClassExpression322{{"PgClassExpression[322∈20]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle225 --> PgClassExpression322
    PgSelect227[["PgSelect[227∈21]<br />ᐸrelational_checklist_itemsᐳ<br />(5) ...ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression189 --> PgSelect227
    First231{{"First[231∈21]^"}}:::plan
    PgSelectRows232[["PgSelectRows[232∈21]^"]]:::plan
    PgSelectRows232 --> First231
    PgSelect227 --> PgSelectRows232
    PgSelectSingle233{{"PgSelectSingle[233∈21]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First231 --> PgSelectSingle233
    PgClassExpression323{{"PgClassExpression[323∈21]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle233 --> PgClassExpression323
    PgClassExpression326{{"PgClassExpression[326∈21]^<br />ᐸ__relation...s__.”note”ᐳ"}}:::plan
    PgClassExpression323 o--o PgClassExpression326
    PgClassExpression328{{"PgClassExpression[328∈22]<br />ᐸ__people__.”username”ᐳ<br />(5) ...ᐳRelationalTopic"}}:::plan
    PgSelectSingle261 --> PgClassExpression328
    PgClassExpression329{{"PgClassExpression[329∈23]<br />ᐸ__people__.”username”ᐳ<br />(5) ...ᐳRelationalPost"}}:::plan
    PgClassExpression328 o--o PgClassExpression329
    PgClassExpression330{{"PgClassExpression[330∈24]<br />ᐸ__people__.”username”ᐳ<br />(5) ...ᐳRelationalDivider"}}:::plan
    PgClassExpression329 o--o PgClassExpression330
    PgClassExpression331{{"PgClassExpression[331∈25]<br />ᐸ__people__.”username”ᐳ<br />(5) ...ᐳRelationalChecklist"}}:::plan
    PgClassExpression330 o--o PgClassExpression331
    PgClassExpression332{{"PgClassExpression[332∈26]<br />ᐸ__people__.”username”ᐳ<br />(5) ...ᐳRelationalChecklistItem"}}:::plan
    PgClassExpression331 o--o PgClassExpression332

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect7,Access8,Access9,Object10,PgSelectRows11 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item13,PgSelectSingle14 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression15,PgClassExpression16,PgSelect17,PgSelectRows21 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item23,PgSelectSingle24,PgClassExpression25,PgClassExpression28,Lambda29,PgClassExpression120,PgClassExpression125,PgSelect126,First128,PgSelectRows129,PgSelectSingle130,PgClassExpression155,PgClassExpression160,PgClassExpression165,PgClassExpression170,PgClassExpression175 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgSelect31,First35,PgSelectRows36,PgSelectSingle37,PgClassExpression180 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgSelect39,First43,PgSelectRows44,PgSelectSingle45,PgClassExpression181,PgClassExpression185,PgClassExpression188 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,PgSelect47,First51,PgSelectRows52,PgSelectSingle53,PgClassExpression182,PgClassExpression186 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgSelect55,First59,PgSelectRows60,PgSelectSingle61,PgClassExpression183 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgSelect63,First67,PgSelectRows68,PgSelectSingle69,PgClassExpression184,PgClassExpression187 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgClassExpression234 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11,PgClassExpression235 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgClassExpression236 bucket12
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgClassExpression237 bucket13
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgClassExpression238 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgClassExpression70,PgSelect71,First75,PgSelectRows76,PgSelectSingle77,PgClassExpression189,PgClassExpression192,Lambda193,PgClassExpression249,PgClassExpression254,PgSelect255,First259,PgSelectRows260,PgSelectSingle261,PgClassExpression294,PgClassExpression299,PgClassExpression304,PgClassExpression309,PgClassExpression314 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16 bucket16
    classDef bucket17 stroke:#696969
    class Bucket17,PgSelect195,First199,PgSelectRows200,PgSelectSingle201,PgClassExpression319 bucket17
    classDef bucket18 stroke:#00bfff
    class Bucket18,PgSelect203,First207,PgSelectRows208,PgSelectSingle209,PgClassExpression320,PgClassExpression324,PgClassExpression327 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19,PgSelect211,First215,PgSelectRows216,PgSelectSingle217,PgClassExpression321,PgClassExpression325 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20,PgSelect219,First223,PgSelectRows224,PgSelectSingle225,PgClassExpression322 bucket20
    classDef bucket21 stroke:#0000ff
    class Bucket21,PgSelect227,First231,PgSelectRows232,PgSelectSingle233,PgClassExpression323,PgClassExpression326 bucket21
    classDef bucket22 stroke:#7fff00
    class Bucket22,PgClassExpression328 bucket22
    classDef bucket23 stroke:#ff1493
    class Bucket23,PgClassExpression329 bucket23
    classDef bucket24 stroke:#808000
    class Bucket24,PgClassExpression330 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25,PgClassExpression331 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,PgClassExpression332 bucket26

