%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/polymorphic/person-app-vulns"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 10, 11, 43, 128, 133, 178, 183, 228, 233, 267, 12<br />2: PgSelect[9]<br />3: Connection[13]<br />4: ConnectionItems[15]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 13, 15, 12, 43, 128, 133, 178, 183, 228, 233<br /><br />ROOT Connectionᐸ9ᐳ[13]"):::bucket
    Bucket3("Bucket 3 (listItem)<br />Deps: 12, 43, 128, 133, 178, 183, 228, 233<br /><br />ROOT __Item{3}ᐸ15ᐳ[19]"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 20, 12, 43, 128, 133, 178, 183, 228, 233<br /><br />ROOT PgSelectSingle{3}ᐸpeopleᐳ[20]<br />1: <br />ᐳ: 21, 22<br />2: PgUnionAll[23], PgUnionAll[28]<br />ᐳ: 266, 29, 32<br />3: Connection[27]<br />4: ConnectionItems[33]"):::bucket
    Bucket7("Bucket 7 (listItem)<br />Deps: 43, 23, 12, 128, 133, 178, 183, 228, 233<br /><br />ROOT __Item{7}ᐸ33ᐳ[38]"):::bucket
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 45, 39, 12, 108, 65<br /><br />ROOT Edge{7}[39]"):::bucket
    Bucket9("Bucket 9 (polymorphic)<br />__typename: Access[47]<br />Deps: 47, 12, 48, 128, 133, 178, 183, 228, 233"):::bucket
    Bucket10("Bucket 10 (polymorphicPartition)<br />|AwsApplication<br />Deps: 12, 48, 128, 178, 228<br />ᐳAwsApplication<br /><br />1: PgSelect[49]<br />2: PgSelectRows[54]<br />ᐳ: 53, 55, 67, 69, 71, 73, 74<br />3: 75, 91, 95, 160<br />ᐳ: 260, 261, 262, 79, 126, 127, 129, 130, 161, 164<br />4: Connection[97]<br />5: ConnectionItems[170]"):::bucket
    Bucket11("Bucket 11 (polymorphicPartition)<br />|GcpApplication<br />Deps: 12, 48, 133, 183, 233<br />ᐳGcpApplication<br /><br />1: PgSelect[57]<br />2: PgSelectRows[62]<br />ᐳ: 61, 63, 68, 70, 72, 82, 83<br />3: 84, 93, 98, 165<br />ᐳ: 263, 264, 265, 88, 131, 132, 134, 135, 166, 169<br />4: Connection[100]<br />5: ConnectionItems[173]"):::bucket
    Bucket12("Bucket 12 (polymorphic)<br />__typename: Access[107]<br />Deps: 107, 12, 108"):::bucket
    Bucket13("Bucket 13 (polymorphicPartition)<br />|AwsApplication<br />Deps: 12, 108<br />ᐳAwsApplication<br /><br />1: PgSelect[109]<br />2: PgSelectRows[114]<br />ᐳ: 113, 115, 158"):::bucket
    Bucket14("Bucket 14 (polymorphicPartition)<br />|GcpApplication<br />Deps: 12, 108<br />ᐳGcpApplication<br /><br />1: PgSelect[117]<br />2: PgSelectRows[122]<br />ᐳ: 121, 123, 159"):::bucket
    Bucket15("Bucket 15 (combined)<br />Deps: 12"):::bucket
    Bucket16("Bucket 16 (polymorphic)<br />__typename: Access[137]<br />Deps: 137, 136, 12"):::bucket
    Bucket17("Bucket 17 (listItem)<br />Deps: 178, 12<br /><br />ROOT __Item{17}ᐸ260ᐳ[154]"):::bucket
    Bucket18("Bucket 18 (listItem)<br />Deps: 183, 12<br /><br />ROOT __Item{18}ᐸ263ᐳ[156]"):::bucket
    Bucket19("Bucket 19 (polymorphicPartition)<br />|Organization<br />Deps: 136, 12<br />(2) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[138]<br />2: PgSelect[139]<br />3: PgSelectRows[144]<br />ᐳ: 143, 145, 204, 206"):::bucket
    Bucket20("Bucket 20 (polymorphicPartition)<br />|Person<br />Deps: 136, 12<br />(2) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[146]<br />2: PgSelect[147]<br />3: PgSelectRows[152]<br />ᐳ: 151, 153, 205, 207"):::bucket
    Bucket23("Bucket 23 (combined)<br />Deps: 12"):::bucket
    Bucket24("Bucket 24 (polymorphic)<br />__typename: Access[187]<br />Deps: 187, 12, 188"):::bucket
    Bucket25("Bucket 25 (polymorphicPartition)<br />|FirstPartyVulnerability<br />Deps: 12, 188<br />(2) ...ᐳFirstPartyVulnerability<br /><br />1: PgSelect[189]<br />2: PgSelectRows[194]<br />ᐳ: 193, 195, 212, 214, 216, 218"):::bucket
    Bucket26("Bucket 26 (polymorphicPartition)<br />|ThirdPartyVulnerability<br />Deps: 12, 188<br />(2) ...ᐳThirdPartyVulnerability<br /><br />1: PgSelect[197]<br />2: PgSelectRows[202]<br />ᐳ: 201, 203, 213, 215, 217, 219"):::bucket
    Bucket27("Bucket 27 (listItem)<br />Deps: 95, 228, 12<br /><br />ROOT __Item{27}ᐸ170ᐳ[208]"):::bucket
    Bucket28("Bucket 28 (listItem)<br />Deps: 98, 233, 12<br /><br />ROOT __Item{28}ᐸ173ᐳ[210]"):::bucket
    Bucket29("Bucket 29 (nullableBoundary)<br />Deps: 208, 228, 209, 12, 221<br /><br />ROOT Edge{27}[209]"):::bucket
    Bucket30("Bucket 30 (nullableBoundary)<br />Deps: 210, 233, 211, 12, 223<br /><br />ROOT Edge{28}[211]"):::bucket
    Bucket31("Bucket 31 (combined)<br />Deps: 12"):::bucket
    Bucket32("Bucket 32 (polymorphic)<br />__typename: Access[237]<br />Deps: 237, 12, 238"):::bucket
    Bucket33("Bucket 33 (polymorphicPartition)<br />|FirstPartyVulnerability<br />Deps: 12, 238<br />(2) ...ᐳFirstPartyVulnerability<br /><br />1: PgSelect[239]<br />2: PgSelectRows[244]<br />ᐳ: 243, 245, 254, 256, 258"):::bucket
    Bucket34("Bucket 34 (polymorphicPartition)<br />|ThirdPartyVulnerability<br />Deps: 12, 238<br />(2) ...ᐳThirdPartyVulnerability<br /><br />1: PgSelect[247]<br />2: PgSelectRows[252]<br />ᐳ: 251, 253, 255, 257, 259"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket7
    Bucket7 --> Bucket8 & Bucket9
    Bucket8 --> Bucket12
    Bucket9 --> Bucket10 & Bucket11
    Bucket10 --> Bucket15 & Bucket17 & Bucket27
    Bucket11 --> Bucket15 & Bucket18 & Bucket28
    Bucket12 --> Bucket13 & Bucket14
    Bucket15 --> Bucket16
    Bucket16 --> Bucket19 & Bucket20
    Bucket17 --> Bucket23
    Bucket18 --> Bucket23
    Bucket23 --> Bucket24
    Bucket24 --> Bucket25 & Bucket26
    Bucket27 --> Bucket29
    Bucket28 --> Bucket30
    Bucket29 --> Bucket31
    Bucket30 --> Bucket31
    Bucket31 --> Bucket32
    Bucket32 --> Bucket33 & Bucket34

    %% plan dependencies
    PgSelect9[["PgSelect[9∈0] ➊<br />ᐸpeopleᐳ<br />More deps:<br />- Object[12]<br />- Constantᐸ4ᐳ[267]"]]:::plan
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ<br />Dependents: 21"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    Connection13[["Connection[13∈0] ➊<br />ᐸ9ᐳ<br />More deps:<br />- Constantᐸ4ᐳ[267]"]]:::plan
    PgSelect9 --> Connection13
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    ConnectionItems15[["ConnectionItems[15∈0] ➊"]]:::plan
    Connection13 --> ConnectionItems15
    __Item19[/"__Item[19∈3]<br />ᐸ15ᐳ"\]:::itemplan
    ConnectionItems15 ==> __Item19
    PgSelectSingle20{{"PgSelectSingle[20∈3]<br />ᐸpeopleᐳ"}}:::plan
    __Item19 --> PgSelectSingle20
    PgUnionAll23[["PgUnionAll[23∈4]<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[12]"]]:::plan
    PgClassExpression21{{"PgClassExpression[21∈4]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression21 --> PgUnionAll23
    PgUnionAll28[["PgUnionAll[28∈4]<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[12]"]]:::plan
    PgClassExpression21 --> PgUnionAll28
    PgSelectSingle20 --> PgClassExpression21
    PgClassExpression22{{"PgClassExpression[22∈4]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle20 --> PgClassExpression22
    Connection27[["Connection[27∈4]<br />ᐸ23ᐳ"]]:::plan
    PgUnionAll23 --> Connection27
    First29{{"First[29∈4]"}}:::plan
    Access266{{"Access[266∈4]<br />ᐸ28.itemsᐳ"}}:::plan
    Access266 --> First29
    PgClassExpression32{{"PgClassExpression[32∈4]<br />ᐸcount(*)ᐳ"}}:::plan
    First29 --> PgClassExpression32
    ConnectionItems33[["ConnectionItems[33∈4]"]]:::plan
    Connection27 --> ConnectionItems33
    PgUnionAll28 --> Access266
    List44{{"List[44∈7]<br />ᐸ41,42,43ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[43]"}}:::plan
    Access41{{"Access[41∈7]<br />ᐸ38.0ᐳ"}}:::plan
    Access42{{"Access[42∈7]<br />ᐸ38.1ᐳ"}}:::plan
    Access41 & Access42 --> List44
    Edge39{{"Edge[39∈7]"}}:::plan
    __Item38[/"__Item[38∈7]<br />ᐸ33ᐳ"\]:::itemplan
    PgCursor65{{"PgCursor[65∈7]"}}:::plan
    __Item38 & PgCursor65 --> Edge39
    Access64{{"Access[64∈7]<br />ᐸ23.cursorDetailsᐳ"}}:::plan
    __Item38 & Access64 --> PgCursor65
    ConnectionItems33 ==> __Item38
    __Item38 --> Access41
    __Item38 --> Access42
    Lambda45{{"Lambda[45∈7]<br />ᐸtoSpecifierᐳ"}}:::plan
    List44 --> Lambda45
    Access47{{"Access[47∈7]<br />ᐸ45.__typenameᐳ"}}:::plan
    Lambda45 -->|rejectNull| Access47
    Access48{{"Access[48∈7]<br />ᐸ45.idᐳ"}}:::plan
    Lambda45 -->|rejectNull| Access48
    PgUnionAll23 --> Access64
    Access108{{"Access[108∈7]<br />ᐸ45.idᐳ"}}:::plan
    Lambda45 -->|rejectNull| Access108
    Access107{{"Access[107∈8]<br />ᐸ45.__typenameᐳ"}}:::plan
    Access47 o--o|rejectNull| Access107
    PgUnionAll75[["PgUnionAll[75∈10]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[12]"]]:::plan
    PgClassExpression73{{"PgClassExpression[73∈10]^<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression74{{"PgClassExpression[74∈10]^<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression73 & PgClassExpression74 --> PgUnionAll75
    List129{{"List[129∈10]^<br />ᐸ126,127,128ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[128]"}}:::plan
    Access126{{"Access[126∈10]^<br />ᐸ79.0ᐳ"}}:::plan
    Access127{{"Access[127∈10]^<br />ᐸ79.1ᐳ"}}:::plan
    Access126 & Access127 --> List129
    PgSelect49[["PgSelect[49∈10]<br />ᐸaws_applicationsᐳ<br />ᐳAwsApplication<br />More deps:<br />- Object[12]"]]:::plan
    Access48 --> PgSelect49
    PgUnionAll91[["PgUnionAll[91∈10]^<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />More deps:<br />- Object[12]"]]:::plan
    PgClassExpression69{{"PgClassExpression[69∈10]^<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression69 --> PgUnionAll91
    PgUnionAll95[["PgUnionAll[95∈10]^<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />More deps:<br />- Object[12]"]]:::plan
    PgClassExpression69 --> PgUnionAll95
    PgUnionAll160[["PgUnionAll[160∈10]^<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />More deps:<br />- Object[12]"]]:::plan
    PgClassExpression69 --> PgUnionAll160
    First53{{"First[53∈10]^"}}:::plan
    PgSelectRows54[["PgSelectRows[54∈10]^"]]:::plan
    PgSelectRows54 --> First53
    PgSelect49 --> PgSelectRows54
    PgSelectSingle55{{"PgSelectSingle[55∈10]^<br />ᐸaws_applicationsᐳ"}}:::plan
    First53 --> PgSelectSingle55
    PgClassExpression67{{"PgClassExpression[67∈10]^<br />ᐸ__aws_appl..._.”aws_id”ᐳ"}}:::plan
    PgSelectSingle55 --> PgClassExpression67
    PgSelectSingle55 --> PgClassExpression69
    PgClassExpression71{{"PgClassExpression[71∈10]^<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgClassExpression67 o--o PgClassExpression71
    PgSelectSingle55 --> PgClassExpression73
    PgSelectSingle55 --> PgClassExpression74
    First79{{"First[79∈10]^"}}:::plan
    Access262{{"Access[262∈10]^<br />ᐸ75.itemsᐳ"}}:::plan
    Access262 --> First79
    Connection97[["Connection[97∈10]^<br />ᐸ95ᐳ"]]:::plan
    PgUnionAll95 --> Connection97
    First79 --> Access126
    First79 --> Access127
    Lambda130{{"Lambda[130∈10]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List129 --> Lambda130
    First161{{"First[161∈10]^"}}:::plan
    Access261{{"Access[261∈10]^<br />ᐸ160.itemsᐳ"}}:::plan
    Access261 --> First161
    PgClassExpression164{{"PgClassExpression[164∈10]^<br />ᐸcount(*)ᐳ"}}:::plan
    First161 --> PgClassExpression164
    ConnectionItems170[["ConnectionItems[170∈10]^"]]:::plan
    Connection97 --> ConnectionItems170
    Access260{{"Access[260∈10]^<br />ᐸ91.itemsᐳ"}}:::plan
    PgUnionAll91 --> Access260
    PgUnionAll160 --> Access261
    PgUnionAll75 --> Access262
    PgUnionAll84[["PgUnionAll[84∈11]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[12]"]]:::plan
    PgClassExpression82{{"PgClassExpression[82∈11]^<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression83{{"PgClassExpression[83∈11]^<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression82 & PgClassExpression83 --> PgUnionAll84
    List134{{"List[134∈11]^<br />ᐸ131,132,133ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[133]"}}:::plan
    Access131{{"Access[131∈11]^<br />ᐸ88.0ᐳ"}}:::plan
    Access132{{"Access[132∈11]^<br />ᐸ88.1ᐳ"}}:::plan
    Access131 & Access132 --> List134
    PgSelect57[["PgSelect[57∈11]<br />ᐸgcp_applicationsᐳ<br />ᐳGcpApplication<br />More deps:<br />- Object[12]"]]:::plan
    Access48 --> PgSelect57
    PgUnionAll93[["PgUnionAll[93∈11]^<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />More deps:<br />- Object[12]"]]:::plan
    PgClassExpression70{{"PgClassExpression[70∈11]^<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression70 --> PgUnionAll93
    PgUnionAll98[["PgUnionAll[98∈11]^<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />More deps:<br />- Object[12]"]]:::plan
    PgClassExpression70 --> PgUnionAll98
    PgUnionAll165[["PgUnionAll[165∈11]^<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />More deps:<br />- Object[12]"]]:::plan
    PgClassExpression70 --> PgUnionAll165
    First61{{"First[61∈11]^"}}:::plan
    PgSelectRows62[["PgSelectRows[62∈11]^"]]:::plan
    PgSelectRows62 --> First61
    PgSelect57 --> PgSelectRows62
    PgSelectSingle63{{"PgSelectSingle[63∈11]^<br />ᐸgcp_applicationsᐳ"}}:::plan
    First61 --> PgSelectSingle63
    PgClassExpression68{{"PgClassExpression[68∈11]^<br />ᐸ__gcp_appl..._.”gcp_id”ᐳ"}}:::plan
    PgSelectSingle63 --> PgClassExpression68
    PgSelectSingle63 --> PgClassExpression70
    PgClassExpression72{{"PgClassExpression[72∈11]^<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgClassExpression68 o--o PgClassExpression72
    PgSelectSingle63 --> PgClassExpression82
    PgSelectSingle63 --> PgClassExpression83
    First88{{"First[88∈11]^"}}:::plan
    Access265{{"Access[265∈11]^<br />ᐸ84.itemsᐳ"}}:::plan
    Access265 --> First88
    Connection100[["Connection[100∈11]^<br />ᐸ98ᐳ"]]:::plan
    PgUnionAll98 --> Connection100
    First88 --> Access131
    First88 --> Access132
    Lambda135{{"Lambda[135∈11]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List134 --> Lambda135
    First166{{"First[166∈11]^"}}:::plan
    Access264{{"Access[264∈11]^<br />ᐸ165.itemsᐳ"}}:::plan
    Access264 --> First166
    PgClassExpression169{{"PgClassExpression[169∈11]^<br />ᐸcount(*)ᐳ"}}:::plan
    First166 --> PgClassExpression169
    ConnectionItems173[["ConnectionItems[173∈11]^"]]:::plan
    Connection100 --> ConnectionItems173
    Access263{{"Access[263∈11]^<br />ᐸ93.itemsᐳ"}}:::plan
    PgUnionAll93 --> Access263
    PgUnionAll165 --> Access264
    PgUnionAll84 --> Access265
    PgSelect109[["PgSelect[109∈13]<br />ᐸaws_applicationsᐳ<br />ᐳAwsApplication<br />More deps:<br />- Object[12]"]]:::plan
    Access108 --> PgSelect109
    First113{{"First[113∈13]^"}}:::plan
    PgSelectRows114[["PgSelectRows[114∈13]^"]]:::plan
    PgSelectRows114 --> First113
    PgSelect109 --> PgSelectRows114
    PgSelectSingle115{{"PgSelectSingle[115∈13]^<br />ᐸaws_applicationsᐳ"}}:::plan
    First113 --> PgSelectSingle115
    PgClassExpression158{{"PgClassExpression[158∈13]^<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgSelectSingle115 --> PgClassExpression158
    PgSelect117[["PgSelect[117∈14]<br />ᐸgcp_applicationsᐳ<br />ᐳGcpApplication<br />More deps:<br />- Object[12]"]]:::plan
    Access108 --> PgSelect117
    First121{{"First[121∈14]^"}}:::plan
    PgSelectRows122[["PgSelectRows[122∈14]^"]]:::plan
    PgSelectRows122 --> First121
    PgSelect117 --> PgSelectRows122
    PgSelectSingle123{{"PgSelectSingle[123∈14]^<br />ᐸgcp_applicationsᐳ"}}:::plan
    First121 --> PgSelectSingle123
    PgClassExpression159{{"PgClassExpression[159∈14]^<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgSelectSingle123 --> PgClassExpression159
    Access137{{"Access[137∈15]^<br />ᐸ136.__typenameᐳ"}}:::plan
    __Value136:::plan@{shape: docs, label: "__Combined[136∈15]<br />ᐳAwsApplication<br />ᐳGcpApplication"}
    __Value136 --> Access137
    List179{{"List[179∈17]^<br />ᐸ176,177,178ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[178]"}}:::plan
    Access176{{"Access[176∈17]^<br />ᐸ154.0ᐳ"}}:::plan
    Access177{{"Access[177∈17]^<br />ᐸ154.1ᐳ"}}:::plan
    Access176 & Access177 --> List179
    __Item154[/"__Item[154∈17]<br />ᐸ260ᐳ<br />ᐳAwsApplication"\]:::itemplan
    Access260 ==> __Item154
    __Item154 --> Access176
    __Item154 --> Access177
    Lambda180{{"Lambda[180∈17]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List179 --> Lambda180
    List184{{"List[184∈18]^<br />ᐸ181,182,183ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[183]"}}:::plan
    Access181{{"Access[181∈18]^<br />ᐸ156.0ᐳ"}}:::plan
    Access182{{"Access[182∈18]^<br />ᐸ156.1ᐳ"}}:::plan
    Access181 & Access182 --> List184
    __Item156[/"__Item[156∈18]<br />ᐸ263ᐳ<br />ᐳGcpApplication"\]:::itemplan
    Access263 ==> __Item156
    __Item156 --> Access181
    __Item156 --> Access182
    Lambda185{{"Lambda[185∈18]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List184 --> Lambda185
    PgSelect139[["PgSelect[139∈19]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[12]"]]:::plan
    Access138{{"Access[138∈19]<br />ᐸ136.organization_idᐳ<br />(2) ...ᐳOrganization"}}:::plan
    Access138 --> PgSelect139
    __Value136 --> Access138
    First143{{"First[143∈19]^"}}:::plan
    PgSelectRows144[["PgSelectRows[144∈19]^"]]:::plan
    PgSelectRows144 --> First143
    PgSelect139 --> PgSelectRows144
    PgSelectSingle145{{"PgSelectSingle[145∈19]^<br />ᐸorganizationsᐳ"}}:::plan
    First143 --> PgSelectSingle145
    PgClassExpression204{{"PgClassExpression[204∈19]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgSelectSingle145 --> PgClassExpression204
    PgClassExpression206{{"PgClassExpression[206∈19]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgClassExpression204 o--o PgClassExpression206
    PgSelect147[["PgSelect[147∈20]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[12]"]]:::plan
    Access146{{"Access[146∈20]<br />ᐸ136.person_idᐳ<br />(2) ...ᐳPerson"}}:::plan
    Access146 --> PgSelect147
    __Value136 --> Access146
    First151{{"First[151∈20]^"}}:::plan
    PgSelectRows152[["PgSelectRows[152∈20]^"]]:::plan
    PgSelectRows152 --> First151
    PgSelect147 --> PgSelectRows152
    PgSelectSingle153{{"PgSelectSingle[153∈20]^<br />ᐸpeopleᐳ"}}:::plan
    First151 --> PgSelectSingle153
    PgClassExpression205{{"PgClassExpression[205∈20]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgSelectSingle153 --> PgClassExpression205
    PgClassExpression207{{"PgClassExpression[207∈20]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgClassExpression205 o--o PgClassExpression207
    Access187{{"Access[187∈23]^<br />ᐸ186.__typenameᐳ"}}:::plan
    __Value186:::plan@{shape: docs, label: "__Combined[186∈23]<br />ᐳAwsApplication<br />ᐳGcpApplication"}
    __Value186 --> Access187
    Access188{{"Access[188∈23]^<br />ᐸ186.idᐳ"}}:::plan
    __Value186 --> Access188
    PgSelect189[["PgSelect[189∈25]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />(2) ...ᐳFirstPartyVulnerability<br />More deps:<br />- Object[12]"]]:::plan
    Access188 --> PgSelect189
    First193{{"First[193∈25]^"}}:::plan
    PgSelectRows194[["PgSelectRows[194∈25]^"]]:::plan
    PgSelectRows194 --> First193
    PgSelect189 --> PgSelectRows194
    PgSelectSingle195{{"PgSelectSingle[195∈25]^<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First193 --> PgSelectSingle195
    PgClassExpression212{{"PgClassExpression[212∈25]^<br />ᐸ__first_pa...team_name”ᐳ"}}:::plan
    PgSelectSingle195 --> PgClassExpression212
    PgClassExpression214{{"PgClassExpression[214∈25]^<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgClassExpression212 o--o PgClassExpression214
    PgClassExpression216{{"PgClassExpression[216∈25]^<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgClassExpression214 o--o PgClassExpression216
    PgClassExpression218{{"PgClassExpression[218∈25]^<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgClassExpression216 o--o PgClassExpression218
    PgSelect197[["PgSelect[197∈26]<br />ᐸthird_party_vulnerabilitiesᐳ<br />(2) ...ᐳThirdPartyVulnerability<br />More deps:<br />- Object[12]"]]:::plan
    Access188 --> PgSelect197
    First201{{"First[201∈26]^"}}:::plan
    PgSelectRows202[["PgSelectRows[202∈26]^"]]:::plan
    PgSelectRows202 --> First201
    PgSelect197 --> PgSelectRows202
    PgSelectSingle203{{"PgSelectSingle[203∈26]^<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First201 --> PgSelectSingle203
    PgClassExpression213{{"PgClassExpression[213∈26]^<br />ᐸ__third_pa...ndor_name”ᐳ"}}:::plan
    PgSelectSingle203 --> PgClassExpression213
    PgClassExpression215{{"PgClassExpression[215∈26]^<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgClassExpression213 o--o PgClassExpression215
    PgClassExpression217{{"PgClassExpression[217∈26]^<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgClassExpression215 o--o PgClassExpression217
    PgClassExpression219{{"PgClassExpression[219∈26]^<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgClassExpression217 o--o PgClassExpression219
    Edge209{{"Edge[209∈27]^"}}:::plan
    __Item208[/"__Item[208∈27]<br />ᐸ170ᐳ<br />ᐳAwsApplication"\]:::itemplan
    PgCursor221{{"PgCursor[221∈27]^"}}:::plan
    __Item208 & PgCursor221 --> Edge209
    Access220{{"Access[220∈27]<br />ᐸ95.cursorDetailsᐳ<br />ᐳAwsApplication"}}:::plan
    __Item208 & Access220 --> PgCursor221
    ConnectionItems170 ==> __Item208
    PgUnionAll95 --> Access220
    Edge211{{"Edge[211∈28]^"}}:::plan
    __Item210[/"__Item[210∈28]<br />ᐸ173ᐳ<br />ᐳGcpApplication"\]:::itemplan
    PgCursor223{{"PgCursor[223∈28]^"}}:::plan
    __Item210 & PgCursor223 --> Edge211
    Access222{{"Access[222∈28]<br />ᐸ98.cursorDetailsᐳ<br />ᐳGcpApplication"}}:::plan
    __Item210 & Access222 --> PgCursor223
    ConnectionItems173 ==> __Item210
    PgUnionAll98 --> Access222
    List229{{"List[229∈29]^<br />ᐸ226,227,228ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[228]"}}:::plan
    Access226{{"Access[226∈29]<br />ᐸ208.0ᐳ<br />ᐳAwsApplication"}}:::plan
    Access227{{"Access[227∈29]<br />ᐸ208.1ᐳ<br />ᐳAwsApplication"}}:::plan
    Access226 & Access227 --> List229
    __Item208 --> Access226
    __Item208 --> Access227
    Lambda230{{"Lambda[230∈29]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List229 --> Lambda230
    List234{{"List[234∈30]^<br />ᐸ231,232,233ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[233]"}}:::plan
    Access231{{"Access[231∈30]<br />ᐸ210.0ᐳ<br />ᐳGcpApplication"}}:::plan
    Access232{{"Access[232∈30]<br />ᐸ210.1ᐳ<br />ᐳGcpApplication"}}:::plan
    Access231 & Access232 --> List234
    __Item210 --> Access231
    __Item210 --> Access232
    Lambda235{{"Lambda[235∈30]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List234 --> Lambda235
    Access237{{"Access[237∈31]^<br />ᐸ236.__typenameᐳ"}}:::plan
    __Value236:::plan@{shape: docs, label: "__Combined[236∈31]<br />ᐳAwsApplication<br />ᐳGcpApplication"}
    __Value236 --> Access237
    Access238{{"Access[238∈31]^<br />ᐸ236.idᐳ"}}:::plan
    __Value236 --> Access238
    PgSelect239[["PgSelect[239∈33]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />(2) ...ᐳFirstPartyVulnerability<br />More deps:<br />- Object[12]"]]:::plan
    Access238 --> PgSelect239
    First243{{"First[243∈33]^"}}:::plan
    PgSelectRows244[["PgSelectRows[244∈33]^"]]:::plan
    PgSelectRows244 --> First243
    PgSelect239 --> PgSelectRows244
    PgSelectSingle245{{"PgSelectSingle[245∈33]^<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First243 --> PgSelectSingle245
    PgClassExpression254{{"PgClassExpression[254∈33]^<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle245 --> PgClassExpression254
    PgClassExpression256{{"PgClassExpression[256∈33]^<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgClassExpression254 o--o PgClassExpression256
    PgClassExpression258{{"PgClassExpression[258∈33]^<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgClassExpression256 o--o PgClassExpression258
    PgSelect247[["PgSelect[247∈34]<br />ᐸthird_party_vulnerabilitiesᐳ<br />(2) ...ᐳThirdPartyVulnerability<br />More deps:<br />- Object[12]"]]:::plan
    Access238 --> PgSelect247
    First251{{"First[251∈34]^"}}:::plan
    PgSelectRows252[["PgSelectRows[252∈34]^"]]:::plan
    PgSelectRows252 --> First251
    PgSelect247 --> PgSelectRows252
    PgSelectSingle253{{"PgSelectSingle[253∈34]^<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First251 --> PgSelectSingle253
    PgClassExpression255{{"PgClassExpression[255∈34]^<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle253 --> PgClassExpression255
    PgClassExpression257{{"PgClassExpression[257∈34]^<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgClassExpression255 o--o PgClassExpression257
    PgClassExpression259{{"PgClassExpression[259∈34]^<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgClassExpression257 o--o PgClassExpression259

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect9,Access10,Access11,Object12,Connection13,ConnectionItems15 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1 bucket1
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item19,PgSelectSingle20 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression21,PgClassExpression22,PgUnionAll23,Connection27,PgUnionAll28,First29,PgClassExpression32,ConnectionItems33,Access266 bucket4
    classDef bucket7 stroke:#808000
    class Bucket7,__Item38,Edge39,Access41,Access42,List44,Lambda45,Access47,Access48,Access64,PgCursor65,Access108 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,Access107 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgSelect49,First53,PgSelectRows54,PgSelectSingle55,PgClassExpression67,PgClassExpression69,PgClassExpression71,PgClassExpression73,PgClassExpression74,PgUnionAll75,First79,PgUnionAll91,PgUnionAll95,Connection97,Access126,Access127,List129,Lambda130,PgUnionAll160,First161,PgClassExpression164,ConnectionItems170,Access260,Access261,Access262 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11,PgSelect57,First61,PgSelectRows62,PgSelectSingle63,PgClassExpression68,PgClassExpression70,PgClassExpression72,PgClassExpression82,PgClassExpression83,PgUnionAll84,First88,PgUnionAll93,PgUnionAll98,Connection100,Access131,Access132,List134,Lambda135,PgUnionAll165,First166,PgClassExpression169,ConnectionItems173,Access263,Access264,Access265 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12 bucket12
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgSelect109,First113,PgSelectRows114,PgSelectSingle115,PgClassExpression158 bucket13
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgSelect117,First121,PgSelectRows122,PgSelectSingle123,PgClassExpression159 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15,__Value136,Access137 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16 bucket16
    classDef bucket17 stroke:#696969
    class Bucket17,__Item154,Access176,Access177,List179,Lambda180 bucket17
    classDef bucket18 stroke:#00bfff
    class Bucket18,__Item156,Access181,Access182,List184,Lambda185 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19,Access138,PgSelect139,First143,PgSelectRows144,PgSelectSingle145,PgClassExpression204,PgClassExpression206 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20,Access146,PgSelect147,First151,PgSelectRows152,PgSelectSingle153,PgClassExpression205,PgClassExpression207 bucket20
    classDef bucket23 stroke:#ff1493
    class Bucket23,__Value186,Access187,Access188 bucket23
    classDef bucket24 stroke:#808000
    class Bucket24 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25,PgSelect189,First193,PgSelectRows194,PgSelectSingle195,PgClassExpression212,PgClassExpression214,PgClassExpression216,PgClassExpression218 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,PgSelect197,First201,PgSelectRows202,PgSelectSingle203,PgClassExpression213,PgClassExpression215,PgClassExpression217,PgClassExpression219 bucket26
    classDef bucket27 stroke:#ffff00
    class Bucket27,__Item208,Edge209,Access220,PgCursor221 bucket27
    classDef bucket28 stroke:#00ffff
    class Bucket28,__Item210,Edge211,Access222,PgCursor223 bucket28
    classDef bucket29 stroke:#4169e1
    class Bucket29,Access226,Access227,List229,Lambda230 bucket29
    classDef bucket30 stroke:#3cb371
    class Bucket30,Access231,Access232,List234,Lambda235 bucket30
    classDef bucket31 stroke:#a52a2a
    class Bucket31,__Value236,Access237,Access238 bucket31
    classDef bucket32 stroke:#ff00ff
    class Bucket32 bucket32
    classDef bucket33 stroke:#f5deb3
    class Bucket33,PgSelect239,First243,PgSelectRows244,PgSelectSingle245,PgClassExpression254,PgClassExpression256,PgClassExpression258 bucket33
    classDef bucket34 stroke:#696969
    class Bucket34,PgSelect247,First251,PgSelectRows252,PgSelectSingle253,PgClassExpression255,PgClassExpression257,PgClassExpression259 bucket34

    Lambda130 -.-x __Value136
    Lambda135 -.-x __Value136
    Lambda180 -.-x __Value186
    Lambda185 -.-x __Value186
    Lambda230 -.-x __Value236
    Lambda235 -.-x __Value236
