%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/polymorphic/relational-functions"
    Bucket0("Bucket 0 (root)<br /><br />1: 922, 927, 931, 936, 940, 945<br />ᐳ: 8, 9, 926, 935, 944, 953, 954, 955, 10, 15, 22, 28, 34, 41<br />2: 7, 13, 20, 26, 32, 39<br />ᐳ: 923, 928, 932, 937, 941, 946<br />3: 11, 17, 24, 30, 36, 43<br />ᐳ: 16, 18, 23, 25, 29, 31, 35, 37, 42, 44, 45, 48, 49, 90, 93, 94, 246, 251<br />4: ConnectionItems[135]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 135, 11, 10<br /><br />ROOT Connectionᐸ7ᐳ[11]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 31, 923, 928, 10<br /><br />ROOT PgSelectSingleᐸrelational_topic_by_id_fnᐳ[31]<br />1: <br />ᐳ: 201, 924, 929, 925, 930<br />2: PgSelectRows[144], PgSelectRows[209]<br />ᐳ: 143, 145, 146, 170, 188, 208, 210, 284, 287, 288"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 37, 932, 937, 10<br /><br />ROOT PgSelectSingleᐸrelational_topic_by_id_fnᐳ[37]<br />1: <br />ᐳ: 202, 933, 938, 934, 939<br />2: PgSelectRows[153], PgSelectRows[216]<br />ᐳ: 152, 154, 155, 176, 194, 215, 217, 329, 332, 333"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 44, 941, 946, 10<br /><br />ROOT PgSelectSingleᐸrelational_topic_by_id_fnᐳ[44]<br />1: <br />ᐳ: 203, 942, 947, 943, 948<br />2: PgSelectRows[162], PgSelectRows[223]<br />ᐳ: 161, 163, 164, 182, 200, 222, 224, 374, 377, 378"):::bucket
    Bucket5("Bucket 5 (polymorphic)<br />__typename: Lambda[49]<br />Deps: 49, 10, 45, 48, 246"):::bucket
    Bucket6("Bucket 6 (polymorphic)<br />__typename: Lambda[94]<br />Deps: 94, 10, 90, 93, 251"):::bucket
    Bucket7("Bucket 7 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 45, 48, 246<br />ᐳRelationalTopic<br /><br />1: 912, 913<br />2: PgSelect[51]<br />ᐳ: Access[914]<br />3: PgSelectRows[56]<br />ᐳ: 55, 57, 256, 915, 916<br />4: PgSelectRows[271]<br />ᐳ: 270, 272, 421, 424, 425"):::bucket
    Bucket8("Bucket 8 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 45, 48, 246<br />ᐳRelationalPost<br /><br />1: PgSelect[59]<br />2: PgSelectRows[64]<br />ᐳ: 63, 65, 257, 273"):::bucket
    Bucket9("Bucket 9 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 45, 48, 246<br />ᐳRelationalDivider<br /><br />1: PgSelect[67]<br />2: PgSelectRows[72]<br />ᐳ: 71, 73, 258"):::bucket
    Bucket10("Bucket 10 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 45, 48, 246<br />ᐳRelationalChecklist<br /><br />1: PgSelect[75]<br />2: PgSelectRows[80]<br />ᐳ: First[79], PgSelectSingle[81]"):::bucket
    Bucket11("Bucket 11 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 45, 48, 246<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[83]<br />2: PgSelectRows[88]<br />ᐳ: 87, 89, 259"):::bucket
    Bucket12("Bucket 12 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 90, 93, 251<br />ᐳRelationalTopic<br /><br />1: 917, 918<br />2: PgSelect[96]<br />ᐳ: Access[919]<br />3: PgSelectRows[101]<br />ᐳ: 100, 102, 260, 920, 921<br />4: PgSelectRows[281]<br />ᐳ: 280, 282, 466, 469, 470"):::bucket
    Bucket13("Bucket 13 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 90, 93, 251<br />ᐳRelationalPost<br /><br />1: PgSelect[104]<br />2: PgSelectRows[109]<br />ᐳ: 108, 110, 261, 283"):::bucket
    Bucket14("Bucket 14 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 90, 93, 251<br />ᐳRelationalDivider<br /><br />1: PgSelect[112]<br />2: PgSelectRows[117]<br />ᐳ: 116, 118, 262"):::bucket
    Bucket15("Bucket 15 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 90, 93, 251<br />ᐳRelationalChecklist<br /><br />1: PgSelect[120]<br />2: PgSelectRows[125]<br />ᐳ: First[124], PgSelectSingle[126]"):::bucket
    Bucket16("Bucket 16 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 90, 93, 251<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[128]<br />2: PgSelectRows[133]<br />ᐳ: 132, 134, 263"):::bucket
    Bucket18("Bucket 18 (polymorphic)<br />__typename: Lambda[288]<br />Deps: 288, 10, 284, 287"):::bucket
    Bucket19("Bucket 19 (polymorphic)<br />__typename: Lambda[333]<br />Deps: 333, 10, 329, 332"):::bucket
    Bucket20("Bucket 20 (polymorphic)<br />__typename: Lambda[378]<br />Deps: 378, 10, 374, 377"):::bucket
    Bucket21("Bucket 21 (listItem)<br />Deps: 10<br /><br />ROOT __Item{21}ᐸ225ᐳ[419]"):::bucket
    Bucket22("Bucket 22 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 284, 287<br />ᐳRelationalTopic<br /><br />1: PgSelect[290]<br />2: PgSelectRows[295]<br />ᐳ: 294, 296, 586"):::bucket
    Bucket23("Bucket 23 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 284, 287<br />ᐳRelationalPost<br /><br />1: PgSelect[298]<br />2: PgSelectRows[303]<br />ᐳ: 302, 304, 587, 598"):::bucket
    Bucket24("Bucket 24 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 284, 287<br />ᐳRelationalDivider<br /><br />1: PgSelect[306]<br />2: PgSelectRows[311]<br />ᐳ: 310, 312, 588"):::bucket
    Bucket25("Bucket 25 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 284, 287<br />ᐳRelationalChecklist<br /><br />1: PgSelect[314]<br />2: PgSelectRows[319]<br />ᐳ: First[318], PgSelectSingle[320]"):::bucket
    Bucket26("Bucket 26 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 284, 287<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[322]<br />2: PgSelectRows[327]<br />ᐳ: 326, 328, 589"):::bucket
    Bucket27("Bucket 27 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 329, 332<br />ᐳRelationalTopic<br /><br />1: PgSelect[335]<br />2: PgSelectRows[340]<br />ᐳ: 339, 341, 590"):::bucket
    Bucket28("Bucket 28 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 329, 332<br />ᐳRelationalPost<br /><br />1: PgSelect[343]<br />2: PgSelectRows[348]<br />ᐳ: 347, 349, 591, 599"):::bucket
    Bucket29("Bucket 29 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 329, 332<br />ᐳRelationalDivider<br /><br />1: PgSelect[351]<br />2: PgSelectRows[356]<br />ᐳ: 355, 357, 592"):::bucket
    Bucket30("Bucket 30 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 329, 332<br />ᐳRelationalChecklist<br /><br />1: PgSelect[359]<br />2: PgSelectRows[364]<br />ᐳ: First[363], PgSelectSingle[365]"):::bucket
    Bucket31("Bucket 31 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 329, 332<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[367]<br />2: PgSelectRows[372]<br />ᐳ: 371, 373, 593"):::bucket
    Bucket32("Bucket 32 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 374, 377<br />ᐳRelationalTopic<br /><br />1: PgSelect[380]<br />2: PgSelectRows[385]<br />ᐳ: 384, 386, 594"):::bucket
    Bucket33("Bucket 33 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 374, 377<br />ᐳRelationalPost<br /><br />1: PgSelect[388]<br />2: PgSelectRows[393]<br />ᐳ: 392, 394, 595, 600"):::bucket
    Bucket34("Bucket 34 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 374, 377<br />ᐳRelationalDivider<br /><br />1: PgSelect[396]<br />2: PgSelectRows[401]<br />ᐳ: 400, 402, 596"):::bucket
    Bucket35("Bucket 35 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 374, 377<br />ᐳRelationalChecklist<br /><br />1: PgSelect[404]<br />2: PgSelectRows[409]<br />ᐳ: First[408], PgSelectSingle[410]"):::bucket
    Bucket36("Bucket 36 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 374, 377<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[412]<br />2: PgSelectRows[417]<br />ᐳ: 416, 418, 597"):::bucket
    Bucket37("Bucket 37 (polymorphic)<br />__typename: Lambda[425]<br />Deps: 425, 10, 421, 424"):::bucket
    Bucket38("Bucket 38 (polymorphic)<br />__typename: Lambda[470]<br />Deps: 470, 10, 466, 469"):::bucket
    Bucket39("Bucket 39 (polymorphic)<br />__typename: Lambda[515]<br />Deps: 515, 10, 511, 514, 641"):::bucket
    Bucket40("Bucket 40 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 421, 424<br />ᐳRelationalTopicᐳRelationalTopic<br /><br />1: PgSelect[427]<br />2: PgSelectRows[432]<br />ᐳ: 431, 433, 621"):::bucket
    Bucket41("Bucket 41 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 421, 424<br />ᐳRelationalTopicᐳRelationalPost<br /><br />1: PgSelect[435]<br />2: PgSelectRows[440]<br />ᐳ: 439, 441, 622, 629"):::bucket
    Bucket42("Bucket 42 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 421, 424<br />ᐳRelationalTopicᐳRelationalDivider<br /><br />1: PgSelect[443]<br />2: PgSelectRows[448]<br />ᐳ: 447, 449, 623"):::bucket
    Bucket43("Bucket 43 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 421, 424<br />ᐳRelationalTopicᐳRelationalChecklist<br /><br />1: PgSelect[451]<br />2: PgSelectRows[456]<br />ᐳ: First[455], PgSelectSingle[457]"):::bucket
    Bucket44("Bucket 44 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 421, 424<br />ᐳRelationalTopicᐳRelationalChecklistItem<br /><br />1: PgSelect[459]<br />2: PgSelectRows[464]<br />ᐳ: 463, 465, 624"):::bucket
    Bucket45("Bucket 45 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 466, 469<br />ᐳRelationalTopicᐳRelationalTopic<br /><br />1: PgSelect[472]<br />2: PgSelectRows[477]<br />ᐳ: 476, 478, 625"):::bucket
    Bucket46("Bucket 46 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 466, 469<br />ᐳRelationalTopicᐳRelationalPost<br /><br />1: PgSelect[480]<br />2: PgSelectRows[485]<br />ᐳ: 484, 486, 626, 630"):::bucket
    Bucket47("Bucket 47 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 466, 469<br />ᐳRelationalTopicᐳRelationalDivider<br /><br />1: PgSelect[488]<br />2: PgSelectRows[493]<br />ᐳ: 492, 494, 627"):::bucket
    Bucket48("Bucket 48 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 466, 469<br />ᐳRelationalTopicᐳRelationalChecklist<br /><br />1: PgSelect[496]<br />2: PgSelectRows[501]<br />ᐳ: First[500], PgSelectSingle[502]"):::bucket
    Bucket49("Bucket 49 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 466, 469<br />ᐳRelationalTopicᐳRelationalChecklistItem<br /><br />1: PgSelect[504]<br />2: PgSelectRows[509]<br />ᐳ: 508, 510, 628"):::bucket
    Bucket50("Bucket 50 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 511, 514, 641<br />ᐳRelationalTopic<br /><br />1: 663, 908<br />2: PgSelect[517]<br />ᐳ: Access[909]<br />3: PgSelectRows[522]<br />ᐳ: 521, 523, 646, 686, 910, 911<br />4: PgSelectRows[665], PgSelect[684]<br />ᐳ: 664, 666, 759, 762, 763<br />5: PgSelectRows[688]<br />ᐳ: 687, 689, 704, 705"):::bucket
    Bucket51("Bucket 51 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 511, 514, 641<br />ᐳRelationalPost<br /><br />1: PgSelect[525]<br />2: PgSelectRows[530]<br />ᐳ: 529, 531, 647, 667, 694<br />3: PgSelect[690]<br />4: PgSelectRows[696]<br />ᐳ: 695, 697, 706, 707"):::bucket
    Bucket52("Bucket 52 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 511, 514, 641<br />ᐳRelationalDivider<br /><br />1: PgSelect[533]<br />2: PgSelectRows[538]<br />ᐳ: 537, 539, 648, 672<br />3: PgSelect[668]<br />4: PgSelectRows[674]<br />ᐳ: 673, 675, 700, 701"):::bucket
    Bucket53("Bucket 53 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 511, 514, 641<br />ᐳRelationalChecklist<br /><br />1: PgSelect[541]<br />2: PgSelectRows[546]<br />ᐳ: 545, 547, 653<br />3: PgSelect[649]<br />4: PgSelectRows[655]<br />ᐳ: 654, 656, 698, 699"):::bucket
    Bucket54("Bucket 54 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 511, 514, 641<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[549]<br />2: PgSelectRows[554]<br />ᐳ: 553, 555, 657, 680<br />3: PgSelect[676]<br />4: PgSelectRows[682]<br />ᐳ: 681, 683, 702, 703"):::bucket
    Bucket55("Bucket 55 (combined)<br />Deps: 10<br /><br />1: <br />ᐳ: Access[709]<br />2: PgSelect[710]<br />3: PgSelectRows[715]<br />ᐳ: 714, 716, 717, 718, 719, 824"):::bucket
    Bucket56("Bucket 56 (polymorphic)<br />__typename: Lambda[718]<br />Deps: 718, 10, 719, 717, 824"):::bucket
    Bucket57("Bucket 57 (polymorphic)<br />__typename: Lambda[763]<br />Deps: 763, 10, 759, 762"):::bucket
    Bucket58("Bucket 58 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 719, 717, 824<br />(5) ...ᐳRelationalTopic<br /><br />1: 843, 949<br />2: PgSelect[720]<br />ᐳ: Access[950]<br />3: PgSelectRows[725]<br />ᐳ: 724, 726, 833, 951, 952<br />4: PgSelectRows[845]<br />ᐳ: 844, 846, 848, 851, 852"):::bucket
    Bucket59("Bucket 59 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 719, 717, 824<br />(5) ...ᐳRelationalPost<br /><br />1: PgSelect[728]<br />2: PgSelectRows[733]<br />ᐳ: 732, 734, 834, 847"):::bucket
    Bucket60("Bucket 60 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 719, 717, 824<br />(5) ...ᐳRelationalDivider<br /><br />1: PgSelect[736]<br />2: PgSelectRows[741]<br />ᐳ: 740, 742, 835"):::bucket
    Bucket61("Bucket 61 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 719, 717, 824<br />(5) ...ᐳRelationalChecklist<br /><br />1: PgSelect[744]<br />2: PgSelectRows[749]<br />ᐳ: First[748], PgSelectSingle[750]"):::bucket
    Bucket62("Bucket 62 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 719, 717, 824<br />(5) ...ᐳRelationalChecklistItem<br /><br />1: PgSelect[752]<br />2: PgSelectRows[757]<br />ᐳ: 756, 758, 836"):::bucket
    Bucket63("Bucket 63 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 759, 762<br />ᐳRelationalTopicᐳRelationalTopic<br /><br />1: PgSelect[765]<br />2: PgSelectRows[770]<br />ᐳ: 769, 771, 829"):::bucket
    Bucket64("Bucket 64 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 759, 762<br />ᐳRelationalTopicᐳRelationalPost<br /><br />1: PgSelect[773]<br />2: PgSelectRows[778]<br />ᐳ: 777, 779, 830, 837"):::bucket
    Bucket65("Bucket 65 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 759, 762<br />ᐳRelationalTopicᐳRelationalDivider<br /><br />1: PgSelect[781]<br />2: PgSelectRows[786]<br />ᐳ: 785, 787, 831"):::bucket
    Bucket66("Bucket 66 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 759, 762<br />ᐳRelationalTopicᐳRelationalChecklist<br /><br />1: PgSelect[789]<br />2: PgSelectRows[794]<br />ᐳ: First[793], PgSelectSingle[795]"):::bucket
    Bucket67("Bucket 67 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 759, 762<br />ᐳRelationalTopicᐳRelationalChecklistItem<br /><br />1: PgSelect[797]<br />2: PgSelectRows[802]<br />ᐳ: 801, 803, 832"):::bucket
    Bucket68("Bucket 68 (polymorphic)<br />__typename: Lambda[852]<br />Deps: 852, 10, 848, 851"):::bucket
    Bucket69("Bucket 69 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 848, 851<br />(5) ...ᐳRelationalTopic<br /><br />1: PgSelect[854]<br />2: PgSelectRows[859]<br />ᐳ: 858, 860, 903"):::bucket
    Bucket70("Bucket 70 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 848, 851<br />(5) ...ᐳRelationalPost<br /><br />1: PgSelect[862]<br />2: PgSelectRows[867]<br />ᐳ: 866, 868, 904, 907"):::bucket
    Bucket71("Bucket 71 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 848, 851<br />(5) ...ᐳRelationalDivider<br /><br />1: PgSelect[870]<br />2: PgSelectRows[875]<br />ᐳ: 874, 876, 905"):::bucket
    Bucket72("Bucket 72 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 848, 851<br />(5) ...ᐳRelationalChecklist<br /><br />1: PgSelect[878]<br />2: PgSelectRows[883]<br />ᐳ: First[882], PgSelectSingle[884]"):::bucket
    Bucket73("Bucket 73 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 848, 851<br />(5) ...ᐳRelationalChecklistItem<br /><br />1: PgSelect[886]<br />2: PgSelectRows[891]<br />ᐳ: 890, 892, 906"):::bucket
    end
    Bucket0 --> Bucket1 & Bucket2 & Bucket3 & Bucket4 & Bucket5 & Bucket6
    Bucket1 --> Bucket21
    Bucket2 --> Bucket18
    Bucket3 --> Bucket19
    Bucket4 --> Bucket20
    Bucket5 --> Bucket7 & Bucket8 & Bucket9 & Bucket10 & Bucket11
    Bucket6 --> Bucket12 & Bucket13 & Bucket14 & Bucket15 & Bucket16
    Bucket7 --> Bucket37
    Bucket12 --> Bucket38
    Bucket18 --> Bucket22 & Bucket23 & Bucket24 & Bucket25 & Bucket26
    Bucket19 --> Bucket27 & Bucket28 & Bucket29 & Bucket30 & Bucket31
    Bucket20 --> Bucket32 & Bucket33 & Bucket34 & Bucket35 & Bucket36
    Bucket21 --> Bucket39
    Bucket37 --> Bucket40 & Bucket41 & Bucket42 & Bucket43 & Bucket44
    Bucket38 --> Bucket45 & Bucket46 & Bucket47 & Bucket48 & Bucket49
    Bucket39 --> Bucket50 & Bucket51 & Bucket52 & Bucket53 & Bucket54
    Bucket50 --> Bucket55 & Bucket57
    Bucket51 --> Bucket55
    Bucket52 --> Bucket55
    Bucket53 --> Bucket55
    Bucket54 --> Bucket55
    Bucket55 --> Bucket56
    Bucket56 --> Bucket58 & Bucket59 & Bucket60 & Bucket61 & Bucket62
    Bucket57 --> Bucket63 & Bucket64 & Bucket65 & Bucket66 & Bucket67
    Bucket58 --> Bucket68
    Bucket68 --> Bucket69 & Bucket70 & Bucket71 & Bucket72 & Bucket73

    %% plan dependencies
    PgSelect26[["PgSelect[26∈0] ➊<br />ᐸrelational_topic_by_id_fnᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression28{{"PgFromExpression[28∈0] ➊<br />More deps:<br />- Constantᐸ-1ᐳ[954]"}}:::plan
    PgSelectInlineApply922["PgSelectInlineApply[922∈0] ➊"]:::plan
    PgFromExpression926{{"PgFromExpression[926∈0] ➊"}}:::plan
    PgSelectInlineApply927["PgSelectInlineApply[927∈0] ➊"]:::plan
    PgFromExpression28 & PgSelectInlineApply922 & PgFromExpression926 & PgSelectInlineApply927 --> PgSelect26
    PgSelect32[["PgSelect[32∈0] ➊<br />ᐸrelational_topic_by_id_fnᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression34{{"PgFromExpression[34∈0] ➊<br />More deps:<br />- Constantᐸ16ᐳ[953]"}}:::plan
    PgSelectInlineApply931["PgSelectInlineApply[931∈0] ➊"]:::plan
    PgFromExpression935{{"PgFromExpression[935∈0] ➊"}}:::plan
    PgSelectInlineApply936["PgSelectInlineApply[936∈0] ➊"]:::plan
    PgFromExpression34 & PgSelectInlineApply931 & PgFromExpression935 & PgSelectInlineApply936 --> PgSelect32
    PgSelect39[["PgSelect[39∈0] ➊<br />ᐸrelational_topic_by_id_fnᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression41{{"PgFromExpression[41∈0] ➊<br />More deps:<br />- Constantᐸ11ᐳ[955]"}}:::plan
    PgSelectInlineApply940["PgSelectInlineApply[940∈0] ➊"]:::plan
    PgFromExpression944{{"PgFromExpression[944∈0] ➊"}}:::plan
    PgSelectInlineApply945["PgSelectInlineApply[945∈0] ➊"]:::plan
    PgFromExpression41 & PgSelectInlineApply940 & PgFromExpression944 & PgSelectInlineApply945 --> PgSelect39
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ<br />Dependents: 67"}}:::plan
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    PgSelect13[["PgSelect[13∈0] ➊<br />ᐸrelational_item_by_id_fnᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression15{{"PgFromExpression[15∈0] ➊<br />More deps:<br />- Constantᐸ16ᐳ[953]"}}:::plan
    PgFromExpression15 --> PgSelect13
    PgSelect20[["PgSelect[20∈0] ➊<br />ᐸrelational_item_by_id_fnᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression22{{"PgFromExpression[22∈0] ➊<br />More deps:<br />- Constantᐸ-1ᐳ[954]"}}:::plan
    PgFromExpression22 --> PgSelect20
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸall_relational_items_fnᐳ<br />More deps:<br />- Object[10]"]]:::plan
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    Connection11[["Connection[11∈0] ➊<br />ᐸ7ᐳ"]]:::plan
    PgSelect7 --> Connection11
    First16{{"First[16∈0] ➊"}}:::plan
    PgSelectRows17[["PgSelectRows[17∈0] ➊"]]:::plan
    PgSelectRows17 --> First16
    PgSelect13 --> PgSelectRows17
    PgSelectSingle18{{"PgSelectSingle[18∈0] ➊<br />ᐸrelational_item_by_id_fnᐳ"}}:::plan
    First16 --> PgSelectSingle18
    First23{{"First[23∈0] ➊"}}:::plan
    PgSelectRows24[["PgSelectRows[24∈0] ➊"]]:::plan
    PgSelectRows24 --> First23
    PgSelect20 --> PgSelectRows24
    PgSelectSingle25{{"PgSelectSingle[25∈0] ➊<br />ᐸrelational_item_by_id_fnᐳ"}}:::plan
    First23 --> PgSelectSingle25
    First29{{"First[29∈0] ➊"}}:::plan
    PgSelectRows30[["PgSelectRows[30∈0] ➊"]]:::plan
    PgSelectRows30 --> First29
    PgSelect26 --> PgSelectRows30
    PgSelectSingle31{{"PgSelectSingle[31∈0] ➊<br />ᐸrelational_topic_by_id_fnᐳ"}}:::plan
    First29 --> PgSelectSingle31
    First35{{"First[35∈0] ➊"}}:::plan
    PgSelectRows36[["PgSelectRows[36∈0] ➊"]]:::plan
    PgSelectRows36 --> First35
    PgSelect32 --> PgSelectRows36
    PgSelectSingle37{{"PgSelectSingle[37∈0] ➊<br />ᐸrelational_topic_by_id_fnᐳ"}}:::plan
    First35 --> PgSelectSingle37
    First42{{"First[42∈0] ➊"}}:::plan
    PgSelectRows43[["PgSelectRows[43∈0] ➊"]]:::plan
    PgSelectRows43 --> First42
    PgSelect39 --> PgSelectRows43
    PgSelectSingle44{{"PgSelectSingle[44∈0] ➊<br />ᐸrelational_topic_by_id_fnᐳ"}}:::plan
    First42 --> PgSelectSingle44
    PgClassExpression45{{"PgClassExpression[45∈0] ➊<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle18 --> PgClassExpression45
    PgClassExpression48{{"PgClassExpression[48∈0] ➊<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle18 --> PgClassExpression48
    PgClassExpression90{{"PgClassExpression[90∈0] ➊<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle25 --> PgClassExpression90
    PgClassExpression93{{"PgClassExpression[93∈0] ➊<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle25 --> PgClassExpression93
    ConnectionItems135[["ConnectionItems[135∈0] ➊"]]:::plan
    Connection11 --> ConnectionItems135
    Access923{{"Access[923∈0] ➊<br />ᐸ26.m.joinDetailsFor139ᐳ"}}:::plan
    PgSelect26 --> Access923
    Access928{{"Access[928∈0] ➊<br />ᐸ26.m.joinDetailsFor205ᐳ"}}:::plan
    PgSelect26 --> Access928
    Access932{{"Access[932∈0] ➊<br />ᐸ32.m.joinDetailsFor148ᐳ"}}:::plan
    PgSelect32 --> Access932
    Access937{{"Access[937∈0] ➊<br />ᐸ32.m.joinDetailsFor212ᐳ"}}:::plan
    PgSelect32 --> Access937
    Access941{{"Access[941∈0] ➊<br />ᐸ39.m.joinDetailsFor157ᐳ"}}:::plan
    PgSelect39 --> Access941
    Access946{{"Access[946∈0] ➊<br />ᐸ39.m.joinDetailsFor219ᐳ"}}:::plan
    PgSelect39 --> Access946
    __CloneStream225[["__CloneStream[225∈1] ➊"]]:::plan
    ConnectionItems135 --> __CloneStream225
    List924{{"List[924∈2] ➊<br />ᐸ923,31ᐳ"}}:::plan
    Access923 & PgSelectSingle31 --> List924
    List929{{"List[929∈2] ➊<br />ᐸ928,31ᐳ"}}:::plan
    Access928 & PgSelectSingle31 --> List929
    First143{{"First[143∈2] ➊"}}:::plan
    PgSelectRows144[["PgSelectRows[144∈2] ➊"]]:::plan
    PgSelectRows144 --> First143
    Lambda925{{"Lambda[925∈2] ➊<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda925 --> PgSelectRows144
    PgSelectSingle145{{"PgSelectSingle[145∈2] ➊<br />ᐸrelational_itemsᐳ"}}:::plan
    First143 --> PgSelectSingle145
    PgClassExpression146{{"PgClassExpression[146∈2] ➊<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle145 --> PgClassExpression146
    PgClassExpression170{{"PgClassExpression[170∈2] ➊<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgClassExpression146 o--o PgClassExpression170
    PgClassExpression188{{"PgClassExpression[188∈2] ➊<br />ᐸ__relation...parent_id”ᐳ"}}:::plan
    PgClassExpression170 o--o PgClassExpression188
    PgClassExpression201{{"PgClassExpression[201∈2] ➊<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle31 --> PgClassExpression201
    First208{{"First[208∈2] ➊"}}:::plan
    PgSelectRows209[["PgSelectRows[209∈2] ➊"]]:::plan
    PgSelectRows209 --> First208
    Lambda930{{"Lambda[930∈2] ➊<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda930 --> PgSelectRows209
    PgSelectSingle210{{"PgSelectSingle[210∈2] ➊<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First208 --> PgSelectSingle210
    PgClassExpression284{{"PgClassExpression[284∈2] ➊<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle210 --> PgClassExpression284
    PgClassExpression287{{"PgClassExpression[287∈2] ➊<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle210 --> PgClassExpression287
    Lambda288{{"Lambda[288∈2] ➊<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression287 --> Lambda288
    List924 --> Lambda925
    List929 --> Lambda930
    List933{{"List[933∈3] ➊<br />ᐸ932,37ᐳ"}}:::plan
    Access932 & PgSelectSingle37 --> List933
    List938{{"List[938∈3] ➊<br />ᐸ937,37ᐳ"}}:::plan
    Access937 & PgSelectSingle37 --> List938
    First152{{"First[152∈3] ➊"}}:::plan
    PgSelectRows153[["PgSelectRows[153∈3] ➊"]]:::plan
    PgSelectRows153 --> First152
    Lambda934{{"Lambda[934∈3] ➊<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda934 --> PgSelectRows153
    PgSelectSingle154{{"PgSelectSingle[154∈3] ➊<br />ᐸrelational_itemsᐳ"}}:::plan
    First152 --> PgSelectSingle154
    PgClassExpression155{{"PgClassExpression[155∈3] ➊<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle154 --> PgClassExpression155
    PgClassExpression176{{"PgClassExpression[176∈3] ➊<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgClassExpression155 o--o PgClassExpression176
    PgClassExpression194{{"PgClassExpression[194∈3] ➊<br />ᐸ__relation...parent_id”ᐳ"}}:::plan
    PgClassExpression176 o--o PgClassExpression194
    PgClassExpression202{{"PgClassExpression[202∈3] ➊<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle37 --> PgClassExpression202
    First215{{"First[215∈3] ➊"}}:::plan
    PgSelectRows216[["PgSelectRows[216∈3] ➊"]]:::plan
    PgSelectRows216 --> First215
    Lambda939{{"Lambda[939∈3] ➊<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda939 --> PgSelectRows216
    PgSelectSingle217{{"PgSelectSingle[217∈3] ➊<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First215 --> PgSelectSingle217
    PgClassExpression329{{"PgClassExpression[329∈3] ➊<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle217 --> PgClassExpression329
    PgClassExpression332{{"PgClassExpression[332∈3] ➊<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle217 --> PgClassExpression332
    Lambda333{{"Lambda[333∈3] ➊<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression332 --> Lambda333
    List933 --> Lambda934
    List938 --> Lambda939
    List942{{"List[942∈4] ➊<br />ᐸ941,44ᐳ"}}:::plan
    Access941 & PgSelectSingle44 --> List942
    List947{{"List[947∈4] ➊<br />ᐸ946,44ᐳ"}}:::plan
    Access946 & PgSelectSingle44 --> List947
    First161{{"First[161∈4] ➊"}}:::plan
    PgSelectRows162[["PgSelectRows[162∈4] ➊"]]:::plan
    PgSelectRows162 --> First161
    Lambda943{{"Lambda[943∈4] ➊<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda943 --> PgSelectRows162
    PgSelectSingle163{{"PgSelectSingle[163∈4] ➊<br />ᐸrelational_itemsᐳ"}}:::plan
    First161 --> PgSelectSingle163
    PgClassExpression164{{"PgClassExpression[164∈4] ➊<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle163 --> PgClassExpression164
    PgClassExpression182{{"PgClassExpression[182∈4] ➊<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgClassExpression164 o--o PgClassExpression182
    PgClassExpression200{{"PgClassExpression[200∈4] ➊<br />ᐸ__relation...parent_id”ᐳ"}}:::plan
    PgClassExpression182 o--o PgClassExpression200
    PgClassExpression203{{"PgClassExpression[203∈4] ➊<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle44 --> PgClassExpression203
    First222{{"First[222∈4] ➊"}}:::plan
    PgSelectRows223[["PgSelectRows[223∈4] ➊"]]:::plan
    PgSelectRows223 --> First222
    Lambda948{{"Lambda[948∈4] ➊<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda948 --> PgSelectRows223
    PgSelectSingle224{{"PgSelectSingle[224∈4] ➊<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First222 --> PgSelectSingle224
    PgClassExpression374{{"PgClassExpression[374∈4] ➊<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle224 --> PgClassExpression374
    PgClassExpression377{{"PgClassExpression[377∈4] ➊<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle224 --> PgClassExpression377
    Lambda378{{"Lambda[378∈4] ➊<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression377 --> Lambda378
    List942 --> Lambda943
    List947 --> Lambda948
    PgSelect51[["PgSelect[51∈7] ➊^<br />ᐸrelational_topicsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression912{{"PgFromExpression[912∈7] ➊<br />ᐳRelationalTopic"}}:::plan
    PgSelectInlineApply913["PgSelectInlineApply[913∈7] ➊<br />ᐳRelationalTopic"]:::plan
    PgClassExpression45 & PgFromExpression912 & PgSelectInlineApply913 --> PgSelect51
    List915{{"List[915∈7] ➊^<br />ᐸ914,57ᐳ"}}:::plan
    Access914{{"Access[914∈7] ➊^<br />ᐸ51.m.joinDetailsFor265ᐳ"}}:::plan
    PgSelectSingle57{{"PgSelectSingle[57∈7] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    Access914 & PgSelectSingle57 --> List915
    First55{{"First[55∈7] ➊^"}}:::plan
    PgSelectRows56[["PgSelectRows[56∈7] ➊^"]]:::plan
    PgSelectRows56 --> First55
    PgSelect51 --> PgSelectRows56
    First55 --> PgSelectSingle57
    PgClassExpression256{{"PgClassExpression[256∈7] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle57 --> PgClassExpression256
    First270{{"First[270∈7] ➊^"}}:::plan
    PgSelectRows271[["PgSelectRows[271∈7] ➊^"]]:::plan
    PgSelectRows271 --> First270
    Lambda916{{"Lambda[916∈7] ➊^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda916 --> PgSelectRows271
    PgSelectSingle272{{"PgSelectSingle[272∈7] ➊^<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First270 --> PgSelectSingle272
    PgClassExpression421{{"PgClassExpression[421∈7] ➊^<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle272 --> PgClassExpression421
    PgClassExpression424{{"PgClassExpression[424∈7] ➊^<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle272 --> PgClassExpression424
    Lambda425{{"Lambda[425∈7] ➊^<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression424 --> Lambda425
    PgSelect51 --> Access914
    List915 --> Lambda916
    PgSelect59[["PgSelect[59∈8] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression45 --> PgSelect59
    First63{{"First[63∈8] ➊^"}}:::plan
    PgSelectRows64[["PgSelectRows[64∈8] ➊^"]]:::plan
    PgSelectRows64 --> First63
    PgSelect59 --> PgSelectRows64
    PgSelectSingle65{{"PgSelectSingle[65∈8] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First63 --> PgSelectSingle65
    PgClassExpression257{{"PgClassExpression[257∈8] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle65 --> PgClassExpression257
    PgClassExpression273{{"PgClassExpression[273∈8] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression257 o--o PgClassExpression273
    PgSelect67[["PgSelect[67∈9] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression45 --> PgSelect67
    First71{{"First[71∈9] ➊^"}}:::plan
    PgSelectRows72[["PgSelectRows[72∈9] ➊^"]]:::plan
    PgSelectRows72 --> First71
    PgSelect67 --> PgSelectRows72
    PgSelectSingle73{{"PgSelectSingle[73∈9] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First71 --> PgSelectSingle73
    PgClassExpression258{{"PgClassExpression[258∈9] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle73 --> PgClassExpression258
    PgSelect75[["PgSelect[75∈10] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression45 --> PgSelect75
    First79{{"First[79∈10] ➊^"}}:::plan
    PgSelectRows80[["PgSelectRows[80∈10] ➊^"]]:::plan
    PgSelectRows80 --> First79
    PgSelect75 --> PgSelectRows80
    PgSelectSingle81{{"PgSelectSingle[81∈10] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First79 --> PgSelectSingle81
    PgSelect83[["PgSelect[83∈11] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression45 --> PgSelect83
    First87{{"First[87∈11] ➊^"}}:::plan
    PgSelectRows88[["PgSelectRows[88∈11] ➊^"]]:::plan
    PgSelectRows88 --> First87
    PgSelect83 --> PgSelectRows88
    PgSelectSingle89{{"PgSelectSingle[89∈11] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First87 --> PgSelectSingle89
    PgClassExpression259{{"PgClassExpression[259∈11] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle89 --> PgClassExpression259
    PgSelect96[["PgSelect[96∈12] ➊^<br />ᐸrelational_topicsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression917{{"PgFromExpression[917∈12] ➊<br />ᐳRelationalTopic"}}:::plan
    PgSelectInlineApply918["PgSelectInlineApply[918∈12] ➊<br />ᐳRelationalTopic"]:::plan
    PgClassExpression90 & PgFromExpression917 & PgSelectInlineApply918 --> PgSelect96
    List920{{"List[920∈12] ➊^<br />ᐸ919,102ᐳ"}}:::plan
    Access919{{"Access[919∈12] ➊^<br />ᐸ96.m.joinDetailsFor275ᐳ"}}:::plan
    PgSelectSingle102{{"PgSelectSingle[102∈12] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    Access919 & PgSelectSingle102 --> List920
    First100{{"First[100∈12] ➊^"}}:::plan
    PgSelectRows101[["PgSelectRows[101∈12] ➊^"]]:::plan
    PgSelectRows101 --> First100
    PgSelect96 --> PgSelectRows101
    First100 --> PgSelectSingle102
    PgClassExpression260{{"PgClassExpression[260∈12] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle102 --> PgClassExpression260
    First280{{"First[280∈12] ➊^"}}:::plan
    PgSelectRows281[["PgSelectRows[281∈12] ➊^"]]:::plan
    PgSelectRows281 --> First280
    Lambda921{{"Lambda[921∈12] ➊^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda921 --> PgSelectRows281
    PgSelectSingle282{{"PgSelectSingle[282∈12] ➊^<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First280 --> PgSelectSingle282
    PgClassExpression466{{"PgClassExpression[466∈12] ➊^<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle282 --> PgClassExpression466
    PgClassExpression469{{"PgClassExpression[469∈12] ➊^<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle282 --> PgClassExpression469
    Lambda470{{"Lambda[470∈12] ➊^<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression469 --> Lambda470
    PgSelect96 --> Access919
    List920 --> Lambda921
    PgSelect104[["PgSelect[104∈13] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression90 --> PgSelect104
    First108{{"First[108∈13] ➊^"}}:::plan
    PgSelectRows109[["PgSelectRows[109∈13] ➊^"]]:::plan
    PgSelectRows109 --> First108
    PgSelect104 --> PgSelectRows109
    PgSelectSingle110{{"PgSelectSingle[110∈13] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First108 --> PgSelectSingle110
    PgClassExpression261{{"PgClassExpression[261∈13] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle110 --> PgClassExpression261
    PgClassExpression283{{"PgClassExpression[283∈13] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression261 o--o PgClassExpression283
    PgSelect112[["PgSelect[112∈14] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression90 --> PgSelect112
    First116{{"First[116∈14] ➊^"}}:::plan
    PgSelectRows117[["PgSelectRows[117∈14] ➊^"]]:::plan
    PgSelectRows117 --> First116
    PgSelect112 --> PgSelectRows117
    PgSelectSingle118{{"PgSelectSingle[118∈14] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First116 --> PgSelectSingle118
    PgClassExpression262{{"PgClassExpression[262∈14] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle118 --> PgClassExpression262
    PgSelect120[["PgSelect[120∈15] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression90 --> PgSelect120
    First124{{"First[124∈15] ➊^"}}:::plan
    PgSelectRows125[["PgSelectRows[125∈15] ➊^"]]:::plan
    PgSelectRows125 --> First124
    PgSelect120 --> PgSelectRows125
    PgSelectSingle126{{"PgSelectSingle[126∈15] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First124 --> PgSelectSingle126
    PgSelect128[["PgSelect[128∈16] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression90 --> PgSelect128
    First132{{"First[132∈16] ➊^"}}:::plan
    PgSelectRows133[["PgSelectRows[133∈16] ➊^"]]:::plan
    PgSelectRows133 --> First132
    PgSelect128 --> PgSelectRows133
    PgSelectSingle134{{"PgSelectSingle[134∈16] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First132 --> PgSelectSingle134
    PgClassExpression263{{"PgClassExpression[263∈16] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle134 --> PgClassExpression263
    __Item419[/"__Item[419∈21]<br />ᐸ225ᐳ"\]:::itemplan
    __CloneStream225 ==> __Item419
    PgSelectSingle420{{"PgSelectSingle[420∈21]<br />ᐸall_relational_items_fnᐳ"}}:::plan
    __Item419 --> PgSelectSingle420
    PgClassExpression511{{"PgClassExpression[511∈21]<br />ᐸ__all_rela..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle420 --> PgClassExpression511
    PgClassExpression514{{"PgClassExpression[514∈21]<br />ᐸ__all_rela...n__.”type”ᐳ"}}:::plan
    PgSelectSingle420 --> PgClassExpression514
    Lambda515{{"Lambda[515∈21]<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression514 --> Lambda515
    PgClassExpression641{{"PgClassExpression[641∈21]<br />ᐸ__all_rela...parent_id”ᐳ"}}:::plan
    PgSelectSingle420 --> PgClassExpression641
    PgSelect290[["PgSelect[290∈22] ➊<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression284 --> PgSelect290
    First294{{"First[294∈22] ➊^"}}:::plan
    PgSelectRows295[["PgSelectRows[295∈22] ➊^"]]:::plan
    PgSelectRows295 --> First294
    PgSelect290 --> PgSelectRows295
    PgSelectSingle296{{"PgSelectSingle[296∈22] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    First294 --> PgSelectSingle296
    PgClassExpression586{{"PgClassExpression[586∈22] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle296 --> PgClassExpression586
    PgSelect298[["PgSelect[298∈23] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression284 --> PgSelect298
    First302{{"First[302∈23] ➊^"}}:::plan
    PgSelectRows303[["PgSelectRows[303∈23] ➊^"]]:::plan
    PgSelectRows303 --> First302
    PgSelect298 --> PgSelectRows303
    PgSelectSingle304{{"PgSelectSingle[304∈23] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First302 --> PgSelectSingle304
    PgClassExpression587{{"PgClassExpression[587∈23] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle304 --> PgClassExpression587
    PgClassExpression598{{"PgClassExpression[598∈23] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression587 o--o PgClassExpression598
    PgSelect306[["PgSelect[306∈24] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression284 --> PgSelect306
    First310{{"First[310∈24] ➊^"}}:::plan
    PgSelectRows311[["PgSelectRows[311∈24] ➊^"]]:::plan
    PgSelectRows311 --> First310
    PgSelect306 --> PgSelectRows311
    PgSelectSingle312{{"PgSelectSingle[312∈24] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First310 --> PgSelectSingle312
    PgClassExpression588{{"PgClassExpression[588∈24] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle312 --> PgClassExpression588
    PgSelect314[["PgSelect[314∈25] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression284 --> PgSelect314
    First318{{"First[318∈25] ➊^"}}:::plan
    PgSelectRows319[["PgSelectRows[319∈25] ➊^"]]:::plan
    PgSelectRows319 --> First318
    PgSelect314 --> PgSelectRows319
    PgSelectSingle320{{"PgSelectSingle[320∈25] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First318 --> PgSelectSingle320
    PgSelect322[["PgSelect[322∈26] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression284 --> PgSelect322
    First326{{"First[326∈26] ➊^"}}:::plan
    PgSelectRows327[["PgSelectRows[327∈26] ➊^"]]:::plan
    PgSelectRows327 --> First326
    PgSelect322 --> PgSelectRows327
    PgSelectSingle328{{"PgSelectSingle[328∈26] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First326 --> PgSelectSingle328
    PgClassExpression589{{"PgClassExpression[589∈26] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle328 --> PgClassExpression589
    PgSelect335[["PgSelect[335∈27] ➊<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression329 --> PgSelect335
    First339{{"First[339∈27] ➊^"}}:::plan
    PgSelectRows340[["PgSelectRows[340∈27] ➊^"]]:::plan
    PgSelectRows340 --> First339
    PgSelect335 --> PgSelectRows340
    PgSelectSingle341{{"PgSelectSingle[341∈27] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    First339 --> PgSelectSingle341
    PgClassExpression590{{"PgClassExpression[590∈27] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle341 --> PgClassExpression590
    PgSelect343[["PgSelect[343∈28] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression329 --> PgSelect343
    First347{{"First[347∈28] ➊^"}}:::plan
    PgSelectRows348[["PgSelectRows[348∈28] ➊^"]]:::plan
    PgSelectRows348 --> First347
    PgSelect343 --> PgSelectRows348
    PgSelectSingle349{{"PgSelectSingle[349∈28] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First347 --> PgSelectSingle349
    PgClassExpression591{{"PgClassExpression[591∈28] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle349 --> PgClassExpression591
    PgClassExpression599{{"PgClassExpression[599∈28] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression591 o--o PgClassExpression599
    PgSelect351[["PgSelect[351∈29] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression329 --> PgSelect351
    First355{{"First[355∈29] ➊^"}}:::plan
    PgSelectRows356[["PgSelectRows[356∈29] ➊^"]]:::plan
    PgSelectRows356 --> First355
    PgSelect351 --> PgSelectRows356
    PgSelectSingle357{{"PgSelectSingle[357∈29] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First355 --> PgSelectSingle357
    PgClassExpression592{{"PgClassExpression[592∈29] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle357 --> PgClassExpression592
    PgSelect359[["PgSelect[359∈30] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression329 --> PgSelect359
    First363{{"First[363∈30] ➊^"}}:::plan
    PgSelectRows364[["PgSelectRows[364∈30] ➊^"]]:::plan
    PgSelectRows364 --> First363
    PgSelect359 --> PgSelectRows364
    PgSelectSingle365{{"PgSelectSingle[365∈30] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First363 --> PgSelectSingle365
    PgSelect367[["PgSelect[367∈31] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression329 --> PgSelect367
    First371{{"First[371∈31] ➊^"}}:::plan
    PgSelectRows372[["PgSelectRows[372∈31] ➊^"]]:::plan
    PgSelectRows372 --> First371
    PgSelect367 --> PgSelectRows372
    PgSelectSingle373{{"PgSelectSingle[373∈31] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First371 --> PgSelectSingle373
    PgClassExpression593{{"PgClassExpression[593∈31] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle373 --> PgClassExpression593
    PgSelect380[["PgSelect[380∈32] ➊<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression374 --> PgSelect380
    First384{{"First[384∈32] ➊^"}}:::plan
    PgSelectRows385[["PgSelectRows[385∈32] ➊^"]]:::plan
    PgSelectRows385 --> First384
    PgSelect380 --> PgSelectRows385
    PgSelectSingle386{{"PgSelectSingle[386∈32] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    First384 --> PgSelectSingle386
    PgClassExpression594{{"PgClassExpression[594∈32] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle386 --> PgClassExpression594
    PgSelect388[["PgSelect[388∈33] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression374 --> PgSelect388
    First392{{"First[392∈33] ➊^"}}:::plan
    PgSelectRows393[["PgSelectRows[393∈33] ➊^"]]:::plan
    PgSelectRows393 --> First392
    PgSelect388 --> PgSelectRows393
    PgSelectSingle394{{"PgSelectSingle[394∈33] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First392 --> PgSelectSingle394
    PgClassExpression595{{"PgClassExpression[595∈33] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle394 --> PgClassExpression595
    PgClassExpression600{{"PgClassExpression[600∈33] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression595 o--o PgClassExpression600
    PgSelect396[["PgSelect[396∈34] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression374 --> PgSelect396
    First400{{"First[400∈34] ➊^"}}:::plan
    PgSelectRows401[["PgSelectRows[401∈34] ➊^"]]:::plan
    PgSelectRows401 --> First400
    PgSelect396 --> PgSelectRows401
    PgSelectSingle402{{"PgSelectSingle[402∈34] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First400 --> PgSelectSingle402
    PgClassExpression596{{"PgClassExpression[596∈34] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle402 --> PgClassExpression596
    PgSelect404[["PgSelect[404∈35] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression374 --> PgSelect404
    First408{{"First[408∈35] ➊^"}}:::plan
    PgSelectRows409[["PgSelectRows[409∈35] ➊^"]]:::plan
    PgSelectRows409 --> First408
    PgSelect404 --> PgSelectRows409
    PgSelectSingle410{{"PgSelectSingle[410∈35] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First408 --> PgSelectSingle410
    PgSelect412[["PgSelect[412∈36] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression374 --> PgSelect412
    First416{{"First[416∈36] ➊^"}}:::plan
    PgSelectRows417[["PgSelectRows[417∈36] ➊^"]]:::plan
    PgSelectRows417 --> First416
    PgSelect412 --> PgSelectRows417
    PgSelectSingle418{{"PgSelectSingle[418∈36] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First416 --> PgSelectSingle418
    PgClassExpression597{{"PgClassExpression[597∈36] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle418 --> PgClassExpression597
    PgSelect427[["PgSelect[427∈40] ➊<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopicᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression421 --> PgSelect427
    First431{{"First[431∈40] ➊^"}}:::plan
    PgSelectRows432[["PgSelectRows[432∈40] ➊^"]]:::plan
    PgSelectRows432 --> First431
    PgSelect427 --> PgSelectRows432
    PgSelectSingle433{{"PgSelectSingle[433∈40] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    First431 --> PgSelectSingle433
    PgClassExpression621{{"PgClassExpression[621∈40] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle433 --> PgClassExpression621
    PgSelect435[["PgSelect[435∈41] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalTopicᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression421 --> PgSelect435
    First439{{"First[439∈41] ➊^"}}:::plan
    PgSelectRows440[["PgSelectRows[440∈41] ➊^"]]:::plan
    PgSelectRows440 --> First439
    PgSelect435 --> PgSelectRows440
    PgSelectSingle441{{"PgSelectSingle[441∈41] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First439 --> PgSelectSingle441
    PgClassExpression622{{"PgClassExpression[622∈41] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle441 --> PgClassExpression622
    PgClassExpression629{{"PgClassExpression[629∈41] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression622 o--o PgClassExpression629
    PgSelect443[["PgSelect[443∈42] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalTopicᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression421 --> PgSelect443
    First447{{"First[447∈42] ➊^"}}:::plan
    PgSelectRows448[["PgSelectRows[448∈42] ➊^"]]:::plan
    PgSelectRows448 --> First447
    PgSelect443 --> PgSelectRows448
    PgSelectSingle449{{"PgSelectSingle[449∈42] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First447 --> PgSelectSingle449
    PgClassExpression623{{"PgClassExpression[623∈42] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle449 --> PgClassExpression623
    PgSelect451[["PgSelect[451∈43] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalTopicᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression421 --> PgSelect451
    First455{{"First[455∈43] ➊^"}}:::plan
    PgSelectRows456[["PgSelectRows[456∈43] ➊^"]]:::plan
    PgSelectRows456 --> First455
    PgSelect451 --> PgSelectRows456
    PgSelectSingle457{{"PgSelectSingle[457∈43] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First455 --> PgSelectSingle457
    PgSelect459[["PgSelect[459∈44] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalTopicᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression421 --> PgSelect459
    First463{{"First[463∈44] ➊^"}}:::plan
    PgSelectRows464[["PgSelectRows[464∈44] ➊^"]]:::plan
    PgSelectRows464 --> First463
    PgSelect459 --> PgSelectRows464
    PgSelectSingle465{{"PgSelectSingle[465∈44] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First463 --> PgSelectSingle465
    PgClassExpression624{{"PgClassExpression[624∈44] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle465 --> PgClassExpression624
    PgSelect472[["PgSelect[472∈45] ➊<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopicᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression466 --> PgSelect472
    First476{{"First[476∈45] ➊^"}}:::plan
    PgSelectRows477[["PgSelectRows[477∈45] ➊^"]]:::plan
    PgSelectRows477 --> First476
    PgSelect472 --> PgSelectRows477
    PgSelectSingle478{{"PgSelectSingle[478∈45] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    First476 --> PgSelectSingle478
    PgClassExpression625{{"PgClassExpression[625∈45] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle478 --> PgClassExpression625
    PgSelect480[["PgSelect[480∈46] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalTopicᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression466 --> PgSelect480
    First484{{"First[484∈46] ➊^"}}:::plan
    PgSelectRows485[["PgSelectRows[485∈46] ➊^"]]:::plan
    PgSelectRows485 --> First484
    PgSelect480 --> PgSelectRows485
    PgSelectSingle486{{"PgSelectSingle[486∈46] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First484 --> PgSelectSingle486
    PgClassExpression626{{"PgClassExpression[626∈46] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle486 --> PgClassExpression626
    PgClassExpression630{{"PgClassExpression[630∈46] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression626 o--o PgClassExpression630
    PgSelect488[["PgSelect[488∈47] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalTopicᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression466 --> PgSelect488
    First492{{"First[492∈47] ➊^"}}:::plan
    PgSelectRows493[["PgSelectRows[493∈47] ➊^"]]:::plan
    PgSelectRows493 --> First492
    PgSelect488 --> PgSelectRows493
    PgSelectSingle494{{"PgSelectSingle[494∈47] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First492 --> PgSelectSingle494
    PgClassExpression627{{"PgClassExpression[627∈47] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle494 --> PgClassExpression627
    PgSelect496[["PgSelect[496∈48] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalTopicᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression466 --> PgSelect496
    First500{{"First[500∈48] ➊^"}}:::plan
    PgSelectRows501[["PgSelectRows[501∈48] ➊^"]]:::plan
    PgSelectRows501 --> First500
    PgSelect496 --> PgSelectRows501
    PgSelectSingle502{{"PgSelectSingle[502∈48] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First500 --> PgSelectSingle502
    PgSelect504[["PgSelect[504∈49] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalTopicᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression466 --> PgSelect504
    First508{{"First[508∈49] ➊^"}}:::plan
    PgSelectRows509[["PgSelectRows[509∈49] ➊^"]]:::plan
    PgSelectRows509 --> First508
    PgSelect504 --> PgSelectRows509
    PgSelectSingle510{{"PgSelectSingle[510∈49] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First508 --> PgSelectSingle510
    PgClassExpression628{{"PgClassExpression[628∈49] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle510 --> PgClassExpression628
    PgSelect517[["PgSelect[517∈50]^<br />ᐸrelational_topicsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression663{{"PgFromExpression[663∈50] ➊<br />ᐳRelationalTopic"}}:::plan
    PgSelectInlineApply908["PgSelectInlineApply[908∈50] ➊<br />ᐳRelationalTopic"]:::plan
    PgClassExpression511 & PgFromExpression663 & PgSelectInlineApply908 --> PgSelect517
    PgSelect684[["PgSelect[684∈50]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression686{{"PgClassExpression[686∈50]^<br />ᐸ__relation...c_item_id”ᐳ"}}:::plan
    PgClassExpression686 --> PgSelect684
    List910{{"List[910∈50]^<br />ᐸ909,523ᐳ"}}:::plan
    Access909{{"Access[909∈50]^<br />ᐸ517.m.joinDetailsFor659ᐳ"}}:::plan
    PgSelectSingle523{{"PgSelectSingle[523∈50]^<br />ᐸrelational_topicsᐳ"}}:::plan
    Access909 & PgSelectSingle523 --> List910
    First521{{"First[521∈50]^"}}:::plan
    PgSelectRows522[["PgSelectRows[522∈50]^"]]:::plan
    PgSelectRows522 --> First521
    PgSelect517 --> PgSelectRows522
    First521 --> PgSelectSingle523
    PgClassExpression646{{"PgClassExpression[646∈50]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle523 --> PgClassExpression646
    First664{{"First[664∈50]^"}}:::plan
    PgSelectRows665[["PgSelectRows[665∈50]^"]]:::plan
    PgSelectRows665 --> First664
    Lambda911{{"Lambda[911∈50]^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda911 --> PgSelectRows665
    PgSelectSingle666{{"PgSelectSingle[666∈50]^<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First664 --> PgSelectSingle666
    PgSelectSingle523 --> PgClassExpression686
    First687{{"First[687∈50]^"}}:::plan
    PgSelectRows688[["PgSelectRows[688∈50]^"]]:::plan
    PgSelectRows688 --> First687
    PgSelect684 --> PgSelectRows688
    PgSelectSingle689{{"PgSelectSingle[689∈50]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First687 --> PgSelectSingle689
    PgClassExpression704{{"PgClassExpression[704∈50]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle689 --> PgClassExpression704
    Object705{{"Object[705∈50]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression704 --> Object705
    PgClassExpression759{{"PgClassExpression[759∈50]^<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle666 --> PgClassExpression759
    PgClassExpression762{{"PgClassExpression[762∈50]^<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle666 --> PgClassExpression762
    Lambda763{{"Lambda[763∈50]^<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression762 --> Lambda763
    PgSelect517 --> Access909
    List910 --> Lambda911
    PgSelect525[["PgSelect[525∈51]<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression511 --> PgSelect525
    PgSelect690[["PgSelect[690∈51]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression694{{"PgClassExpression[694∈51]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression694 --> PgSelect690
    First529{{"First[529∈51]^"}}:::plan
    PgSelectRows530[["PgSelectRows[530∈51]^"]]:::plan
    PgSelectRows530 --> First529
    PgSelect525 --> PgSelectRows530
    PgSelectSingle531{{"PgSelectSingle[531∈51]^<br />ᐸrelational_postsᐳ"}}:::plan
    First529 --> PgSelectSingle531
    PgClassExpression647{{"PgClassExpression[647∈51]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle531 --> PgClassExpression647
    PgClassExpression667{{"PgClassExpression[667∈51]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression647 o--o PgClassExpression667
    PgSelectSingle531 --> PgClassExpression694
    First695{{"First[695∈51]^"}}:::plan
    PgSelectRows696[["PgSelectRows[696∈51]^"]]:::plan
    PgSelectRows696 --> First695
    PgSelect690 --> PgSelectRows696
    PgSelectSingle697{{"PgSelectSingle[697∈51]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First695 --> PgSelectSingle697
    PgClassExpression706{{"PgClassExpression[706∈51]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle697 --> PgClassExpression706
    Object707{{"Object[707∈51]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression706 --> Object707
    PgSelect533[["PgSelect[533∈52]<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression511 --> PgSelect533
    PgSelect668[["PgSelect[668∈52]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression672{{"PgClassExpression[672∈52]^<br />ᐸ__relation...r_item_id”ᐳ"}}:::plan
    PgClassExpression672 --> PgSelect668
    First537{{"First[537∈52]^"}}:::plan
    PgSelectRows538[["PgSelectRows[538∈52]^"]]:::plan
    PgSelectRows538 --> First537
    PgSelect533 --> PgSelectRows538
    PgSelectSingle539{{"PgSelectSingle[539∈52]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First537 --> PgSelectSingle539
    PgClassExpression648{{"PgClassExpression[648∈52]^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle539 --> PgClassExpression648
    PgSelectSingle539 --> PgClassExpression672
    First673{{"First[673∈52]^"}}:::plan
    PgSelectRows674[["PgSelectRows[674∈52]^"]]:::plan
    PgSelectRows674 --> First673
    PgSelect668 --> PgSelectRows674
    PgSelectSingle675{{"PgSelectSingle[675∈52]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First673 --> PgSelectSingle675
    PgClassExpression700{{"PgClassExpression[700∈52]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle675 --> PgClassExpression700
    Object701{{"Object[701∈52]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression700 --> Object701
    PgSelect541[["PgSelect[541∈53]<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression511 --> PgSelect541
    PgSelect649[["PgSelect[649∈53]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression653{{"PgClassExpression[653∈53]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression653 --> PgSelect649
    First545{{"First[545∈53]^"}}:::plan
    PgSelectRows546[["PgSelectRows[546∈53]^"]]:::plan
    PgSelectRows546 --> First545
    PgSelect541 --> PgSelectRows546
    PgSelectSingle547{{"PgSelectSingle[547∈53]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First545 --> PgSelectSingle547
    PgSelectSingle547 --> PgClassExpression653
    First654{{"First[654∈53]^"}}:::plan
    PgSelectRows655[["PgSelectRows[655∈53]^"]]:::plan
    PgSelectRows655 --> First654
    PgSelect649 --> PgSelectRows655
    PgSelectSingle656{{"PgSelectSingle[656∈53]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First654 --> PgSelectSingle656
    PgClassExpression698{{"PgClassExpression[698∈53]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle656 --> PgClassExpression698
    Object699{{"Object[699∈53]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression698 --> Object699
    PgSelect549[["PgSelect[549∈54]<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression511 --> PgSelect549
    PgSelect676[["PgSelect[676∈54]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression680{{"PgClassExpression[680∈54]^<br />ᐸ__relation...m_item_id”ᐳ"}}:::plan
    PgClassExpression680 --> PgSelect676
    First553{{"First[553∈54]^"}}:::plan
    PgSelectRows554[["PgSelectRows[554∈54]^"]]:::plan
    PgSelectRows554 --> First553
    PgSelect549 --> PgSelectRows554
    PgSelectSingle555{{"PgSelectSingle[555∈54]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First553 --> PgSelectSingle555
    PgClassExpression657{{"PgClassExpression[657∈54]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle555 --> PgClassExpression657
    PgSelectSingle555 --> PgClassExpression680
    First681{{"First[681∈54]^"}}:::plan
    PgSelectRows682[["PgSelectRows[682∈54]^"]]:::plan
    PgSelectRows682 --> First681
    PgSelect676 --> PgSelectRows682
    PgSelectSingle683{{"PgSelectSingle[683∈54]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First681 --> PgSelectSingle683
    PgClassExpression702{{"PgClassExpression[702∈54]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle683 --> PgClassExpression702
    Object703{{"Object[703∈54]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression702 --> Object703
    PgSelect710[["PgSelect[710∈55]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    Access709{{"Access[709∈55]^<br />ᐸ708.idᐳ"}}:::plan
    Access709 --> PgSelect710
    __Value708:::plan@{shape: docs, label: "__Combined[708∈55]<br />ᐳRelationalChecklist<br />ᐳRelationalDivider<br />ᐳRelationalChecklistItem<br />ᐳRelationalTopic<br />ᐳRelationalPost"}
    __Value708 --> Access709
    First714{{"First[714∈55]^"}}:::plan
    PgSelectRows715[["PgSelectRows[715∈55]^"]]:::plan
    PgSelectRows715 --> First714
    PgSelect710 --> PgSelectRows715
    PgSelectSingle716{{"PgSelectSingle[716∈55]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First714 --> PgSelectSingle716
    PgClassExpression717{{"PgClassExpression[717∈55]^<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle716 --> PgClassExpression717
    Lambda718{{"Lambda[718∈55]^<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression717 --> Lambda718
    PgClassExpression719{{"PgClassExpression[719∈55]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle716 --> PgClassExpression719
    PgClassExpression824{{"PgClassExpression[824∈55]^<br />ᐸ__relation...parent_id”ᐳ"}}:::plan
    PgSelectSingle716 --> PgClassExpression824
    PgSelect720[["PgSelect[720∈58]^<br />ᐸrelational_topicsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression843{{"PgFromExpression[843∈58] ➊<br />(5) ...ᐳRelationalTopic"}}:::plan
    PgSelectInlineApply949["PgSelectInlineApply[949∈58] ➊<br />(5) ...ᐳRelationalTopic"]:::plan
    PgClassExpression719 & PgFromExpression843 & PgSelectInlineApply949 --> PgSelect720
    List951{{"List[951∈58]^<br />ᐸ950,726ᐳ"}}:::plan
    Access950{{"Access[950∈58]^<br />ᐸ720.m.joinDetailsFor839ᐳ"}}:::plan
    PgSelectSingle726{{"PgSelectSingle[726∈58]^<br />ᐸrelational_topicsᐳ"}}:::plan
    Access950 & PgSelectSingle726 --> List951
    First724{{"First[724∈58]^"}}:::plan
    PgSelectRows725[["PgSelectRows[725∈58]^"]]:::plan
    PgSelectRows725 --> First724
    PgSelect720 --> PgSelectRows725
    First724 --> PgSelectSingle726
    PgClassExpression833{{"PgClassExpression[833∈58]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle726 --> PgClassExpression833
    First844{{"First[844∈58]^"}}:::plan
    PgSelectRows845[["PgSelectRows[845∈58]^"]]:::plan
    PgSelectRows845 --> First844
    Lambda952{{"Lambda[952∈58]^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda952 --> PgSelectRows845
    PgSelectSingle846{{"PgSelectSingle[846∈58]^<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First844 --> PgSelectSingle846
    PgClassExpression848{{"PgClassExpression[848∈58]^<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle846 --> PgClassExpression848
    PgClassExpression851{{"PgClassExpression[851∈58]^<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle846 --> PgClassExpression851
    Lambda852{{"Lambda[852∈58]^<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression851 --> Lambda852
    PgSelect720 --> Access950
    List951 --> Lambda952
    PgSelect728[["PgSelect[728∈59]<br />ᐸrelational_postsᐳ<br />(5) ...ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression719 --> PgSelect728
    First732{{"First[732∈59]^"}}:::plan
    PgSelectRows733[["PgSelectRows[733∈59]^"]]:::plan
    PgSelectRows733 --> First732
    PgSelect728 --> PgSelectRows733
    PgSelectSingle734{{"PgSelectSingle[734∈59]^<br />ᐸrelational_postsᐳ"}}:::plan
    First732 --> PgSelectSingle734
    PgClassExpression834{{"PgClassExpression[834∈59]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle734 --> PgClassExpression834
    PgClassExpression847{{"PgClassExpression[847∈59]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression834 o--o PgClassExpression847
    PgSelect736[["PgSelect[736∈60]<br />ᐸrelational_dividersᐳ<br />(5) ...ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression719 --> PgSelect736
    First740{{"First[740∈60]^"}}:::plan
    PgSelectRows741[["PgSelectRows[741∈60]^"]]:::plan
    PgSelectRows741 --> First740
    PgSelect736 --> PgSelectRows741
    PgSelectSingle742{{"PgSelectSingle[742∈60]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First740 --> PgSelectSingle742
    PgClassExpression835{{"PgClassExpression[835∈60]^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle742 --> PgClassExpression835
    PgSelect744[["PgSelect[744∈61]<br />ᐸrelational_checklistsᐳ<br />(5) ...ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression719 --> PgSelect744
    First748{{"First[748∈61]^"}}:::plan
    PgSelectRows749[["PgSelectRows[749∈61]^"]]:::plan
    PgSelectRows749 --> First748
    PgSelect744 --> PgSelectRows749
    PgSelectSingle750{{"PgSelectSingle[750∈61]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First748 --> PgSelectSingle750
    PgSelect752[["PgSelect[752∈62]<br />ᐸrelational_checklist_itemsᐳ<br />(5) ...ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression719 --> PgSelect752
    First756{{"First[756∈62]^"}}:::plan
    PgSelectRows757[["PgSelectRows[757∈62]^"]]:::plan
    PgSelectRows757 --> First756
    PgSelect752 --> PgSelectRows757
    PgSelectSingle758{{"PgSelectSingle[758∈62]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First756 --> PgSelectSingle758
    PgClassExpression836{{"PgClassExpression[836∈62]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle758 --> PgClassExpression836
    PgSelect765[["PgSelect[765∈63]<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopicᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression759 --> PgSelect765
    First769{{"First[769∈63]^"}}:::plan
    PgSelectRows770[["PgSelectRows[770∈63]^"]]:::plan
    PgSelectRows770 --> First769
    PgSelect765 --> PgSelectRows770
    PgSelectSingle771{{"PgSelectSingle[771∈63]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First769 --> PgSelectSingle771
    PgClassExpression829{{"PgClassExpression[829∈63]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle771 --> PgClassExpression829
    PgSelect773[["PgSelect[773∈64]<br />ᐸrelational_postsᐳ<br />ᐳRelationalTopicᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression759 --> PgSelect773
    First777{{"First[777∈64]^"}}:::plan
    PgSelectRows778[["PgSelectRows[778∈64]^"]]:::plan
    PgSelectRows778 --> First777
    PgSelect773 --> PgSelectRows778
    PgSelectSingle779{{"PgSelectSingle[779∈64]^<br />ᐸrelational_postsᐳ"}}:::plan
    First777 --> PgSelectSingle779
    PgClassExpression830{{"PgClassExpression[830∈64]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle779 --> PgClassExpression830
    PgClassExpression837{{"PgClassExpression[837∈64]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression830 o--o PgClassExpression837
    PgSelect781[["PgSelect[781∈65]<br />ᐸrelational_dividersᐳ<br />ᐳRelationalTopicᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression759 --> PgSelect781
    First785{{"First[785∈65]^"}}:::plan
    PgSelectRows786[["PgSelectRows[786∈65]^"]]:::plan
    PgSelectRows786 --> First785
    PgSelect781 --> PgSelectRows786
    PgSelectSingle787{{"PgSelectSingle[787∈65]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First785 --> PgSelectSingle787
    PgClassExpression831{{"PgClassExpression[831∈65]^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle787 --> PgClassExpression831
    PgSelect789[["PgSelect[789∈66]<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalTopicᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression759 --> PgSelect789
    First793{{"First[793∈66]^"}}:::plan
    PgSelectRows794[["PgSelectRows[794∈66]^"]]:::plan
    PgSelectRows794 --> First793
    PgSelect789 --> PgSelectRows794
    PgSelectSingle795{{"PgSelectSingle[795∈66]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First793 --> PgSelectSingle795
    PgSelect797[["PgSelect[797∈67]<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalTopicᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression759 --> PgSelect797
    First801{{"First[801∈67]^"}}:::plan
    PgSelectRows802[["PgSelectRows[802∈67]^"]]:::plan
    PgSelectRows802 --> First801
    PgSelect797 --> PgSelectRows802
    PgSelectSingle803{{"PgSelectSingle[803∈67]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First801 --> PgSelectSingle803
    PgClassExpression832{{"PgClassExpression[832∈67]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle803 --> PgClassExpression832
    PgSelect854[["PgSelect[854∈69]<br />ᐸrelational_topicsᐳ<br />(5) ...ᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression848 --> PgSelect854
    First858{{"First[858∈69]^"}}:::plan
    PgSelectRows859[["PgSelectRows[859∈69]^"]]:::plan
    PgSelectRows859 --> First858
    PgSelect854 --> PgSelectRows859
    PgSelectSingle860{{"PgSelectSingle[860∈69]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First858 --> PgSelectSingle860
    PgClassExpression903{{"PgClassExpression[903∈69]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle860 --> PgClassExpression903
    PgSelect862[["PgSelect[862∈70]<br />ᐸrelational_postsᐳ<br />(5) ...ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression848 --> PgSelect862
    First866{{"First[866∈70]^"}}:::plan
    PgSelectRows867[["PgSelectRows[867∈70]^"]]:::plan
    PgSelectRows867 --> First866
    PgSelect862 --> PgSelectRows867
    PgSelectSingle868{{"PgSelectSingle[868∈70]^<br />ᐸrelational_postsᐳ"}}:::plan
    First866 --> PgSelectSingle868
    PgClassExpression904{{"PgClassExpression[904∈70]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle868 --> PgClassExpression904
    PgClassExpression907{{"PgClassExpression[907∈70]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression904 o--o PgClassExpression907
    PgSelect870[["PgSelect[870∈71]<br />ᐸrelational_dividersᐳ<br />(5) ...ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression848 --> PgSelect870
    First874{{"First[874∈71]^"}}:::plan
    PgSelectRows875[["PgSelectRows[875∈71]^"]]:::plan
    PgSelectRows875 --> First874
    PgSelect870 --> PgSelectRows875
    PgSelectSingle876{{"PgSelectSingle[876∈71]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First874 --> PgSelectSingle876
    PgClassExpression905{{"PgClassExpression[905∈71]^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle876 --> PgClassExpression905
    PgSelect878[["PgSelect[878∈72]<br />ᐸrelational_checklistsᐳ<br />(5) ...ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression848 --> PgSelect878
    First882{{"First[882∈72]^"}}:::plan
    PgSelectRows883[["PgSelectRows[883∈72]^"]]:::plan
    PgSelectRows883 --> First882
    PgSelect878 --> PgSelectRows883
    PgSelectSingle884{{"PgSelectSingle[884∈72]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First882 --> PgSelectSingle884
    PgSelect886[["PgSelect[886∈73]<br />ᐸrelational_checklist_itemsᐳ<br />(5) ...ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression848 --> PgSelect886
    First890{{"First[890∈73]^"}}:::plan
    PgSelectRows891[["PgSelectRows[891∈73]^"]]:::plan
    PgSelectRows891 --> First890
    PgSelect886 --> PgSelectRows891
    PgSelectSingle892{{"PgSelectSingle[892∈73]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First890 --> PgSelectSingle892
    PgClassExpression906{{"PgClassExpression[906∈73]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle892 --> PgClassExpression906

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect7,Access8,Access9,Object10,Connection11,PgSelect13,PgFromExpression15,First16,PgSelectRows17,PgSelectSingle18,PgSelect20,PgFromExpression22,First23,PgSelectRows24,PgSelectSingle25,PgSelect26,PgFromExpression28,First29,PgSelectRows30,PgSelectSingle31,PgSelect32,PgFromExpression34,First35,PgSelectRows36,PgSelectSingle37,PgSelect39,PgFromExpression41,First42,PgSelectRows43,PgSelectSingle44,PgClassExpression45,PgClassExpression48,PgClassExpression90,PgClassExpression93,ConnectionItems135,PgSelectInlineApply922,Access923,PgFromExpression926,PgSelectInlineApply927,Access928,PgSelectInlineApply931,Access932,PgFromExpression935,PgSelectInlineApply936,Access937,PgSelectInlineApply940,Access941,PgFromExpression944,PgSelectInlineApply945,Access946 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,__CloneStream225 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,First143,PgSelectRows144,PgSelectSingle145,PgClassExpression146,PgClassExpression170,PgClassExpression188,PgClassExpression201,First208,PgSelectRows209,PgSelectSingle210,PgClassExpression284,PgClassExpression287,Lambda288,List924,Lambda925,List929,Lambda930 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,First152,PgSelectRows153,PgSelectSingle154,PgClassExpression155,PgClassExpression176,PgClassExpression194,PgClassExpression202,First215,PgSelectRows216,PgSelectSingle217,PgClassExpression329,PgClassExpression332,Lambda333,List933,Lambda934,List938,Lambda939 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,First161,PgSelectRows162,PgSelectSingle163,PgClassExpression164,PgClassExpression182,PgClassExpression200,PgClassExpression203,First222,PgSelectRows223,PgSelectSingle224,PgClassExpression374,PgClassExpression377,Lambda378,List942,Lambda943,List947,Lambda948 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,PgSelect51,First55,PgSelectRows56,PgSelectSingle57,PgClassExpression256,First270,PgSelectRows271,PgSelectSingle272,PgClassExpression421,PgClassExpression424,Lambda425,PgFromExpression912,PgSelectInlineApply913,Access914,List915,Lambda916 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgSelect59,First63,PgSelectRows64,PgSelectSingle65,PgClassExpression257,PgClassExpression273 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgSelect67,First71,PgSelectRows72,PgSelectSingle73,PgClassExpression258 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgSelect75,First79,PgSelectRows80,PgSelectSingle81 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11,PgSelect83,First87,PgSelectRows88,PgSelectSingle89,PgClassExpression259 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgSelect96,First100,PgSelectRows101,PgSelectSingle102,PgClassExpression260,First280,PgSelectRows281,PgSelectSingle282,PgClassExpression466,PgClassExpression469,Lambda470,PgFromExpression917,PgSelectInlineApply918,Access919,List920,Lambda921 bucket12
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgSelect104,First108,PgSelectRows109,PgSelectSingle110,PgClassExpression261,PgClassExpression283 bucket13
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgSelect112,First116,PgSelectRows117,PgSelectSingle118,PgClassExpression262 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgSelect120,First124,PgSelectRows125,PgSelectSingle126 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16,PgSelect128,First132,PgSelectRows133,PgSelectSingle134,PgClassExpression263 bucket16
    classDef bucket18 stroke:#00bfff
    class Bucket18 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20 bucket20
    classDef bucket21 stroke:#0000ff
    class Bucket21,__Item419,PgSelectSingle420,PgClassExpression511,PgClassExpression514,Lambda515,PgClassExpression641 bucket21
    classDef bucket22 stroke:#7fff00
    class Bucket22,PgSelect290,First294,PgSelectRows295,PgSelectSingle296,PgClassExpression586 bucket22
    classDef bucket23 stroke:#ff1493
    class Bucket23,PgSelect298,First302,PgSelectRows303,PgSelectSingle304,PgClassExpression587,PgClassExpression598 bucket23
    classDef bucket24 stroke:#808000
    class Bucket24,PgSelect306,First310,PgSelectRows311,PgSelectSingle312,PgClassExpression588 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25,PgSelect314,First318,PgSelectRows319,PgSelectSingle320 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,PgSelect322,First326,PgSelectRows327,PgSelectSingle328,PgClassExpression589 bucket26
    classDef bucket27 stroke:#ffff00
    class Bucket27,PgSelect335,First339,PgSelectRows340,PgSelectSingle341,PgClassExpression590 bucket27
    classDef bucket28 stroke:#00ffff
    class Bucket28,PgSelect343,First347,PgSelectRows348,PgSelectSingle349,PgClassExpression591,PgClassExpression599 bucket28
    classDef bucket29 stroke:#4169e1
    class Bucket29,PgSelect351,First355,PgSelectRows356,PgSelectSingle357,PgClassExpression592 bucket29
    classDef bucket30 stroke:#3cb371
    class Bucket30,PgSelect359,First363,PgSelectRows364,PgSelectSingle365 bucket30
    classDef bucket31 stroke:#a52a2a
    class Bucket31,PgSelect367,First371,PgSelectRows372,PgSelectSingle373,PgClassExpression593 bucket31
    classDef bucket32 stroke:#ff00ff
    class Bucket32,PgSelect380,First384,PgSelectRows385,PgSelectSingle386,PgClassExpression594 bucket32
    classDef bucket33 stroke:#f5deb3
    class Bucket33,PgSelect388,First392,PgSelectRows393,PgSelectSingle394,PgClassExpression595,PgClassExpression600 bucket33
    classDef bucket34 stroke:#696969
    class Bucket34,PgSelect396,First400,PgSelectRows401,PgSelectSingle402,PgClassExpression596 bucket34
    classDef bucket35 stroke:#00bfff
    class Bucket35,PgSelect404,First408,PgSelectRows409,PgSelectSingle410 bucket35
    classDef bucket36 stroke:#7f007f
    class Bucket36,PgSelect412,First416,PgSelectRows417,PgSelectSingle418,PgClassExpression597 bucket36
    classDef bucket37 stroke:#ffa500
    class Bucket37 bucket37
    classDef bucket38 stroke:#0000ff
    class Bucket38 bucket38
    classDef bucket39 stroke:#7fff00
    class Bucket39 bucket39
    classDef bucket40 stroke:#ff1493
    class Bucket40,PgSelect427,First431,PgSelectRows432,PgSelectSingle433,PgClassExpression621 bucket40
    classDef bucket41 stroke:#808000
    class Bucket41,PgSelect435,First439,PgSelectRows440,PgSelectSingle441,PgClassExpression622,PgClassExpression629 bucket41
    classDef bucket42 stroke:#dda0dd
    class Bucket42,PgSelect443,First447,PgSelectRows448,PgSelectSingle449,PgClassExpression623 bucket42
    classDef bucket43 stroke:#ff0000
    class Bucket43,PgSelect451,First455,PgSelectRows456,PgSelectSingle457 bucket43
    classDef bucket44 stroke:#ffff00
    class Bucket44,PgSelect459,First463,PgSelectRows464,PgSelectSingle465,PgClassExpression624 bucket44
    classDef bucket45 stroke:#00ffff
    class Bucket45,PgSelect472,First476,PgSelectRows477,PgSelectSingle478,PgClassExpression625 bucket45
    classDef bucket46 stroke:#4169e1
    class Bucket46,PgSelect480,First484,PgSelectRows485,PgSelectSingle486,PgClassExpression626,PgClassExpression630 bucket46
    classDef bucket47 stroke:#3cb371
    class Bucket47,PgSelect488,First492,PgSelectRows493,PgSelectSingle494,PgClassExpression627 bucket47
    classDef bucket48 stroke:#a52a2a
    class Bucket48,PgSelect496,First500,PgSelectRows501,PgSelectSingle502 bucket48
    classDef bucket49 stroke:#ff00ff
    class Bucket49,PgSelect504,First508,PgSelectRows509,PgSelectSingle510,PgClassExpression628 bucket49
    classDef bucket50 stroke:#f5deb3
    class Bucket50,PgSelect517,First521,PgSelectRows522,PgSelectSingle523,PgClassExpression646,PgFromExpression663,First664,PgSelectRows665,PgSelectSingle666,PgSelect684,PgClassExpression686,First687,PgSelectRows688,PgSelectSingle689,PgClassExpression704,Object705,PgClassExpression759,PgClassExpression762,Lambda763,PgSelectInlineApply908,Access909,List910,Lambda911 bucket50
    classDef bucket51 stroke:#696969
    class Bucket51,PgSelect525,First529,PgSelectRows530,PgSelectSingle531,PgClassExpression647,PgClassExpression667,PgSelect690,PgClassExpression694,First695,PgSelectRows696,PgSelectSingle697,PgClassExpression706,Object707 bucket51
    classDef bucket52 stroke:#00bfff
    class Bucket52,PgSelect533,First537,PgSelectRows538,PgSelectSingle539,PgClassExpression648,PgSelect668,PgClassExpression672,First673,PgSelectRows674,PgSelectSingle675,PgClassExpression700,Object701 bucket52
    classDef bucket53 stroke:#7f007f
    class Bucket53,PgSelect541,First545,PgSelectRows546,PgSelectSingle547,PgSelect649,PgClassExpression653,First654,PgSelectRows655,PgSelectSingle656,PgClassExpression698,Object699 bucket53
    classDef bucket54 stroke:#ffa500
    class Bucket54,PgSelect549,First553,PgSelectRows554,PgSelectSingle555,PgClassExpression657,PgSelect676,PgClassExpression680,First681,PgSelectRows682,PgSelectSingle683,PgClassExpression702,Object703 bucket54
    classDef bucket55 stroke:#0000ff
    class Bucket55,__Value708,Access709,PgSelect710,First714,PgSelectRows715,PgSelectSingle716,PgClassExpression717,Lambda718,PgClassExpression719,PgClassExpression824 bucket55
    classDef bucket56 stroke:#7fff00
    class Bucket56 bucket56
    classDef bucket57 stroke:#ff1493
    class Bucket57 bucket57
    classDef bucket58 stroke:#808000
    class Bucket58,PgSelect720,First724,PgSelectRows725,PgSelectSingle726,PgClassExpression833,PgFromExpression843,First844,PgSelectRows845,PgSelectSingle846,PgClassExpression848,PgClassExpression851,Lambda852,PgSelectInlineApply949,Access950,List951,Lambda952 bucket58
    classDef bucket59 stroke:#dda0dd
    class Bucket59,PgSelect728,First732,PgSelectRows733,PgSelectSingle734,PgClassExpression834,PgClassExpression847 bucket59
    classDef bucket60 stroke:#ff0000
    class Bucket60,PgSelect736,First740,PgSelectRows741,PgSelectSingle742,PgClassExpression835 bucket60
    classDef bucket61 stroke:#ffff00
    class Bucket61,PgSelect744,First748,PgSelectRows749,PgSelectSingle750 bucket61
    classDef bucket62 stroke:#00ffff
    class Bucket62,PgSelect752,First756,PgSelectRows757,PgSelectSingle758,PgClassExpression836 bucket62
    classDef bucket63 stroke:#4169e1
    class Bucket63,PgSelect765,First769,PgSelectRows770,PgSelectSingle771,PgClassExpression829 bucket63
    classDef bucket64 stroke:#3cb371
    class Bucket64,PgSelect773,First777,PgSelectRows778,PgSelectSingle779,PgClassExpression830,PgClassExpression837 bucket64
    classDef bucket65 stroke:#a52a2a
    class Bucket65,PgSelect781,First785,PgSelectRows786,PgSelectSingle787,PgClassExpression831 bucket65
    classDef bucket66 stroke:#ff00ff
    class Bucket66,PgSelect789,First793,PgSelectRows794,PgSelectSingle795 bucket66
    classDef bucket67 stroke:#f5deb3
    class Bucket67,PgSelect797,First801,PgSelectRows802,PgSelectSingle803,PgClassExpression832 bucket67
    classDef bucket68 stroke:#696969
    class Bucket68 bucket68
    classDef bucket69 stroke:#00bfff
    class Bucket69,PgSelect854,First858,PgSelectRows859,PgSelectSingle860,PgClassExpression903 bucket69
    classDef bucket70 stroke:#7f007f
    class Bucket70,PgSelect862,First866,PgSelectRows867,PgSelectSingle868,PgClassExpression904,PgClassExpression907 bucket70
    classDef bucket71 stroke:#ffa500
    class Bucket71,PgSelect870,First874,PgSelectRows875,PgSelectSingle876,PgClassExpression905 bucket71
    classDef bucket72 stroke:#0000ff
    class Bucket72,PgSelect878,First882,PgSelectRows883,PgSelectSingle884 bucket72
    classDef bucket73 stroke:#7fff00
    class Bucket73,PgSelect886,First890,PgSelectRows891,PgSelectSingle892,PgClassExpression906 bucket73

    Object699 -.-x __Value708
    Object701 -.-x __Value708
    Object703 -.-x __Value708
    Object705 -.-x __Value708
    Object707 -.-x __Value708
