%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/polymorphic/relay.polyroot_with_related_poly.simple"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 9, 10, 65, 69, 73, 77, 81, 11<br />2: PgSelect[8]<br />3: Connection[12]<br />4: ConnectionItems[14]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 14, 11, 65, 69, 73, 77, 81<br /><br />ROOT Connectionᐸ8ᐳ[12]"):::bucket
    Bucket3("Bucket 3 (listItem)<br />Deps: 11, 65, 69, 73, 77, 81<br /><br />ROOT __Item{3}ᐸ14ᐳ[18]"):::bucket
    Bucket4("Bucket 4 (polymorphic)<br />__typename: Lambda[24]<br />Deps: 24, 11, 20, 65, 69, 73, 77, 81, 23"):::bucket
    Bucket5("Bucket 5 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 11, 20, 65, 69, 73, 77, 81, 23<br />ᐳRelationalTopic<br /><br />1: PgSelect[26]<br />2: PgSelectRows[31]<br />ᐳ: 30, 32, 66, 67, 68<br />3: PgSelect[90]<br />4: PgSelectRows[95]<br />ᐳ: 94, 96, 125, 126"):::bucket
    Bucket6("Bucket 6 (polymorphicPartition)<br />|RelationalPost<br />Deps: 11, 20, 69, 65, 73, 77, 81, 23<br />ᐳRelationalPost<br /><br />1: PgSelect[34]<br />2: PgSelectRows[39]<br />ᐳ: 38, 40, 70, 71, 72<br />3: PgSelect[97]<br />4: PgSelectRows[102]<br />ᐳ: 101, 103, 127, 128"):::bucket
    Bucket7("Bucket 7 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 11, 20, 73, 65, 69, 77, 81, 23<br />ᐳRelationalDivider<br /><br />1: PgSelect[42]<br />2: PgSelectRows[47]<br />ᐳ: 46, 48, 74, 75, 76<br />3: PgSelect[104]<br />4: PgSelectRows[109]<br />ᐳ: 108, 110, 129, 130"):::bucket
    Bucket8("Bucket 8 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 11, 20, 77, 65, 69, 73, 81, 23<br />ᐳRelationalChecklist<br /><br />1: PgSelect[50]<br />2: PgSelectRows[55]<br />ᐳ: 54, 56, 78, 79, 80<br />3: PgSelect[111]<br />4: PgSelectRows[116]<br />ᐳ: 115, 117, 131, 132"):::bucket
    Bucket9("Bucket 9 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 11, 20, 81, 65, 69, 73, 77, 23<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[58]<br />2: PgSelectRows[63]<br />ᐳ: 62, 64, 82, 83, 84<br />3: PgSelect[118]<br />4: PgSelectRows[123]<br />ᐳ: 122, 124, 133, 134"):::bucket
    Bucket10("Bucket 10 (combined)<br />Deps: 11, 65, 69, 73, 77, 81<br /><br />1: <br />ᐳ: Access[136]<br />2: PgSelect[137]<br />3: PgSelectRows[142]<br />ᐳ: 141, 143, 144, 145, 146"):::bucket
    Bucket11("Bucket 11 (polymorphic)<br />__typename: Lambda[145]<br />Deps: 145, 11, 146, 65, 69, 73, 77, 81, 144"):::bucket
    Bucket12("Bucket 12 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 11, 146, 65, 144<br />(5) ...ᐳRelationalTopic<br /><br />1: PgSelect[147]<br />2: PgSelectRows[152]<br />ᐳ: 151, 153, 186, 187, 188"):::bucket
    Bucket13("Bucket 13 (polymorphicPartition)<br />|RelationalPost<br />Deps: 11, 146, 69, 144<br />(5) ...ᐳRelationalPost<br /><br />1: PgSelect[155]<br />2: PgSelectRows[160]<br />ᐳ: 159, 161, 189, 190, 191"):::bucket
    Bucket14("Bucket 14 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 11, 146, 73, 144<br />(5) ...ᐳRelationalDivider<br /><br />1: PgSelect[163]<br />2: PgSelectRows[168]<br />ᐳ: 167, 169, 192, 193, 194"):::bucket
    Bucket15("Bucket 15 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 11, 146, 77, 144<br />(5) ...ᐳRelationalChecklist<br /><br />1: PgSelect[171]<br />2: PgSelectRows[176]<br />ᐳ: 175, 177, 195, 196, 197"):::bucket
    Bucket16("Bucket 16 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 11, 146, 81, 144<br />(5) ...ᐳRelationalChecklistItem<br /><br />1: PgSelect[179]<br />2: PgSelectRows[184]<br />ᐳ: 183, 185, 198, 199, 200"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5 & Bucket6 & Bucket7 & Bucket8 & Bucket9
    Bucket5 --> Bucket10
    Bucket6 --> Bucket10
    Bucket7 --> Bucket10
    Bucket8 --> Bucket10
    Bucket9 --> Bucket10
    Bucket10 --> Bucket11
    Bucket11 --> Bucket12 & Bucket13 & Bucket14 & Bucket15 & Bucket16

    %% plan dependencies
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ<br />Dependents: 17"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    PgSelect8[["PgSelect[8∈0] ➊<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    Connection12[["Connection[12∈0] ➊<br />ᐸ8ᐳ"]]:::plan
    PgSelect8 --> Connection12
    ConnectionItems14[["ConnectionItems[14∈0] ➊"]]:::plan
    Connection12 --> ConnectionItems14
    __Item18[/"__Item[18∈3]<br />ᐸ14ᐳ"\]:::itemplan
    ConnectionItems14 ==> __Item18
    PgSelectSingle19{{"PgSelectSingle[19∈3]<br />ᐸrelational_itemsᐳ"}}:::plan
    __Item18 --> PgSelectSingle19
    PgClassExpression20{{"PgClassExpression[20∈3]<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression20
    PgClassExpression23{{"PgClassExpression[23∈3]<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression23
    Lambda24{{"Lambda[24∈3]<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression23 --> Lambda24
    PgSelect26[["PgSelect[26∈5]<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopic<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression20 --> PgSelect26
    List67{{"List[67∈5]^<br />ᐸ65,66ᐳ<br />More deps:<br />- Constantᐸ'relational_topics'ᐳ[65]"}}:::plan
    PgClassExpression66{{"PgClassExpression[66∈5]^<br />ᐸ__relation...c_item_id”ᐳ"}}:::plan
    PgClassExpression66 --> List67
    PgSelect90[["PgSelect[90∈5]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression66 --> PgSelect90
    First30{{"First[30∈5]^"}}:::plan
    PgSelectRows31[["PgSelectRows[31∈5]^"]]:::plan
    PgSelectRows31 --> First30
    PgSelect26 --> PgSelectRows31
    PgSelectSingle32{{"PgSelectSingle[32∈5]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First30 --> PgSelectSingle32
    PgSelectSingle32 --> PgClassExpression66
    Lambda68{{"Lambda[68∈5]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List67 --> Lambda68
    First94{{"First[94∈5]^"}}:::plan
    PgSelectRows95[["PgSelectRows[95∈5]^"]]:::plan
    PgSelectRows95 --> First94
    PgSelect90 --> PgSelectRows95
    PgSelectSingle96{{"PgSelectSingle[96∈5]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First94 --> PgSelectSingle96
    PgClassExpression125{{"PgClassExpression[125∈5]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle96 --> PgClassExpression125
    Object126{{"Object[126∈5]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression125 --> Object126
    PgSelect34[["PgSelect[34∈6]<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression20 --> PgSelect34
    List71{{"List[71∈6]^<br />ᐸ69,70ᐳ<br />More deps:<br />- Constantᐸ'relational_posts'ᐳ[69]"}}:::plan
    PgClassExpression70{{"PgClassExpression[70∈6]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression70 --> List71
    PgSelect97[["PgSelect[97∈6]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression70 --> PgSelect97
    First38{{"First[38∈6]^"}}:::plan
    PgSelectRows39[["PgSelectRows[39∈6]^"]]:::plan
    PgSelectRows39 --> First38
    PgSelect34 --> PgSelectRows39
    PgSelectSingle40{{"PgSelectSingle[40∈6]^<br />ᐸrelational_postsᐳ"}}:::plan
    First38 --> PgSelectSingle40
    PgSelectSingle40 --> PgClassExpression70
    Lambda72{{"Lambda[72∈6]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List71 --> Lambda72
    First101{{"First[101∈6]^"}}:::plan
    PgSelectRows102[["PgSelectRows[102∈6]^"]]:::plan
    PgSelectRows102 --> First101
    PgSelect97 --> PgSelectRows102
    PgSelectSingle103{{"PgSelectSingle[103∈6]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First101 --> PgSelectSingle103
    PgClassExpression127{{"PgClassExpression[127∈6]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle103 --> PgClassExpression127
    Object128{{"Object[128∈6]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression127 --> Object128
    PgSelect42[["PgSelect[42∈7]<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression20 --> PgSelect42
    List75{{"List[75∈7]^<br />ᐸ73,74ᐳ<br />More deps:<br />- Constantᐸ'relational_dividers'ᐳ[73]"}}:::plan
    PgClassExpression74{{"PgClassExpression[74∈7]^<br />ᐸ__relation...r_item_id”ᐳ"}}:::plan
    PgClassExpression74 --> List75
    PgSelect104[["PgSelect[104∈7]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression74 --> PgSelect104
    First46{{"First[46∈7]^"}}:::plan
    PgSelectRows47[["PgSelectRows[47∈7]^"]]:::plan
    PgSelectRows47 --> First46
    PgSelect42 --> PgSelectRows47
    PgSelectSingle48{{"PgSelectSingle[48∈7]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First46 --> PgSelectSingle48
    PgSelectSingle48 --> PgClassExpression74
    Lambda76{{"Lambda[76∈7]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List75 --> Lambda76
    First108{{"First[108∈7]^"}}:::plan
    PgSelectRows109[["PgSelectRows[109∈7]^"]]:::plan
    PgSelectRows109 --> First108
    PgSelect104 --> PgSelectRows109
    PgSelectSingle110{{"PgSelectSingle[110∈7]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First108 --> PgSelectSingle110
    PgClassExpression129{{"PgClassExpression[129∈7]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle110 --> PgClassExpression129
    Object130{{"Object[130∈7]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression129 --> Object130
    PgSelect50[["PgSelect[50∈8]<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression20 --> PgSelect50
    List79{{"List[79∈8]^<br />ᐸ77,78ᐳ<br />More deps:<br />- Constantᐸ'relational_checklists'ᐳ[77]"}}:::plan
    PgClassExpression78{{"PgClassExpression[78∈8]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression78 --> List79
    PgSelect111[["PgSelect[111∈8]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression78 --> PgSelect111
    First54{{"First[54∈8]^"}}:::plan
    PgSelectRows55[["PgSelectRows[55∈8]^"]]:::plan
    PgSelectRows55 --> First54
    PgSelect50 --> PgSelectRows55
    PgSelectSingle56{{"PgSelectSingle[56∈8]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First54 --> PgSelectSingle56
    PgSelectSingle56 --> PgClassExpression78
    Lambda80{{"Lambda[80∈8]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List79 --> Lambda80
    First115{{"First[115∈8]^"}}:::plan
    PgSelectRows116[["PgSelectRows[116∈8]^"]]:::plan
    PgSelectRows116 --> First115
    PgSelect111 --> PgSelectRows116
    PgSelectSingle117{{"PgSelectSingle[117∈8]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First115 --> PgSelectSingle117
    PgClassExpression131{{"PgClassExpression[131∈8]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle117 --> PgClassExpression131
    Object132{{"Object[132∈8]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression131 --> Object132
    PgSelect58[["PgSelect[58∈9]<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression20 --> PgSelect58
    List83{{"List[83∈9]^<br />ᐸ81,82ᐳ<br />More deps:<br />- Constantᐸ'relational_checklist_items'ᐳ[81]"}}:::plan
    PgClassExpression82{{"PgClassExpression[82∈9]^<br />ᐸ__relation...m_item_id”ᐳ"}}:::plan
    PgClassExpression82 --> List83
    PgSelect118[["PgSelect[118∈9]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression82 --> PgSelect118
    First62{{"First[62∈9]^"}}:::plan
    PgSelectRows63[["PgSelectRows[63∈9]^"]]:::plan
    PgSelectRows63 --> First62
    PgSelect58 --> PgSelectRows63
    PgSelectSingle64{{"PgSelectSingle[64∈9]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First62 --> PgSelectSingle64
    PgSelectSingle64 --> PgClassExpression82
    Lambda84{{"Lambda[84∈9]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List83 --> Lambda84
    First122{{"First[122∈9]^"}}:::plan
    PgSelectRows123[["PgSelectRows[123∈9]^"]]:::plan
    PgSelectRows123 --> First122
    PgSelect118 --> PgSelectRows123
    PgSelectSingle124{{"PgSelectSingle[124∈9]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First122 --> PgSelectSingle124
    PgClassExpression133{{"PgClassExpression[133∈9]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle124 --> PgClassExpression133
    Object134{{"Object[134∈9]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression133 --> Object134
    PgSelect137[["PgSelect[137∈10]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access136{{"Access[136∈10]^<br />ᐸ135.idᐳ"}}:::plan
    Access136 --> PgSelect137
    __Value135:::plan@{shape: docs, label: "__Combined[135∈10]<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}
    __Value135 --> Access136
    First141{{"First[141∈10]^"}}:::plan
    PgSelectRows142[["PgSelectRows[142∈10]^"]]:::plan
    PgSelectRows142 --> First141
    PgSelect137 --> PgSelectRows142
    PgSelectSingle143{{"PgSelectSingle[143∈10]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First141 --> PgSelectSingle143
    PgClassExpression144{{"PgClassExpression[144∈10]^<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle143 --> PgClassExpression144
    Lambda145{{"Lambda[145∈10]^<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression144 --> Lambda145
    PgClassExpression146{{"PgClassExpression[146∈10]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle143 --> PgClassExpression146
    PgSelect147[["PgSelect[147∈12]<br />ᐸrelational_topicsᐳ<br />(5) ...ᐳRelationalTopic<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression146 --> PgSelect147
    List187{{"List[187∈12]^<br />ᐸ65,186ᐳ<br />More deps:<br />- Constantᐸ'relational_topics'ᐳ[65]"}}:::plan
    PgClassExpression186{{"PgClassExpression[186∈12]^<br />ᐸ__relation...c_item_id”ᐳ"}}:::plan
    PgClassExpression186 --> List187
    First151{{"First[151∈12]^"}}:::plan
    PgSelectRows152[["PgSelectRows[152∈12]^"]]:::plan
    PgSelectRows152 --> First151
    PgSelect147 --> PgSelectRows152
    PgSelectSingle153{{"PgSelectSingle[153∈12]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First151 --> PgSelectSingle153
    PgSelectSingle153 --> PgClassExpression186
    Lambda188{{"Lambda[188∈12]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List187 --> Lambda188
    PgSelect155[["PgSelect[155∈13]<br />ᐸrelational_postsᐳ<br />(5) ...ᐳRelationalPost<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression146 --> PgSelect155
    List190{{"List[190∈13]^<br />ᐸ69,189ᐳ<br />More deps:<br />- Constantᐸ'relational_posts'ᐳ[69]"}}:::plan
    PgClassExpression189{{"PgClassExpression[189∈13]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression189 --> List190
    First159{{"First[159∈13]^"}}:::plan
    PgSelectRows160[["PgSelectRows[160∈13]^"]]:::plan
    PgSelectRows160 --> First159
    PgSelect155 --> PgSelectRows160
    PgSelectSingle161{{"PgSelectSingle[161∈13]^<br />ᐸrelational_postsᐳ"}}:::plan
    First159 --> PgSelectSingle161
    PgSelectSingle161 --> PgClassExpression189
    Lambda191{{"Lambda[191∈13]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List190 --> Lambda191
    PgSelect163[["PgSelect[163∈14]<br />ᐸrelational_dividersᐳ<br />(5) ...ᐳRelationalDivider<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression146 --> PgSelect163
    List193{{"List[193∈14]^<br />ᐸ73,192ᐳ<br />More deps:<br />- Constantᐸ'relational_dividers'ᐳ[73]"}}:::plan
    PgClassExpression192{{"PgClassExpression[192∈14]^<br />ᐸ__relation...r_item_id”ᐳ"}}:::plan
    PgClassExpression192 --> List193
    First167{{"First[167∈14]^"}}:::plan
    PgSelectRows168[["PgSelectRows[168∈14]^"]]:::plan
    PgSelectRows168 --> First167
    PgSelect163 --> PgSelectRows168
    PgSelectSingle169{{"PgSelectSingle[169∈14]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First167 --> PgSelectSingle169
    PgSelectSingle169 --> PgClassExpression192
    Lambda194{{"Lambda[194∈14]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List193 --> Lambda194
    PgSelect171[["PgSelect[171∈15]<br />ᐸrelational_checklistsᐳ<br />(5) ...ᐳRelationalChecklist<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression146 --> PgSelect171
    List196{{"List[196∈15]^<br />ᐸ77,195ᐳ<br />More deps:<br />- Constantᐸ'relational_checklists'ᐳ[77]"}}:::plan
    PgClassExpression195{{"PgClassExpression[195∈15]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression195 --> List196
    First175{{"First[175∈15]^"}}:::plan
    PgSelectRows176[["PgSelectRows[176∈15]^"]]:::plan
    PgSelectRows176 --> First175
    PgSelect171 --> PgSelectRows176
    PgSelectSingle177{{"PgSelectSingle[177∈15]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First175 --> PgSelectSingle177
    PgSelectSingle177 --> PgClassExpression195
    Lambda197{{"Lambda[197∈15]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List196 --> Lambda197
    PgSelect179[["PgSelect[179∈16]<br />ᐸrelational_checklist_itemsᐳ<br />(5) ...ᐳRelationalChecklistItem<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression146 --> PgSelect179
    List199{{"List[199∈16]^<br />ᐸ81,198ᐳ<br />More deps:<br />- Constantᐸ'relational_checklist_items'ᐳ[81]"}}:::plan
    PgClassExpression198{{"PgClassExpression[198∈16]^<br />ᐸ__relation...m_item_id”ᐳ"}}:::plan
    PgClassExpression198 --> List199
    First183{{"First[183∈16]^"}}:::plan
    PgSelectRows184[["PgSelectRows[184∈16]^"]]:::plan
    PgSelectRows184 --> First183
    PgSelect179 --> PgSelectRows184
    PgSelectSingle185{{"PgSelectSingle[185∈16]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First183 --> PgSelectSingle185
    PgSelectSingle185 --> PgClassExpression198
    Lambda200{{"Lambda[200∈16]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List199 --> Lambda200

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect8,Access9,Access10,Object11,Connection12,ConnectionItems14 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1 bucket1
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item18,PgSelectSingle19,PgClassExpression20,PgClassExpression23,Lambda24 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgSelect26,First30,PgSelectRows31,PgSelectSingle32,PgClassExpression66,List67,Lambda68,PgSelect90,First94,PgSelectRows95,PgSelectSingle96,PgClassExpression125,Object126 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgSelect34,First38,PgSelectRows39,PgSelectSingle40,PgClassExpression70,List71,Lambda72,PgSelect97,First101,PgSelectRows102,PgSelectSingle103,PgClassExpression127,Object128 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,PgSelect42,First46,PgSelectRows47,PgSelectSingle48,PgClassExpression74,List75,Lambda76,PgSelect104,First108,PgSelectRows109,PgSelectSingle110,PgClassExpression129,Object130 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgSelect50,First54,PgSelectRows55,PgSelectSingle56,PgClassExpression78,List79,Lambda80,PgSelect111,First115,PgSelectRows116,PgSelectSingle117,PgClassExpression131,Object132 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgSelect58,First62,PgSelectRows63,PgSelectSingle64,PgClassExpression82,List83,Lambda84,PgSelect118,First122,PgSelectRows123,PgSelectSingle124,PgClassExpression133,Object134 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,__Value135,Access136,PgSelect137,First141,PgSelectRows142,PgSelectSingle143,PgClassExpression144,Lambda145,PgClassExpression146 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgSelect147,First151,PgSelectRows152,PgSelectSingle153,PgClassExpression186,List187,Lambda188 bucket12
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgSelect155,First159,PgSelectRows160,PgSelectSingle161,PgClassExpression189,List190,Lambda191 bucket13
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgSelect163,First167,PgSelectRows168,PgSelectSingle169,PgClassExpression192,List193,Lambda194 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgSelect171,First175,PgSelectRows176,PgSelectSingle177,PgClassExpression195,List196,Lambda197 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16,PgSelect179,First183,PgSelectRows184,PgSelectSingle185,PgClassExpression198,List199,Lambda200 bucket16

    Object126 -.-x __Value135
    Object128 -.-x __Value135
    Object130 -.-x __Value135
    Object132 -.-x __Value135
    Object134 -.-x __Value135
