%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/polymorphic/simple-log-entries"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 9, 10, 32, 11<br />2: PgSelect[8]<br />3: Connection[12]<br />4: ConnectionItems[14]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 14, 11, 32<br /><br />ROOT Connectionᐸ8ᐳ[12]"):::bucket
    Bucket3("Bucket 3 (listItem)<br />Deps: 11, 32<br /><br />ROOT __Item{3}ᐸ14ᐳ[18]"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 19, 11, 32<br /><br />ROOT PgSelectSingle{3}ᐸlog_entriesᐳ[19]<br />1: <br />ᐳ: 20, 21, 22<br />2: PgUnionAll[23]<br />ᐳ: 55, 27, 30, 31, 33, 34, 36"):::bucket
    Bucket5("Bucket 5 (polymorphic)<br />__typename: Access[36]<br />Deps: 36, 34, 11"):::bucket
    Bucket6("Bucket 6 (polymorphicPartition)<br />|Organization<br />Deps: 34, 11<br />ᐳOrganization<br /><br />1: <br />ᐳ: Access[37]<br />2: PgSelect[38]<br />3: PgSelectRows[43]<br />ᐳ: 42, 44, 53"):::bucket
    Bucket7("Bucket 7 (polymorphicPartition)<br />|Person<br />Deps: 34, 11<br />ᐳPerson<br /><br />1: <br />ᐳ: Access[45]<br />2: PgSelect[46]<br />3: PgSelectRows[51]<br />ᐳ: 50, 52, 54"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6 & Bucket7

    %% plan dependencies
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ<br />Dependents: 4"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    PgSelect8[["PgSelect[8∈0] ➊<br />ᐸlog_entriesᐳ<br />More deps:<br />- Object[11]"]]:::plan
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    Connection12[["Connection[12∈0] ➊<br />ᐸ8ᐳ"]]:::plan
    PgSelect8 --> Connection12
    ConnectionItems14[["ConnectionItems[14∈0] ➊"]]:::plan
    Connection12 --> ConnectionItems14
    __Item18[/"__Item[18∈3]<br />ᐸ14ᐳ"\]:::itemplan
    ConnectionItems14 ==> __Item18
    PgSelectSingle19{{"PgSelectSingle[19∈3]<br />ᐸlog_entriesᐳ"}}:::plan
    __Item18 --> PgSelectSingle19
    PgUnionAll23[["PgUnionAll[23∈4]<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression21{{"PgClassExpression[21∈4]<br />ᐸ__log_entr...person_id”ᐳ"}}:::plan
    PgClassExpression22{{"PgClassExpression[22∈4]<br />ᐸ__log_entr...zation_id”ᐳ"}}:::plan
    PgClassExpression21 & PgClassExpression22 --> PgUnionAll23
    List33{{"List[33∈4]<br />ᐸ30,31,32ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[32]"}}:::plan
    Access30{{"Access[30∈4]<br />ᐸ27.0ᐳ"}}:::plan
    Access31{{"Access[31∈4]<br />ᐸ27.1ᐳ"}}:::plan
    Access30 & Access31 --> List33
    PgClassExpression20{{"PgClassExpression[20∈4]<br />ᐸ__log_entries__.”id”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression20
    PgSelectSingle19 --> PgClassExpression21
    PgSelectSingle19 --> PgClassExpression22
    First27{{"First[27∈4]"}}:::plan
    Access55{{"Access[55∈4]<br />ᐸ23.itemsᐳ"}}:::plan
    Access55 --> First27
    First27 --> Access30
    First27 --> Access31
    Lambda34{{"Lambda[34∈4]<br />ᐸtoSpecifierᐳ"}}:::plan
    List33 --> Lambda34
    Access36{{"Access[36∈4]<br />ᐸ34.__typenameᐳ"}}:::plan
    Lambda34 -->|rejectNull| Access36
    PgUnionAll23 --> Access55
    PgSelect38[["PgSelect[38∈6]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access37{{"Access[37∈6]<br />ᐸ34.organization_idᐳ<br />ᐳOrganization"}}:::plan
    Access37 --> PgSelect38
    Lambda34 -->|rejectNull| Access37
    First42{{"First[42∈6]^"}}:::plan
    PgSelectRows43[["PgSelectRows[43∈6]^"]]:::plan
    PgSelectRows43 --> First42
    PgSelect38 --> PgSelectRows43
    PgSelectSingle44{{"PgSelectSingle[44∈6]^<br />ᐸorganizationsᐳ"}}:::plan
    First42 --> PgSelectSingle44
    PgClassExpression53{{"PgClassExpression[53∈6]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle44 --> PgClassExpression53
    PgSelect46[["PgSelect[46∈7]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access45{{"Access[45∈7]<br />ᐸ34.person_idᐳ<br />ᐳPerson"}}:::plan
    Access45 --> PgSelect46
    Lambda34 -->|rejectNull| Access45
    First50{{"First[50∈7]^"}}:::plan
    PgSelectRows51[["PgSelectRows[51∈7]^"]]:::plan
    PgSelectRows51 --> First50
    PgSelect46 --> PgSelectRows51
    PgSelectSingle52{{"PgSelectSingle[52∈7]^<br />ᐸpeopleᐳ"}}:::plan
    First50 --> PgSelectSingle52
    PgClassExpression54{{"PgClassExpression[54∈7]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle52 --> PgClassExpression54

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect8,Access9,Access10,Object11,Connection12,ConnectionItems14 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1 bucket1
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item18,PgSelectSingle19 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression20,PgClassExpression21,PgClassExpression22,PgUnionAll23,First27,Access30,Access31,List33,Lambda34,Access36,Access55 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,Access37,PgSelect38,First42,PgSelectRows43,PgSelectSingle44,PgClassExpression53 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,Access45,PgSelect46,First50,PgSelectRows51,PgSelectSingle52,PgClassExpression54 bucket7

