%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/polymorphic/vulns.union_owners"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 9, 10, 21, 42, 46, 106, 111, 134, 139, 172, 176, 180, 184, 212, 217, 240, 245, 268, 273, 400, 11<br />2: PgUnionAll[8]<br />3: Connection[12]<br />4: ConnectionItems[13]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 13, 12, 21, 11, 42, 46, 106, 111, 134, 139, 172, 268, 176, 273, 180, 184, 212, 217, 240, 245<br /><br />ROOT Connectionᐸ8ᐳ[12]"):::bucket
    Bucket3("Bucket 3 (listItem)<br />Deps: 21, 11, 42, 46, 106, 111, 134, 139, 172, 268, 176, 273, 180, 184, 212, 217, 240, 245<br /><br />ROOT __Item{3}ᐸ16ᐳ[17]"):::bucket
    Bucket4("Bucket 4 (polymorphic)<br />__typename: Access[25]<br />Deps: 25, 11, 26, 42, 46, 106, 111, 134, 139, 172, 268, 176, 273, 180, 184, 212, 217, 240, 245"):::bucket
    Bucket5("Bucket 5 (polymorphicPartition)<br />|FirstPartyVulnerability<br />Deps: 11, 26, 42, 106, 134, 172, 268, 176, 273, 180, 184, 212, 240<br />ᐳFirstPartyVulnerability<br /><br />1: PgSelect[27]<br />2: PgSelectRows[32]<br />ᐳ: 31, 33, 43, 44, 45, 50<br />3: 52, 62, 66, 72<br />ᐳ: Access[392], Access[393]<br />4: Connection[56], Connection[68]<br />5: 92, 98"):::bucket
    Bucket6("Bucket 6 (polymorphicPartition)<br />|ThirdPartyVulnerability<br />Deps: 11, 26, 46, 111, 139, 172, 268, 176, 273, 180, 184, 217, 245<br />ᐳThirdPartyVulnerability<br /><br />1: PgSelect[35]<br />2: PgSelectRows[40]<br />ᐳ: 39, 41, 47, 48, 49, 51<br />3: 57, 64, 69, 74<br />ᐳ: Access[394], Access[395]<br />4: Connection[61], Connection[71]<br />5: 95, 101"):::bucket
    Bucket7("Bucket 7 (listItem)<br />Deps: 106, 11, 172, 268, 176, 273, 180, 184<br /><br />ROOT __Item{7}ᐸ392ᐳ[84]"):::bucket
    Bucket8("Bucket 8 (listItem)<br />Deps: 111, 11, 172, 268, 176, 273, 180, 184<br /><br />ROOT __Item{8}ᐸ394ᐳ[86]"):::bucket
    Bucket9("Bucket 9 (listItem)<br />Deps: 134, 11, 180, 184<br /><br />ROOT __Item{9}ᐸ393ᐳ[88]"):::bucket
    Bucket10("Bucket 10 (listItem)<br />Deps: 139, 11, 180, 184<br /><br />ROOT __Item{10}ᐸ395ᐳ[90]"):::bucket
    Bucket15("Bucket 15 (combined)<br />Deps: 11, 172, 268, 176, 273, 180, 184"):::bucket
    Bucket16("Bucket 16 (polymorphic)<br />__typename: Access[115]<br />Deps: 115, 11, 116, 172, 268, 176, 273, 180, 184"):::bucket
    Bucket17("Bucket 17 (combined)<br />Deps: 11, 180, 184"):::bucket
    Bucket18("Bucket 18 (polymorphic)<br />__typename: Access[143]<br />Deps: 143, 142, 11, 180, 184"):::bucket
    Bucket19("Bucket 19 (polymorphicPartition)<br />|AwsApplication<br />Deps: 11, 116, 172, 268, 180, 184<br />(2) ...ᐳAwsApplication<br /><br />1: PgSelect[117]<br />2: PgSelectRows[122]<br />ᐳ: 121, 123, 173, 174, 175, 188, 192, 193<br />3: PgUnionAll[194]<br />ᐳ: 396, 198, 266, 267, 269, 270"):::bucket
    Bucket20("Bucket 20 (polymorphicPartition)<br />|GcpApplication<br />Deps: 11, 116, 176, 273, 180, 184<br />(2) ...ᐳGcpApplication<br /><br />1: PgSelect[125]<br />2: PgSelectRows[130]<br />ᐳ: 129, 131, 177, 178, 179, 189, 201, 202<br />3: PgUnionAll[203]<br />ᐳ: 397, 207, 271, 272, 274, 275"):::bucket
    Bucket21("Bucket 21 (polymorphicPartition)<br />|Organization<br />Deps: 142, 11, 180<br />(2) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[144]<br />2: PgSelect[145]<br />3: PgSelectRows[150]<br />ᐳ: 149, 151, 181, 182, 183, 190"):::bucket
    Bucket22("Bucket 22 (polymorphicPartition)<br />|Person<br />Deps: 142, 11, 184<br />(2) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[152]<br />2: PgSelect[153]<br />3: PgSelectRows[158]<br />ᐳ: 157, 159, 185, 186, 187, 191"):::bucket
    Bucket23("Bucket 23 (listItem)<br />Deps: 212, 11, 172, 268, 176, 273, 180, 184<br /><br />ROOT __Item{23}ᐸ92ᐳ[164]"):::bucket
    Bucket24("Bucket 24 (listItem)<br />Deps: 217, 11, 172, 268, 176, 273, 180, 184<br /><br />ROOT __Item{24}ᐸ95ᐳ[166]"):::bucket
    Bucket25("Bucket 25 (listItem)<br />Deps: 240, 11, 180, 184<br /><br />ROOT __Item{25}ᐸ98ᐳ[168]"):::bucket
    Bucket26("Bucket 26 (listItem)<br />Deps: 245, 11, 180, 184<br /><br />ROOT __Item{26}ᐸ101ᐳ[170]"):::bucket
    Bucket27("Bucket 27 (combined)<br />Deps: 11, 172, 268, 176, 273, 180, 184"):::bucket
    Bucket28("Bucket 28 (polymorphic)<br />__typename: Access[221]<br />Deps: 221, 11, 222, 172, 268, 176, 273, 180, 184"):::bucket
    Bucket29("Bucket 29 (combined)<br />Deps: 11, 180, 184"):::bucket
    Bucket30("Bucket 30 (polymorphic)<br />__typename: Access[249]<br />Deps: 249, 248, 11, 180, 184"):::bucket
    Bucket31("Bucket 31 (polymorphicPartition)<br />|AwsApplication<br />Deps: 11, 222, 172, 268, 180, 184<br />(2) ...ᐳAwsApplication<br /><br />1: PgSelect[223]<br />2: PgSelectRows[228]<br />ᐳ: 227, 229, 304, 305, 306, 316, 320, 321<br />3: PgUnionAll[322]<br />ᐳ: 398, 326, 346, 347, 349, 350"):::bucket
    Bucket32("Bucket 32 (polymorphicPartition)<br />|GcpApplication<br />Deps: 11, 222, 176, 273, 180, 184<br />(2) ...ᐳGcpApplication<br /><br />1: PgSelect[231]<br />2: PgSelectRows[236]<br />ᐳ: 235, 237, 307, 308, 309, 317, 329, 330<br />3: PgUnionAll[331]<br />ᐳ: 399, 335, 351, 352, 354, 355"):::bucket
    Bucket33("Bucket 33 (polymorphicPartition)<br />|Organization<br />Deps: 248, 11, 180<br />(2) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[250]<br />2: PgSelect[251]<br />3: PgSelectRows[256]<br />ᐳ: 255, 257, 310, 311, 312, 318"):::bucket
    Bucket34("Bucket 34 (polymorphicPartition)<br />|Person<br />Deps: 248, 11, 184<br />(2) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[258]<br />2: PgSelect[259]<br />3: PgSelectRows[264]<br />ᐳ: 263, 265, 313, 314, 315, 319"):::bucket
    Bucket35("Bucket 35 (combined)<br />Deps: 11, 180, 184"):::bucket
    Bucket36("Bucket 36 (polymorphic)<br />__typename: Access[287]<br />Deps: 287, 286, 11, 180, 184"):::bucket
    Bucket37("Bucket 37 (polymorphicPartition)<br />|Organization<br />Deps: 286, 11, 180<br />(4) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[288]<br />2: PgSelect[289]<br />3: PgSelectRows[294]<br />ᐳ: 293, 295, 338, 339, 340, 344"):::bucket
    Bucket38("Bucket 38 (polymorphicPartition)<br />|Person<br />Deps: 286, 11, 184<br />(4) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[296]<br />2: PgSelect[297]<br />3: PgSelectRows[302]<br />ᐳ: 301, 303, 341, 342, 343, 345"):::bucket
    Bucket39("Bucket 39 (combined)<br />Deps: 11, 180, 184"):::bucket
    Bucket40("Bucket 40 (polymorphic)<br />__typename: Access[367]<br />Deps: 367, 366, 11, 180, 184"):::bucket
    Bucket41("Bucket 41 (polymorphicPartition)<br />|Organization<br />Deps: 366, 11, 180<br />(4) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[368]<br />2: PgSelect[369]<br />3: PgSelectRows[374]<br />ᐳ: 373, 375, 384, 385, 386, 390"):::bucket
    Bucket42("Bucket 42 (polymorphicPartition)<br />|Person<br />Deps: 366, 11, 184<br />(4) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[376]<br />2: PgSelect[377]<br />3: PgSelectRows[382]<br />ᐳ: 381, 383, 387, 388, 389, 391"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5 & Bucket6
    Bucket5 --> Bucket7 & Bucket9 & Bucket23 & Bucket25
    Bucket6 --> Bucket8 & Bucket10 & Bucket24 & Bucket26
    Bucket7 --> Bucket15
    Bucket8 --> Bucket15
    Bucket9 --> Bucket17
    Bucket10 --> Bucket17
    Bucket15 --> Bucket16
    Bucket16 --> Bucket19 & Bucket20
    Bucket17 --> Bucket18
    Bucket18 --> Bucket21 & Bucket22
    Bucket19 --> Bucket35
    Bucket20 --> Bucket35
    Bucket23 --> Bucket27
    Bucket24 --> Bucket27
    Bucket25 --> Bucket29
    Bucket26 --> Bucket29
    Bucket27 --> Bucket28
    Bucket28 --> Bucket31 & Bucket32
    Bucket29 --> Bucket30
    Bucket30 --> Bucket33 & Bucket34
    Bucket31 --> Bucket39
    Bucket32 --> Bucket39
    Bucket35 --> Bucket36
    Bucket36 --> Bucket37 & Bucket38
    Bucket39 --> Bucket40
    Bucket40 --> Bucket41 & Bucket42

    %% plan dependencies
    PgUnionAll8[["PgUnionAll[8∈0] ➊<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />More deps:<br />- Object[11]<br />- Constantᐸ2ᐳ[400]"]]:::plan
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ<br />Dependents: 27"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    Connection12[["Connection[12∈0] ➊<br />ᐸ8ᐳ<br />More deps:<br />- Constantᐸ2ᐳ[400]"]]:::plan
    PgUnionAll8 --> Connection12
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    ConnectionItems13[["ConnectionItems[13∈0] ➊"]]:::plan
    Connection12 --> ConnectionItems13
    __CloneStream16[["__CloneStream[16∈1] ➊"]]:::plan
    ConnectionItems13 --> __CloneStream16
    List22{{"List[22∈3]<br />ᐸ19,20,21ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[21]"}}:::plan
    Access19{{"Access[19∈3]<br />ᐸ17.0ᐳ"}}:::plan
    Access20{{"Access[20∈3]<br />ᐸ17.1ᐳ"}}:::plan
    Access19 & Access20 --> List22
    __Item17[/"__Item[17∈3]<br />ᐸ16ᐳ"\]:::itemplan
    __CloneStream16 ==> __Item17
    __Item17 --> Access19
    __Item17 --> Access20
    Lambda23{{"Lambda[23∈3]<br />ᐸtoSpecifierᐳ"}}:::plan
    List22 --> Lambda23
    Access25{{"Access[25∈3]<br />ᐸ23.__typenameᐳ"}}:::plan
    Lambda23 -->|rejectNull| Access25
    Access26{{"Access[26∈3]<br />ᐸ23.idᐳ"}}:::plan
    Lambda23 -->|rejectNull| Access26
    PgSelect27[["PgSelect[27∈5]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳFirstPartyVulnerability<br />More deps:<br />- Object[11]"]]:::plan
    Access26 --> PgSelect27
    List44{{"List[44∈5]^<br />ᐸ42,43ᐳ<br />More deps:<br />- Constantᐸ'first_party_vulnerabilities'ᐳ[42]"}}:::plan
    PgClassExpression43{{"PgClassExpression[43∈5]^<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgClassExpression43 --> List44
    PgUnionAll52[["PgUnionAll[52∈5]^<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression43 --> PgUnionAll52
    PgUnionAll62[["PgUnionAll[62∈5]^<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression43 --> PgUnionAll62
    PgUnionAll66[["PgUnionAll[66∈5]^<br />ᐸPerson,Organization,Person,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression43 --> PgUnionAll66
    PgUnionAll72[["PgUnionAll[72∈5]^<br />ᐸPerson,Organization,Person,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression43 --> PgUnionAll72
    First31{{"First[31∈5]^"}}:::plan
    PgSelectRows32[["PgSelectRows[32∈5]^"]]:::plan
    PgSelectRows32 --> First31
    PgSelect27 --> PgSelectRows32
    PgSelectSingle33{{"PgSelectSingle[33∈5]^<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First31 --> PgSelectSingle33
    PgSelectSingle33 --> PgClassExpression43
    Lambda45{{"Lambda[45∈5]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List44 --> Lambda45
    PgClassExpression50{{"PgClassExpression[50∈5]^<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression50
    Connection56[["Connection[56∈5]^<br />ᐸ52ᐳ"]]:::plan
    PgUnionAll52 --> Connection56
    Connection68[["Connection[68∈5]^<br />ᐸ66ᐳ"]]:::plan
    PgUnionAll66 --> Connection68
    ConnectionItems92[["ConnectionItems[92∈5]^"]]:::plan
    Connection56 --> ConnectionItems92
    ConnectionItems98[["ConnectionItems[98∈5]^"]]:::plan
    Connection68 --> ConnectionItems98
    Access392{{"Access[392∈5]^<br />ᐸ62.itemsᐳ"}}:::plan
    PgUnionAll62 --> Access392
    Access393{{"Access[393∈5]^<br />ᐸ72.itemsᐳ"}}:::plan
    PgUnionAll72 --> Access393
    PgSelect35[["PgSelect[35∈6]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳThirdPartyVulnerability<br />More deps:<br />- Object[11]"]]:::plan
    Access26 --> PgSelect35
    List48{{"List[48∈6]^<br />ᐸ46,47ᐳ<br />More deps:<br />- Constantᐸ'third_party_vulnerabilities'ᐳ[46]"}}:::plan
    PgClassExpression47{{"PgClassExpression[47∈6]^<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgClassExpression47 --> List48
    PgUnionAll57[["PgUnionAll[57∈6]^<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression47 --> PgUnionAll57
    PgUnionAll64[["PgUnionAll[64∈6]^<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression47 --> PgUnionAll64
    PgUnionAll69[["PgUnionAll[69∈6]^<br />ᐸPerson,Organization,Person,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression47 --> PgUnionAll69
    PgUnionAll74[["PgUnionAll[74∈6]^<br />ᐸPerson,Organization,Person,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression47 --> PgUnionAll74
    First39{{"First[39∈6]^"}}:::plan
    PgSelectRows40[["PgSelectRows[40∈6]^"]]:::plan
    PgSelectRows40 --> First39
    PgSelect35 --> PgSelectRows40
    PgSelectSingle41{{"PgSelectSingle[41∈6]^<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First39 --> PgSelectSingle41
    PgSelectSingle41 --> PgClassExpression47
    Lambda49{{"Lambda[49∈6]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List48 --> Lambda49
    PgClassExpression51{{"PgClassExpression[51∈6]^<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle41 --> PgClassExpression51
    Connection61[["Connection[61∈6]^<br />ᐸ57ᐳ"]]:::plan
    PgUnionAll57 --> Connection61
    Connection71[["Connection[71∈6]^<br />ᐸ69ᐳ"]]:::plan
    PgUnionAll69 --> Connection71
    ConnectionItems95[["ConnectionItems[95∈6]^"]]:::plan
    Connection61 --> ConnectionItems95
    ConnectionItems101[["ConnectionItems[101∈6]^"]]:::plan
    Connection71 --> ConnectionItems101
    Access394{{"Access[394∈6]^<br />ᐸ64.itemsᐳ"}}:::plan
    PgUnionAll64 --> Access394
    Access395{{"Access[395∈6]^<br />ᐸ74.itemsᐳ"}}:::plan
    PgUnionAll74 --> Access395
    List107{{"List[107∈7]^<br />ᐸ104,105,106ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[106]"}}:::plan
    Access104{{"Access[104∈7]^<br />ᐸ84.0ᐳ"}}:::plan
    Access105{{"Access[105∈7]^<br />ᐸ84.1ᐳ"}}:::plan
    Access104 & Access105 --> List107
    __Item84[/"__Item[84∈7]<br />ᐸ392ᐳ<br />ᐳFirstPartyVulnerability"\]:::itemplan
    Access392 ==> __Item84
    __Item84 --> Access104
    __Item84 --> Access105
    Lambda108{{"Lambda[108∈7]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List107 --> Lambda108
    List112{{"List[112∈8]^<br />ᐸ109,110,111ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[111]"}}:::plan
    Access109{{"Access[109∈8]^<br />ᐸ86.0ᐳ"}}:::plan
    Access110{{"Access[110∈8]^<br />ᐸ86.1ᐳ"}}:::plan
    Access109 & Access110 --> List112
    __Item86[/"__Item[86∈8]<br />ᐸ394ᐳ<br />ᐳThirdPartyVulnerability"\]:::itemplan
    Access394 ==> __Item86
    __Item86 --> Access109
    __Item86 --> Access110
    Lambda113{{"Lambda[113∈8]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List112 --> Lambda113
    List135{{"List[135∈9]^<br />ᐸ132,133,134ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[134]"}}:::plan
    Access132{{"Access[132∈9]^<br />ᐸ88.0ᐳ"}}:::plan
    Access133{{"Access[133∈9]^<br />ᐸ88.1ᐳ"}}:::plan
    Access132 & Access133 --> List135
    __Item88[/"__Item[88∈9]<br />ᐸ393ᐳ<br />ᐳFirstPartyVulnerability"\]:::itemplan
    Access393 ==> __Item88
    __Item88 --> Access132
    __Item88 --> Access133
    Lambda136{{"Lambda[136∈9]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List135 --> Lambda136
    List140{{"List[140∈10]^<br />ᐸ137,138,139ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[139]"}}:::plan
    Access137{{"Access[137∈10]^<br />ᐸ90.0ᐳ"}}:::plan
    Access138{{"Access[138∈10]^<br />ᐸ90.1ᐳ"}}:::plan
    Access137 & Access138 --> List140
    __Item90[/"__Item[90∈10]<br />ᐸ395ᐳ<br />ᐳThirdPartyVulnerability"\]:::itemplan
    Access395 ==> __Item90
    __Item90 --> Access137
    __Item90 --> Access138
    Lambda141{{"Lambda[141∈10]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List140 --> Lambda141
    Access115{{"Access[115∈15]^<br />ᐸ114.__typenameᐳ"}}:::plan
    __Value114:::plan@{shape: docs, label: "__Combined[114∈15]<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability"}
    __Value114 --> Access115
    Access116{{"Access[116∈15]^<br />ᐸ114.idᐳ"}}:::plan
    __Value114 --> Access116
    Access143{{"Access[143∈17]^<br />ᐸ142.__typenameᐳ"}}:::plan
    __Value142:::plan@{shape: docs, label: "__Combined[142∈17]<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability"}
    __Value142 --> Access143
    PgUnionAll194[["PgUnionAll[194∈19]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression192{{"PgClassExpression[192∈19]^<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression193{{"PgClassExpression[193∈19]^<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression192 & PgClassExpression193 --> PgUnionAll194
    List269{{"List[269∈19]^<br />ᐸ266,267,268ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[268]"}}:::plan
    Access266{{"Access[266∈19]^<br />ᐸ198.0ᐳ"}}:::plan
    Access267{{"Access[267∈19]^<br />ᐸ198.1ᐳ"}}:::plan
    Access266 & Access267 --> List269
    PgSelect117[["PgSelect[117∈19]<br />ᐸaws_applicationsᐳ<br />(2) ...ᐳAwsApplication<br />More deps:<br />- Object[11]"]]:::plan
    Access116 --> PgSelect117
    List174{{"List[174∈19]^<br />ᐸ172,173ᐳ<br />More deps:<br />- Constantᐸ'aws_applications'ᐳ[172]"}}:::plan
    PgClassExpression173{{"PgClassExpression[173∈19]^<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression173 --> List174
    First121{{"First[121∈19]^"}}:::plan
    PgSelectRows122[["PgSelectRows[122∈19]^"]]:::plan
    PgSelectRows122 --> First121
    PgSelect117 --> PgSelectRows122
    PgSelectSingle123{{"PgSelectSingle[123∈19]^<br />ᐸaws_applicationsᐳ"}}:::plan
    First121 --> PgSelectSingle123
    PgSelectSingle123 --> PgClassExpression173
    Lambda175{{"Lambda[175∈19]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List174 --> Lambda175
    PgClassExpression188{{"PgClassExpression[188∈19]^<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle123 --> PgClassExpression188
    PgSelectSingle123 --> PgClassExpression192
    PgSelectSingle123 --> PgClassExpression193
    First198{{"First[198∈19]^"}}:::plan
    Access396{{"Access[396∈19]^<br />ᐸ194.itemsᐳ"}}:::plan
    Access396 --> First198
    First198 --> Access266
    First198 --> Access267
    Lambda270{{"Lambda[270∈19]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List269 --> Lambda270
    PgUnionAll194 --> Access396
    PgUnionAll203[["PgUnionAll[203∈20]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression201{{"PgClassExpression[201∈20]^<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression202{{"PgClassExpression[202∈20]^<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression201 & PgClassExpression202 --> PgUnionAll203
    List274{{"List[274∈20]^<br />ᐸ271,272,273ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[273]"}}:::plan
    Access271{{"Access[271∈20]^<br />ᐸ207.0ᐳ"}}:::plan
    Access272{{"Access[272∈20]^<br />ᐸ207.1ᐳ"}}:::plan
    Access271 & Access272 --> List274
    PgSelect125[["PgSelect[125∈20]<br />ᐸgcp_applicationsᐳ<br />(2) ...ᐳGcpApplication<br />More deps:<br />- Object[11]"]]:::plan
    Access116 --> PgSelect125
    List178{{"List[178∈20]^<br />ᐸ176,177ᐳ<br />More deps:<br />- Constantᐸ'gcp_applications'ᐳ[176]"}}:::plan
    PgClassExpression177{{"PgClassExpression[177∈20]^<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression177 --> List178
    First129{{"First[129∈20]^"}}:::plan
    PgSelectRows130[["PgSelectRows[130∈20]^"]]:::plan
    PgSelectRows130 --> First129
    PgSelect125 --> PgSelectRows130
    PgSelectSingle131{{"PgSelectSingle[131∈20]^<br />ᐸgcp_applicationsᐳ"}}:::plan
    First129 --> PgSelectSingle131
    PgSelectSingle131 --> PgClassExpression177
    Lambda179{{"Lambda[179∈20]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List178 --> Lambda179
    PgClassExpression189{{"PgClassExpression[189∈20]^<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle131 --> PgClassExpression189
    PgSelectSingle131 --> PgClassExpression201
    PgSelectSingle131 --> PgClassExpression202
    First207{{"First[207∈20]^"}}:::plan
    Access397{{"Access[397∈20]^<br />ᐸ203.itemsᐳ"}}:::plan
    Access397 --> First207
    First207 --> Access271
    First207 --> Access272
    Lambda275{{"Lambda[275∈20]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List274 --> Lambda275
    PgUnionAll203 --> Access397
    PgSelect145[["PgSelect[145∈21]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access144{{"Access[144∈21]<br />ᐸ142.organization_idᐳ<br />(2) ...ᐳOrganization"}}:::plan
    Access144 --> PgSelect145
    List182{{"List[182∈21]^<br />ᐸ180,181ᐳ<br />More deps:<br />- Constantᐸ'organizations'ᐳ[180]"}}:::plan
    PgClassExpression181{{"PgClassExpression[181∈21]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgClassExpression181 --> List182
    __Value142 --> Access144
    First149{{"First[149∈21]^"}}:::plan
    PgSelectRows150[["PgSelectRows[150∈21]^"]]:::plan
    PgSelectRows150 --> First149
    PgSelect145 --> PgSelectRows150
    PgSelectSingle151{{"PgSelectSingle[151∈21]^<br />ᐸorganizationsᐳ"}}:::plan
    First149 --> PgSelectSingle151
    PgSelectSingle151 --> PgClassExpression181
    Lambda183{{"Lambda[183∈21]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List182 --> Lambda183
    PgClassExpression190{{"PgClassExpression[190∈21]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle151 --> PgClassExpression190
    PgSelect153[["PgSelect[153∈22]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access152{{"Access[152∈22]<br />ᐸ142.person_idᐳ<br />(2) ...ᐳPerson"}}:::plan
    Access152 --> PgSelect153
    List186{{"List[186∈22]^<br />ᐸ184,185ᐳ<br />More deps:<br />- Constantᐸ'people'ᐳ[184]"}}:::plan
    PgClassExpression185{{"PgClassExpression[185∈22]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression185 --> List186
    __Value142 --> Access152
    First157{{"First[157∈22]^"}}:::plan
    PgSelectRows158[["PgSelectRows[158∈22]^"]]:::plan
    PgSelectRows158 --> First157
    PgSelect153 --> PgSelectRows158
    PgSelectSingle159{{"PgSelectSingle[159∈22]^<br />ᐸpeopleᐳ"}}:::plan
    First157 --> PgSelectSingle159
    PgSelectSingle159 --> PgClassExpression185
    Lambda187{{"Lambda[187∈22]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List186 --> Lambda187
    PgClassExpression191{{"PgClassExpression[191∈22]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle159 --> PgClassExpression191
    List213{{"List[213∈23]^<br />ᐸ210,211,212ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[212]"}}:::plan
    Access210{{"Access[210∈23]^<br />ᐸ164.0ᐳ"}}:::plan
    Access211{{"Access[211∈23]^<br />ᐸ164.1ᐳ"}}:::plan
    Access210 & Access211 --> List213
    __Item164[/"__Item[164∈23]<br />ᐸ92ᐳ<br />ᐳFirstPartyVulnerability"\]:::itemplan
    ConnectionItems92 ==> __Item164
    __Item164 --> Access210
    __Item164 --> Access211
    Lambda214{{"Lambda[214∈23]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List213 --> Lambda214
    List218{{"List[218∈24]^<br />ᐸ215,216,217ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[217]"}}:::plan
    Access215{{"Access[215∈24]^<br />ᐸ166.0ᐳ"}}:::plan
    Access216{{"Access[216∈24]^<br />ᐸ166.1ᐳ"}}:::plan
    Access215 & Access216 --> List218
    __Item166[/"__Item[166∈24]<br />ᐸ95ᐳ<br />ᐳThirdPartyVulnerability"\]:::itemplan
    ConnectionItems95 ==> __Item166
    __Item166 --> Access215
    __Item166 --> Access216
    Lambda219{{"Lambda[219∈24]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List218 --> Lambda219
    List241{{"List[241∈25]^<br />ᐸ238,239,240ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[240]"}}:::plan
    Access238{{"Access[238∈25]^<br />ᐸ168.0ᐳ"}}:::plan
    Access239{{"Access[239∈25]^<br />ᐸ168.1ᐳ"}}:::plan
    Access238 & Access239 --> List241
    __Item168[/"__Item[168∈25]<br />ᐸ98ᐳ<br />ᐳFirstPartyVulnerability"\]:::itemplan
    ConnectionItems98 ==> __Item168
    __Item168 --> Access238
    __Item168 --> Access239
    Lambda242{{"Lambda[242∈25]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List241 --> Lambda242
    List246{{"List[246∈26]^<br />ᐸ243,244,245ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[245]"}}:::plan
    Access243{{"Access[243∈26]^<br />ᐸ170.0ᐳ"}}:::plan
    Access244{{"Access[244∈26]^<br />ᐸ170.1ᐳ"}}:::plan
    Access243 & Access244 --> List246
    __Item170[/"__Item[170∈26]<br />ᐸ101ᐳ<br />ᐳThirdPartyVulnerability"\]:::itemplan
    ConnectionItems101 ==> __Item170
    __Item170 --> Access243
    __Item170 --> Access244
    Lambda247{{"Lambda[247∈26]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List246 --> Lambda247
    Access221{{"Access[221∈27]^<br />ᐸ220.__typenameᐳ"}}:::plan
    __Value220:::plan@{shape: docs, label: "__Combined[220∈27]<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability"}
    __Value220 --> Access221
    Access222{{"Access[222∈27]^<br />ᐸ220.idᐳ"}}:::plan
    __Value220 --> Access222
    Access249{{"Access[249∈29]^<br />ᐸ248.__typenameᐳ"}}:::plan
    __Value248:::plan@{shape: docs, label: "__Combined[248∈29]<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability"}
    __Value248 --> Access249
    PgUnionAll322[["PgUnionAll[322∈31]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression320{{"PgClassExpression[320∈31]^<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression321{{"PgClassExpression[321∈31]^<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression320 & PgClassExpression321 --> PgUnionAll322
    List349{{"List[349∈31]^<br />ᐸ346,347,268ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[268]"}}:::plan
    Access346{{"Access[346∈31]^<br />ᐸ326.0ᐳ"}}:::plan
    Access347{{"Access[347∈31]^<br />ᐸ326.1ᐳ"}}:::plan
    Access346 & Access347 --> List349
    PgSelect223[["PgSelect[223∈31]<br />ᐸaws_applicationsᐳ<br />(2) ...ᐳAwsApplication<br />More deps:<br />- Object[11]"]]:::plan
    Access222 --> PgSelect223
    List305{{"List[305∈31]^<br />ᐸ172,304ᐳ<br />More deps:<br />- Constantᐸ'aws_applications'ᐳ[172]"}}:::plan
    PgClassExpression304{{"PgClassExpression[304∈31]^<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression304 --> List305
    First227{{"First[227∈31]^"}}:::plan
    PgSelectRows228[["PgSelectRows[228∈31]^"]]:::plan
    PgSelectRows228 --> First227
    PgSelect223 --> PgSelectRows228
    PgSelectSingle229{{"PgSelectSingle[229∈31]^<br />ᐸaws_applicationsᐳ"}}:::plan
    First227 --> PgSelectSingle229
    PgSelectSingle229 --> PgClassExpression304
    Lambda306{{"Lambda[306∈31]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List305 --> Lambda306
    PgClassExpression316{{"PgClassExpression[316∈31]^<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle229 --> PgClassExpression316
    PgSelectSingle229 --> PgClassExpression320
    PgSelectSingle229 --> PgClassExpression321
    First326{{"First[326∈31]^"}}:::plan
    Access398{{"Access[398∈31]^<br />ᐸ322.itemsᐳ"}}:::plan
    Access398 --> First326
    First326 --> Access346
    First326 --> Access347
    Lambda350{{"Lambda[350∈31]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List349 --> Lambda350
    PgUnionAll322 --> Access398
    PgUnionAll331[["PgUnionAll[331∈32]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression329{{"PgClassExpression[329∈32]^<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression330{{"PgClassExpression[330∈32]^<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression329 & PgClassExpression330 --> PgUnionAll331
    List354{{"List[354∈32]^<br />ᐸ351,352,273ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[273]"}}:::plan
    Access351{{"Access[351∈32]^<br />ᐸ335.0ᐳ"}}:::plan
    Access352{{"Access[352∈32]^<br />ᐸ335.1ᐳ"}}:::plan
    Access351 & Access352 --> List354
    PgSelect231[["PgSelect[231∈32]<br />ᐸgcp_applicationsᐳ<br />(2) ...ᐳGcpApplication<br />More deps:<br />- Object[11]"]]:::plan
    Access222 --> PgSelect231
    List308{{"List[308∈32]^<br />ᐸ176,307ᐳ<br />More deps:<br />- Constantᐸ'gcp_applications'ᐳ[176]"}}:::plan
    PgClassExpression307{{"PgClassExpression[307∈32]^<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression307 --> List308
    First235{{"First[235∈32]^"}}:::plan
    PgSelectRows236[["PgSelectRows[236∈32]^"]]:::plan
    PgSelectRows236 --> First235
    PgSelect231 --> PgSelectRows236
    PgSelectSingle237{{"PgSelectSingle[237∈32]^<br />ᐸgcp_applicationsᐳ"}}:::plan
    First235 --> PgSelectSingle237
    PgSelectSingle237 --> PgClassExpression307
    Lambda309{{"Lambda[309∈32]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List308 --> Lambda309
    PgClassExpression317{{"PgClassExpression[317∈32]^<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle237 --> PgClassExpression317
    PgSelectSingle237 --> PgClassExpression329
    PgSelectSingle237 --> PgClassExpression330
    First335{{"First[335∈32]^"}}:::plan
    Access399{{"Access[399∈32]^<br />ᐸ331.itemsᐳ"}}:::plan
    Access399 --> First335
    First335 --> Access351
    First335 --> Access352
    Lambda355{{"Lambda[355∈32]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List354 --> Lambda355
    PgUnionAll331 --> Access399
    PgSelect251[["PgSelect[251∈33]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access250{{"Access[250∈33]<br />ᐸ248.organization_idᐳ<br />(2) ...ᐳOrganization"}}:::plan
    Access250 --> PgSelect251
    List311{{"List[311∈33]^<br />ᐸ180,310ᐳ<br />More deps:<br />- Constantᐸ'organizations'ᐳ[180]"}}:::plan
    PgClassExpression310{{"PgClassExpression[310∈33]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgClassExpression310 --> List311
    __Value248 --> Access250
    First255{{"First[255∈33]^"}}:::plan
    PgSelectRows256[["PgSelectRows[256∈33]^"]]:::plan
    PgSelectRows256 --> First255
    PgSelect251 --> PgSelectRows256
    PgSelectSingle257{{"PgSelectSingle[257∈33]^<br />ᐸorganizationsᐳ"}}:::plan
    First255 --> PgSelectSingle257
    PgSelectSingle257 --> PgClassExpression310
    Lambda312{{"Lambda[312∈33]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List311 --> Lambda312
    PgClassExpression318{{"PgClassExpression[318∈33]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle257 --> PgClassExpression318
    PgSelect259[["PgSelect[259∈34]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access258{{"Access[258∈34]<br />ᐸ248.person_idᐳ<br />(2) ...ᐳPerson"}}:::plan
    Access258 --> PgSelect259
    List314{{"List[314∈34]^<br />ᐸ184,313ᐳ<br />More deps:<br />- Constantᐸ'people'ᐳ[184]"}}:::plan
    PgClassExpression313{{"PgClassExpression[313∈34]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression313 --> List314
    __Value248 --> Access258
    First263{{"First[263∈34]^"}}:::plan
    PgSelectRows264[["PgSelectRows[264∈34]^"]]:::plan
    PgSelectRows264 --> First263
    PgSelect259 --> PgSelectRows264
    PgSelectSingle265{{"PgSelectSingle[265∈34]^<br />ᐸpeopleᐳ"}}:::plan
    First263 --> PgSelectSingle265
    PgSelectSingle265 --> PgClassExpression313
    Lambda315{{"Lambda[315∈34]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List314 --> Lambda315
    PgClassExpression319{{"PgClassExpression[319∈34]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle265 --> PgClassExpression319
    Access287{{"Access[287∈35]^<br />ᐸ286.__typenameᐳ"}}:::plan
    __Value286:::plan@{shape: docs, label: "__Combined[286∈35]<br />(2) ...ᐳAwsApplication<br />(2) ...ᐳGcpApplication"}
    __Value286 --> Access287
    PgSelect289[["PgSelect[289∈37]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access288{{"Access[288∈37]<br />ᐸ286.organization_idᐳ<br />(4) ...ᐳOrganization"}}:::plan
    Access288 --> PgSelect289
    List339{{"List[339∈37]^<br />ᐸ180,338ᐳ<br />More deps:<br />- Constantᐸ'organizations'ᐳ[180]"}}:::plan
    PgClassExpression338{{"PgClassExpression[338∈37]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgClassExpression338 --> List339
    __Value286 --> Access288
    First293{{"First[293∈37]^"}}:::plan
    PgSelectRows294[["PgSelectRows[294∈37]^"]]:::plan
    PgSelectRows294 --> First293
    PgSelect289 --> PgSelectRows294
    PgSelectSingle295{{"PgSelectSingle[295∈37]^<br />ᐸorganizationsᐳ"}}:::plan
    First293 --> PgSelectSingle295
    PgSelectSingle295 --> PgClassExpression338
    Lambda340{{"Lambda[340∈37]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List339 --> Lambda340
    PgClassExpression344{{"PgClassExpression[344∈37]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle295 --> PgClassExpression344
    PgSelect297[["PgSelect[297∈38]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access296{{"Access[296∈38]<br />ᐸ286.person_idᐳ<br />(4) ...ᐳPerson"}}:::plan
    Access296 --> PgSelect297
    List342{{"List[342∈38]^<br />ᐸ184,341ᐳ<br />More deps:<br />- Constantᐸ'people'ᐳ[184]"}}:::plan
    PgClassExpression341{{"PgClassExpression[341∈38]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression341 --> List342
    __Value286 --> Access296
    First301{{"First[301∈38]^"}}:::plan
    PgSelectRows302[["PgSelectRows[302∈38]^"]]:::plan
    PgSelectRows302 --> First301
    PgSelect297 --> PgSelectRows302
    PgSelectSingle303{{"PgSelectSingle[303∈38]^<br />ᐸpeopleᐳ"}}:::plan
    First301 --> PgSelectSingle303
    PgSelectSingle303 --> PgClassExpression341
    Lambda343{{"Lambda[343∈38]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List342 --> Lambda343
    PgClassExpression345{{"PgClassExpression[345∈38]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle303 --> PgClassExpression345
    Access367{{"Access[367∈39]^<br />ᐸ366.__typenameᐳ"}}:::plan
    __Value366:::plan@{shape: docs, label: "__Combined[366∈39]<br />(2) ...ᐳAwsApplication<br />(2) ...ᐳGcpApplication"}
    __Value366 --> Access367
    PgSelect369[["PgSelect[369∈41]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access368{{"Access[368∈41]<br />ᐸ366.organization_idᐳ<br />(4) ...ᐳOrganization"}}:::plan
    Access368 --> PgSelect369
    List385{{"List[385∈41]^<br />ᐸ180,384ᐳ<br />More deps:<br />- Constantᐸ'organizations'ᐳ[180]"}}:::plan
    PgClassExpression384{{"PgClassExpression[384∈41]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgClassExpression384 --> List385
    __Value366 --> Access368
    First373{{"First[373∈41]^"}}:::plan
    PgSelectRows374[["PgSelectRows[374∈41]^"]]:::plan
    PgSelectRows374 --> First373
    PgSelect369 --> PgSelectRows374
    PgSelectSingle375{{"PgSelectSingle[375∈41]^<br />ᐸorganizationsᐳ"}}:::plan
    First373 --> PgSelectSingle375
    PgSelectSingle375 --> PgClassExpression384
    Lambda386{{"Lambda[386∈41]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List385 --> Lambda386
    PgClassExpression390{{"PgClassExpression[390∈41]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle375 --> PgClassExpression390
    PgSelect377[["PgSelect[377∈42]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access376{{"Access[376∈42]<br />ᐸ366.person_idᐳ<br />(4) ...ᐳPerson"}}:::plan
    Access376 --> PgSelect377
    List388{{"List[388∈42]^<br />ᐸ184,387ᐳ<br />More deps:<br />- Constantᐸ'people'ᐳ[184]"}}:::plan
    PgClassExpression387{{"PgClassExpression[387∈42]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression387 --> List388
    __Value366 --> Access376
    First381{{"First[381∈42]^"}}:::plan
    PgSelectRows382[["PgSelectRows[382∈42]^"]]:::plan
    PgSelectRows382 --> First381
    PgSelect377 --> PgSelectRows382
    PgSelectSingle383{{"PgSelectSingle[383∈42]^<br />ᐸpeopleᐳ"}}:::plan
    First381 --> PgSelectSingle383
    PgSelectSingle383 --> PgClassExpression387
    Lambda389{{"Lambda[389∈42]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List388 --> Lambda389
    PgClassExpression391{{"PgClassExpression[391∈42]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle383 --> PgClassExpression391

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgUnionAll8,Access9,Access10,Object11,Connection12,ConnectionItems13 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,__CloneStream16 bucket1
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item17,Access19,Access20,List22,Lambda23,Access25,Access26 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgSelect27,First31,PgSelectRows32,PgSelectSingle33,PgClassExpression43,List44,Lambda45,PgClassExpression50,PgUnionAll52,Connection56,PgUnionAll62,PgUnionAll66,Connection68,PgUnionAll72,ConnectionItems92,ConnectionItems98,Access392,Access393 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgSelect35,First39,PgSelectRows40,PgSelectSingle41,PgClassExpression47,List48,Lambda49,PgClassExpression51,PgUnionAll57,Connection61,PgUnionAll64,PgUnionAll69,Connection71,PgUnionAll74,ConnectionItems95,ConnectionItems101,Access394,Access395 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,__Item84,Access104,Access105,List107,Lambda108 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,__Item86,Access109,Access110,List112,Lambda113 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,__Item88,Access132,Access133,List135,Lambda136 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,__Item90,Access137,Access138,List140,Lambda141 bucket10
    classDef bucket15 stroke:#ff00ff
    class Bucket15,__Value114,Access115,Access116 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16 bucket16
    classDef bucket17 stroke:#696969
    class Bucket17,__Value142,Access143 bucket17
    classDef bucket18 stroke:#00bfff
    class Bucket18 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19,PgSelect117,First121,PgSelectRows122,PgSelectSingle123,PgClassExpression173,List174,Lambda175,PgClassExpression188,PgClassExpression192,PgClassExpression193,PgUnionAll194,First198,Access266,Access267,List269,Lambda270,Access396 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20,PgSelect125,First129,PgSelectRows130,PgSelectSingle131,PgClassExpression177,List178,Lambda179,PgClassExpression189,PgClassExpression201,PgClassExpression202,PgUnionAll203,First207,Access271,Access272,List274,Lambda275,Access397 bucket20
    classDef bucket21 stroke:#0000ff
    class Bucket21,Access144,PgSelect145,First149,PgSelectRows150,PgSelectSingle151,PgClassExpression181,List182,Lambda183,PgClassExpression190 bucket21
    classDef bucket22 stroke:#7fff00
    class Bucket22,Access152,PgSelect153,First157,PgSelectRows158,PgSelectSingle159,PgClassExpression185,List186,Lambda187,PgClassExpression191 bucket22
    classDef bucket23 stroke:#ff1493
    class Bucket23,__Item164,Access210,Access211,List213,Lambda214 bucket23
    classDef bucket24 stroke:#808000
    class Bucket24,__Item166,Access215,Access216,List218,Lambda219 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25,__Item168,Access238,Access239,List241,Lambda242 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,__Item170,Access243,Access244,List246,Lambda247 bucket26
    classDef bucket27 stroke:#ffff00
    class Bucket27,__Value220,Access221,Access222 bucket27
    classDef bucket28 stroke:#00ffff
    class Bucket28 bucket28
    classDef bucket29 stroke:#4169e1
    class Bucket29,__Value248,Access249 bucket29
    classDef bucket30 stroke:#3cb371
    class Bucket30 bucket30
    classDef bucket31 stroke:#a52a2a
    class Bucket31,PgSelect223,First227,PgSelectRows228,PgSelectSingle229,PgClassExpression304,List305,Lambda306,PgClassExpression316,PgClassExpression320,PgClassExpression321,PgUnionAll322,First326,Access346,Access347,List349,Lambda350,Access398 bucket31
    classDef bucket32 stroke:#ff00ff
    class Bucket32,PgSelect231,First235,PgSelectRows236,PgSelectSingle237,PgClassExpression307,List308,Lambda309,PgClassExpression317,PgClassExpression329,PgClassExpression330,PgUnionAll331,First335,Access351,Access352,List354,Lambda355,Access399 bucket32
    classDef bucket33 stroke:#f5deb3
    class Bucket33,Access250,PgSelect251,First255,PgSelectRows256,PgSelectSingle257,PgClassExpression310,List311,Lambda312,PgClassExpression318 bucket33
    classDef bucket34 stroke:#696969
    class Bucket34,Access258,PgSelect259,First263,PgSelectRows264,PgSelectSingle265,PgClassExpression313,List314,Lambda315,PgClassExpression319 bucket34
    classDef bucket35 stroke:#00bfff
    class Bucket35,__Value286,Access287 bucket35
    classDef bucket36 stroke:#7f007f
    class Bucket36 bucket36
    classDef bucket37 stroke:#ffa500
    class Bucket37,Access288,PgSelect289,First293,PgSelectRows294,PgSelectSingle295,PgClassExpression338,List339,Lambda340,PgClassExpression344 bucket37
    classDef bucket38 stroke:#0000ff
    class Bucket38,Access296,PgSelect297,First301,PgSelectRows302,PgSelectSingle303,PgClassExpression341,List342,Lambda343,PgClassExpression345 bucket38
    classDef bucket39 stroke:#7fff00
    class Bucket39,__Value366,Access367 bucket39
    classDef bucket40 stroke:#ff1493
    class Bucket40 bucket40
    classDef bucket41 stroke:#808000
    class Bucket41,Access368,PgSelect369,First373,PgSelectRows374,PgSelectSingle375,PgClassExpression384,List385,Lambda386,PgClassExpression390 bucket41
    classDef bucket42 stroke:#dda0dd
    class Bucket42,Access376,PgSelect377,First381,PgSelectRows382,PgSelectSingle383,PgClassExpression387,List388,Lambda389,PgClassExpression391 bucket42

    Lambda108 -.-x __Value114
    Lambda113 -.-x __Value114
    Lambda136 -.-x __Value142
    Lambda141 -.-x __Value142
    Lambda214 -.-x __Value220
    Lambda219 -.-x __Value220
    Lambda242 -.-x __Value248
    Lambda247 -.-x __Value248
    Lambda270 -.-x __Value286
    Lambda275 -.-x __Value286
    Lambda350 -.-x __Value366
    Lambda355 -.-x __Value366
