%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/connections/basics-limit3"
    Bucket0("Bucket 0 (root)<br /><br />1: PgSelectInlineApply[49]<br />ᐳ: 10, 11, 53, 54, 12, 15<br />2: PgSelect[9], PgSelect[20]<br />ᐳ: Access[31], Access[50]<br />3: Connection[13], PgSelectRows[22]<br />ᐳ: 21, 23, 24<br />4: ConnectionItems[16]<br />5: First[30], Last[33]<br />ᐳ: PgCursor[32], PgCursor[34]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 13, 16, 31, 50, 24, 32, 34<br /><br />ROOT Connectionᐸ9ᐳ[13]"):::bucket
    Bucket3("Bucket 3 (listItem)<br />Deps: 31, 50<br /><br />ROOT __Item{3}ᐸ25ᐳ[26]"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 26, 27, 50, 36<br /><br />ROOT Edge{3}[27]"):::bucket
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 37, 50<br /><br />ROOT PgSelectSingle{4}ᐸmessagesᐳ[37]<br />1: <br />ᐳ: 38, 51, 52<br />2: PgSelectRows[45]<br />ᐳ: First[44], PgSelectSingle[46]"):::bucket
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 46<br /><br />ROOT PgSelectSingle{5}ᐸusersᐳ[46]"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6

    %% plan dependencies
    PgSelect9[["PgSelect[9∈0] ➊<br />ᐸmessages+1ᐳ<br />More deps:<br />- Constantᐸ3ᐳ[54]"]]:::plan
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Lambda15{{"Lambda[15∈0] ➊<br />ᐸincludeArchivedConditionᐳ<br />More deps:<br />- Constantᐸ[ undefined, 'INHERIT' ]ᐳ[53]"}}:::plan
    PgSelectInlineApply49["PgSelectInlineApply[49∈0] ➊"]:::plan
    Object12 & Lambda15 & PgSelectInlineApply49 --> PgSelect9
    PgSelect20[["PgSelect[20∈0] ➊<br />ᐸmessages(aggregate)ᐳ<br />More deps:<br />- Constantᐸ3ᐳ[54]"]]:::plan
    Object12 & Lambda15 --> PgSelect20
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    Connection13[["Connection[13∈0] ➊<br />ᐸ9ᐳ<br />Dependents: 4<br />More deps:<br />- Constantᐸ3ᐳ[54]"]]:::plan
    PgSelect9 --> Connection13
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    ConnectionItems16[["ConnectionItems[16∈0] ➊<br />Dependents: 3<br />More deps:<br />- Connection[13]"]]:::plan
    First21{{"First[21∈0] ➊"}}:::plan
    PgSelectRows22[["PgSelectRows[22∈0] ➊"]]:::plan
    PgSelectRows22 --> First21
    PgSelect20 --> PgSelectRows22
    PgSelectSingle23{{"PgSelectSingle[23∈0] ➊<br />ᐸmessagesᐳ"}}:::plan
    First21 --> PgSelectSingle23
    First30[["First[30∈0] ➊<br />More deps:<br />- ConnectionItems[16]"]]:::plan
    Access31{{"Access[31∈0] ➊<br />ᐸ9.cursorDetailsᐳ<br />Dependents: 3"}}:::plan
    PgSelect9 --> Access31
    Last33[["Last[33∈0] ➊<br />More deps:<br />- ConnectionItems[16]"]]:::plan
    Access50{{"Access[50∈0] ➊<br />ᐸ9.m.joinDetailsFor40ᐳ"}}:::plan
    PgSelect9 --> Access50
    PageInfo19{{"PageInfo[19∈1] ➊<br />More deps:<br />- Connection[13]"}}:::plan
    __CloneStream25[["__CloneStream[25∈1] ➊<br />More deps:<br />- ConnectionItems[16]"]]:::plan
    Lambda28[["Lambda[28∈1] ➊<br />More deps:<br />- Connection[13]"]]:::unbatchedplan
    Lambda29[["Lambda[29∈1] ➊<br />More deps:<br />- Connection[13]"]]:::unbatchedplan
    Edge27{{"Edge[27∈3]"}}:::plan
    __Item26[/"__Item[26∈3]<br />ᐸ25ᐳ"\]:::itemplan
    PgCursor36{{"PgCursor[36∈3]<br />More deps:<br />- Access[31]"}}:::plan
    __Item26 & PgCursor36 --> Edge27
    __Item26 --> PgCursor36
    __CloneStream25 ==> __Item26
    PgSelectSingle37{{"PgSelectSingle[37∈4]<br />ᐸmessagesᐳ"}}:::plan
    __Item26 --> PgSelectSingle37
    List51{{"List[51∈5]<br />ᐸ50,37ᐳ"}}:::plan
    Access50 & PgSelectSingle37 --> List51
    PgClassExpression38{{"PgClassExpression[38∈5]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle37 --> PgClassExpression38
    First44{{"First[44∈5]"}}:::plan
    PgSelectRows45[["PgSelectRows[45∈5]"]]:::plan
    PgSelectRows45 --> First44
    Lambda52{{"Lambda[52∈5]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda52 --> PgSelectRows45
    PgSelectSingle46{{"PgSelectSingle[46∈5]<br />ᐸusersᐳ"}}:::plan
    First44 --> PgSelectSingle46
    List51 --> Lambda52
    PgClassExpression47{{"PgClassExpression[47∈6]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle46 --> PgClassExpression47
    PgClassExpression48{{"PgClassExpression[48∈6]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgClassExpression47 o--o PgClassExpression48

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect9,Access10,Access11,Object12,Connection13,Lambda15,ConnectionItems16,PgSelect20,First21,PgSelectRows22,PgSelectSingle23,First30,Access31,Last33,PgSelectInlineApply49,Access50 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PageInfo19,__CloneStream25,Lambda28,Lambda29 bucket1
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item26,Edge27,PgCursor36 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgSelectSingle37 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression38,First44,PgSelectRows45,PgSelectSingle46,List51,Lambda52 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression47,PgClassExpression48 bucket6

