%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/connections/pagination-when-inlined-backwards-nodes-only"
    Bucket0("Bucket 0 (root)<br /><br />1: PgSelectInlineApply[61]<br />ᐳ: 10, 11, 73, 76, 77, 12, 14, 30<br />2: 65, 69<br />3: PgSelect[9]<br />ᐳ: Access[66], Access[70]<br />4: PgSelectRows[15]"):::bucket
    Bucket1("Bucket 1 (listItem)<br />Deps: 73, 66, 70<br /><br />ROOT __Item{1}ᐸ15ᐳ[17]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 18, 73, 66, 17, 70<br /><br />ROOT PgSelectSingle{1}ᐸforumsᐳ[18]<br />1: <br />ᐳ: 19, 67, 71, 68, 72<br />2: Connection[26]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 26, 72, 68<br /><br />ROOT Connection{2}ᐸ68ᐳ[26]<br />1: 31, 37, 43, 44<br />ᐳ: 34, 46, 62, 36, 38, 39<br />2: __CloneStream[40], First[45], Last[48]<br />ᐳ: PgCursor[47], PgCursor[49]"):::bucket
    Bucket5("Bucket 5 (listItem)<br />Deps: 62<br /><br />ROOT __Item{5}ᐸ40ᐳ[41]"):::bucket
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 42, 62<br /><br />ROOT PgSelectSingle{5}ᐸmessagesᐳ[42]<br />1: <br />ᐳ: 50, 63, 64<br />2: PgSelectRows[57]<br />ᐳ: First[56], PgSelectSingle[58]"):::bucket
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 58<br /><br />ROOT PgSelectSingle{6}ᐸusersᐳ[58]"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket5
    Bucket5 --> Bucket6
    Bucket6 --> Bucket7

    %% plan dependencies
    PgSelect9[["PgSelect[9∈0] ➊<br />ᐸforumsᐳ<br />More deps:<br />- Constantᐸ2ᐳ[73]"]]:::plan
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Lambda14{{"Lambda[14∈0] ➊<br />ᐸincludeArchivedConditionᐳ<br />More deps:<br />- Constantᐸ[ undefined, 'YES' ]ᐳ[76]"}}:::plan
    PgSelectInlineApply65["PgSelectInlineApply[65∈0] ➊<br />More deps:<br />- Constantᐸ2ᐳ[73]"]:::plan
    PgSelectInlineApply69["PgSelectInlineApply[69∈0] ➊"]:::plan
    Object12 & Lambda14 & PgSelectInlineApply65 & PgSelectInlineApply69 --> PgSelect9
    Lambda30{{"Lambda[30∈0] ➊<br />ᐸincludeArchivedConditionᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[77]"}}:::plan
    PgSelectInlineApply61["PgSelectInlineApply[61∈0] ➊"]:::plan
    Lambda30 & PgSelectInlineApply61 --> PgSelectInlineApply65
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    PgSelectRows15[["PgSelectRows[15∈0] ➊"]]:::plan
    PgSelect9 --> PgSelectRows15
    Access66{{"Access[66∈0] ➊<br />ᐸ9.m.subqueryDetailsFor22ᐳ"}}:::plan
    PgSelect9 --> Access66
    Lambda30 --> PgSelectInlineApply69
    Access70{{"Access[70∈0] ➊<br />ᐸ9.m.subqueryDetailsFor35ᐳ"}}:::plan
    PgSelect9 --> Access70
    __Item17[/"__Item[17∈1]<br />ᐸ15ᐳ"\]:::itemplan
    PgSelectRows15 ==> __Item17
    PgSelectSingle18{{"PgSelectSingle[18∈1]<br />ᐸforumsᐳ"}}:::plan
    __Item17 --> PgSelectSingle18
    Connection26[["Connection[26∈2]<br />ᐸ68ᐳ<br />More deps:<br />- Constantᐸ2ᐳ[73]"]]:::plan
    Lambda68{{"Lambda[68∈2]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda68 --> Connection26
    List67{{"List[67∈2]<br />ᐸ66,17ᐳ"}}:::plan
    Access66 & __Item17 --> List67
    List71{{"List[71∈2]<br />ᐸ70,17ᐳ"}}:::plan
    Access70 & __Item17 --> List71
    PgClassExpression19{{"PgClassExpression[19∈2]<br />ᐸ__forums__.”name”ᐳ"}}:::plan
    PgSelectSingle18 --> PgClassExpression19
    List67 --> Lambda68
    Lambda72{{"Lambda[72∈2]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    List71 --> Lambda72
    PgCursor47{{"PgCursor[47∈3]"}}:::plan
    First45[["First[45∈3]"]]:::plan
    Access46{{"Access[46∈3]<br />ᐸ68.cursorDetailsᐳ"}}:::plan
    First45 & Access46 --> PgCursor47
    PgCursor49{{"PgCursor[49∈3]"}}:::plan
    Last48[["Last[48∈3]"]]:::plan
    Last48 & Access46 --> PgCursor49
    ConnectionItems31[["ConnectionItems[31∈3]"]]:::plan
    Connection26 --> ConnectionItems31
    PageInfo34{{"PageInfo[34∈3]"}}:::plan
    Connection26 --> PageInfo34
    First36{{"First[36∈3]"}}:::plan
    PgSelectRows37[["PgSelectRows[37∈3]"]]:::plan
    PgSelectRows37 --> First36
    Lambda72 --> PgSelectRows37
    PgSelectSingle38{{"PgSelectSingle[38∈3]<br />ᐸmessagesᐳ"}}:::plan
    First36 --> PgSelectSingle38
    PgClassExpression39{{"PgClassExpression[39∈3]<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle38 --> PgClassExpression39
    __CloneStream40[["__CloneStream[40∈3]"]]:::plan
    ConnectionItems31 --> __CloneStream40
    Lambda43[["Lambda[43∈3]"]]:::unbatchedplan
    PageInfo34 o--o Lambda43
    Lambda44[["Lambda[44∈3]"]]:::unbatchedplan
    Lambda43 o--o Lambda44
    ConnectionItems31 --> First45
    Lambda68 --> Access46
    ConnectionItems31 --> Last48
    Access62{{"Access[62∈3]<br />ᐸ68.m.joinDetailsFor52ᐳ"}}:::plan
    Lambda68 --> Access62
    __Item41[/"__Item[41∈5]<br />ᐸ40ᐳ"\]:::itemplan
    __CloneStream40 ==> __Item41
    PgSelectSingle42{{"PgSelectSingle[42∈5]<br />ᐸmessagesᐳ"}}:::plan
    __Item41 --> PgSelectSingle42
    List63{{"List[63∈6]<br />ᐸ62,42ᐳ"}}:::plan
    Access62 & PgSelectSingle42 --> List63
    PgClassExpression50{{"PgClassExpression[50∈6]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression50
    First56{{"First[56∈6]"}}:::plan
    PgSelectRows57[["PgSelectRows[57∈6]"]]:::plan
    PgSelectRows57 --> First56
    Lambda64{{"Lambda[64∈6]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda64 --> PgSelectRows57
    PgSelectSingle58{{"PgSelectSingle[58∈6]<br />ᐸusersᐳ"}}:::plan
    First56 --> PgSelectSingle58
    List63 --> Lambda64
    PgClassExpression59{{"PgClassExpression[59∈7]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression59
    PgClassExpression60{{"PgClassExpression[60∈7]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgClassExpression59 o--o PgClassExpression60

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect9,Access10,Access11,Object12,Lambda14,PgSelectRows15,Lambda30,PgSelectInlineApply61,PgSelectInlineApply65,Access66,PgSelectInlineApply69,Access70 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item17,PgSelectSingle18 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression19,Connection26,List67,Lambda68,List71,Lambda72 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,ConnectionItems31,PageInfo34,First36,PgSelectRows37,PgSelectSingle38,PgClassExpression39,__CloneStream40,Lambda43,Lambda44,First45,Access46,PgCursor47,Last48,PgCursor49,Access62 bucket3
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item41,PgSelectSingle42 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression50,First56,PgSelectRows57,PgSelectSingle58,List63,Lambda64 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression59,PgClassExpression60 bucket7

