## expect(errors).toBeFalsy()
## expect(queries).toHaveLength(3);
{
  forums(includeArchived: EXCLUSIVELY) {
    name
    messagesConnection(includeArchived: INHERIT) {
      # nodes and edges share one fetch up front instead of duplicating streams.
      # pageInfo also requires materialization, even though it is deferred.
      nodes @stream {
        body
        author {
          username
          gravatarUrl
        }
      }
      edges @stream {
        cursor
        node {
          body
          author {
            username
            gravatarUrl
          }
        }
      }
      ... @defer {
        pageInfo {
          hasNextPage
          hasPreviousPage
        }
        totalCount
      }
    }
  }
}
