import { Buffer } from "node:buffer";

// Generated by webpack (see webpack.config.mts). Placeholder for type-checking.
export const bundleData: Record<string, { etag: string; buffer: Buffer }> = {};
